Step 2 : 위치정보 확인 및 날씨 API 호출 (리나)
yagom-academy/ios-weather-forecast pull request #10
Opened 2021-01-19 03:30 UTC by lina0322

@AppleCEO

안녕하세요 도미닉🙇🏻‍♀️

### [수정 사항]
1. Codable -> Decodable
붱이🦉에게 조언을 듣고, 도미닉🍎이 다른 캠퍼들에게 남긴 리뷰를 본 후, 
아래 솔리드 원칙을 따라 수정하였습니다. 
> __Interface Segregation Principle(인터페이스 분리 원칙)__
 한 클래스는 자신이 사용하지 않는 인터페이스는 구현하지 말아야 한다. 
 하나의 일반적인 인터페이스보다는, 여러 개의 구체적인 인터페이스가 낫다.

</br>

2. Temperature 수정
섭씨 온도를 사용하기 위해, enum 내부에 함수를 추가한 후, 연산프로퍼티를 활용하여 값을 저장할 준비를 하였습니다.
> 테이블 뷰 작업을 할때 섭씨로 변환할까 하다가, 
Temperature이 온도와 관련된 것은 모두 들고있는게 맞다고 생각하여 이렇게 적용했습니다.

</br>

3. WeatherIcon에 url 추가
온도와 마찬가지로, icon과 관련된 url도 WeatherIcon이 가지고 있는게 맞다고 생각했습니다.
다만 api주소가 변경될 수 있어서, format 형식으로 작성하고 url 자체는 Api에 보관했습니다.

</br>

### [구현 사항]
1. Api enum을 따로 구현하여, api관련 정보를 따로 보관 할수 있도록 하였습니다.
> 네이밍에 어려움이 있었습니다..ㅠㅠ 어떻게 하면 좋을지 아직도 모르겠습니다;

</br>

2. InitialValue enum을 구현하여, 기본 값을 모아두었습니다.
> 여기서 저의 고민이, 만약 사용자가 위치정보를 거부할 경우에 어떻게 해야하나였습니다.
거부했다고해서 아무것도 안보여줄 수 는 없으니, '남산'을 기본값으로 정해두어서 거부하여도 남산 날씨를 볼 수 있도록 하였습니다.⛰

</br>

3. CLLocationManager을 이용하여 현재 위도와 경도를 받아옵니다.
> 사용자가 거부하여 위치를 받아오지 못해도, 기본 남산 위치가 저장되어 있기 때문에 아래 작업들을 수행합니다.
</br>

4. 위도와 경도를 바탕으로, url을 구성하고 URLSession과 JSONDecoder을 이용하여, 현재 날씨와 일기 예보를 받아왔습니다.

5. CLGeocoder를 사용하여 현재 위치를 우리나라 주소로 만들었습니다.

</br>

### [고민]
1. 사용자가 위치 설정을 거부할 경우, 현재 위치가 아니라 기본 위치로 날씨를 보여준다고 메세지를 띄워야할 것 같다는 생각이 들었습니다.
그래서 toast message를 구현해봤는데, 이렇게 하는게 좋을지 아니면 네이버지도처럼 아무것도 안띄워도 괜찮을지 조언을 듣고싶습니다!
> message를 보여주는 이유: 사용자에게 현재 위치를 불러올 수 없어서, 기본 위치로 날씨를 보여준다고 알려주려고
message를 보여주지 않아도 될거같은 이유: 상단에 현재 위치가 아니라, 남산 위치가 뜰거라서 사용자도 알 수 있을거라고 생각

</br>

2. decoding 부분에 대한 고민이 있습니다.
현재날씨를 가져오는것과, 일기예보를 가져오는 두 개의 코드가 너무 겹치는데.. 어떻게하면 중복을 줄일 수 있을지 감이 안옵니다.
힌트 주실 수 있나요🥺

</br>

와우 생각보다 너무 길게썼네요;;🤦🏻‍♀️
아직 부족한 코드이지만... 혼자서는 해결이 안될거같아서 제출합니다🥺
시간 내주셔서 감사합니다.. 헿...🙇🏻‍♀️

2021-01-19 07:28 UTC, AppleCEO requested changes
리나 고생하셨습니다.
구조를 잘 짜신 것 같습니다.
몇가지 코멘트 남겨놨습니다.
개선해보시고 피드백 해주세요.

2021-01-19 07:28 UTC, AppleCEO commented on WeatherForecast/WeatherForecast/ViewController.swift
> -//
자신이 작성한 코드라면 이 부분을 바꿔보는 것도 좋을 것 같네요.

2021-01-19 07:28 UTC, AppleCEO commented on WeatherForecast/WeatherForecast/ViewController.swift
> +        let dataTask = session.dataTask(with: url) { data, _, _ in
혹시 HTTP 메서드가 POST면 어떻게 통신해야 할까요?
GET 메소드라는 것을 명시적으로 표현해볼 수 있을까요?

2021-01-19 07:28 UTC, AppleCEO commented on WeatherForecast/WeatherForecast/ViewController.swift
> +        let forecastURL = String(format: Api.url, Api.Kind.forecast.rawValue, latitude, longitude, Api.myKey)
이 방식도 좋은 것 같은데요. 👍 
저는 메소드로 어떤 값들이 들어가야하는지 명시적으로 표현될 수 있으면 좋을 것 같습니다.
이렇게 작성하면 Api.url 을 사용하다가 순서를 바꿔서 인자를 넣을 수도 있을 것 같아서요.
참고해주세요 ㅎㅎ

2021-01-19 07:28 UTC, AppleCEO commented on WeatherForecast/WeatherForecast/ViewController.swift
> +                self.showToast(message: StringFormattingError.unknown.description)
알 수 없는 에러이기 보다 디코드를 못한 상황인 것 같은데 더 명시적인 에러 메시지로 띄워볼 수 있지 않을까요?

2021-01-19 07:28 UTC, AppleCEO commented on WeatherForecast/WeatherForecast/ViewController.swift
> +            }
if let 에 있는 내용을 guard let에 넣어도 될 것 같네요.
이렇게 나눈 이유가 있을까요?

2021-01-19 07:28 UTC, AppleCEO commented on WeatherForecast/WeatherForecast/ViewController.swift
> +        setUpData()
setUpData 메소드에서만 latitude, longitude 값을 사용하는 것 같습니다.
프로퍼티로 선언하지 않고 setUpData 에 인자로 보내서 사용하는 것은 어떨까요?

2021-01-21 11:55 UTC, lina0322 commented
@AppleCEO 

안녕하세요 도미닉🙇🏻‍♀️
이것저것 하다가.. 이제서야 이렇게 보내게됐네요. 하하하..💦

### [1번] 
> CurrentWather 을 Weather 로 변경한 이유는 무엇인가요?

currentWeather이라고 하기에는 모델이 Weather 자체라고 생각이 들었습니다.
그 안에는 아이콘과 온도에 대한 정보만들어있기 때문에 타입 자체가 현재날씨라고 보기는 어렵다고 생각이 들었고,
변수는 진짜 current weather을 가져오는 것이라고 생각되어 그대로 두고, 타입의 이름만 변경하게 되었습니다!


### [2번]
> 오호 이렇게 연산 프로퍼티로 활용한 것도 괜찮네요. 조금 혼돈될 수 도 있을 것 같아요. 이 값이 JSON으로 가져온 값인지요.
어떻게 생각하시나요?

도미닉 말을 들어보니, 이 값이 JSON 값인지 안에서 저장한 값인지 잘 모를 수 있다고 생각이 들었습니다ㅠㅠ
그런데 딱히 해결책은 떠오르지 않았고🥲
나중에 사용할때를 위해서, 사용하지 않을 프로퍼티들을 private로 막아보았습니다.
요 질문에 대한 해답은 찾지 못했네요🥺


### [3번]
> if let 에 있는 내용을 guard let에 넣어도 될 것 같네요.
이렇게 나눈 이유가 있을까요?

당시에는... place로 address배열이 생성되어야 아래의 내용을 할 수 있다고 생각했던 것 같아요.
다시 살펴보니 guard let이 나을 것 같아서 변경하였습니다!!


본다고 다시 봤는데, 뭔가 코드가 맘에 들지 않네요😭
도미닉의 눈에 거슬리는 것들 가감없이 말씀해주셔도 됩니당...하하하 

항상 시간내주셔서 감사합니다🙇🏻‍♀️

2021-01-21 12:50 UTC, lina0322 commented
도미닉!
제가 위쪽에 댓글남긴 이후에... 다시 살펴보면서 수정하고 싶은 것들이 생겨서 수정해보았습니다!
위에 태그 달아서 따로 태그는 안달게요... ~~메일 너무 많이갔죠..?💦~~

#### [4번]
api를 받기위해 사용하는 url을 만드는 방식을 변경하였습니다.

#### [5번]
locationManagerDidChangeAuthorization를 구현하여, 토스트 메세지가 뜨는 타이밍을 개선하였습니다.
</br>
감사합니다🙇🏻‍♀️

2021-01-21 15:37 UTC, AppleCEO approved these changes
리나 고생하셨습니다.
다음 단계를 진행하면서 코멘트 달은 내용은 생각해보시면 되겠습니다.

2021-01-21 15:37 UTC, AppleCEO commented on WeatherForecast/WeatherForecast/ViewController.swift
> +            guard let address: [CLPlacemark] = place, let city = address.last?.administrativeArea, let road = address.last?.thoroughfare else {
adress.last? 라고 한 부분을 옵셔널 언레핑해서 활용할 수는 없을까요?

2021-01-21 15:37 UTC, AppleCEO commented on WeatherForecast/WeatherForecast/Info.plist
> +	<string>현재 위치의 일기예보를 받아오기 위해 필요합니다.</string>
명확한 이유를 적어주는 것은 좋습니다!

2021-01-21 15:38 UTC, merged