Step 1: 타입 구현 - Glenn
yagom-academy/ios-weather-forecast pull request #14
Opened 2021-01-19 11:01 UTC by iluxsm

@delmaSong 
안녕하세요, 델마! 👋
JuiceMaker 프로젝트 이후로 오랜만에 리뷰 신청드리네요!
리뷰 잘 부탁드립니다~ 🙇‍♂️

# 구현 내용
1. 버전 호환성을 위해 SceneDelegate.swift와 해당 plist의 Key를 삭제하고, window 변수를 AppDelegate.swift로 옮겨줬습니다.
2. 총 두 가지의 큰 기능(현재 날씨 & 5일 예보)을 나누어 CurrentWeather 와 FiveDaysForecast에 구현했습니다.
3. 공통적인 타입으로 Coordinates, Weather, Temperature을 구현했습니다.
4. weather 데이터가 배열로 감싸져있어서 접근할 때 [Weather] 로 접근하도록 구현했습니다.
5. FiveDaysForecast API에서 중첩구조로 되어있는 데이터에 접근하기 위해 ListForAccess와 CityForAccess 타입을 구현했습니다.

# 고민 내용
1. 여러 상황에 의해 데이터가 유실됐을 경우, Key Not Found 또는 Value Not Found(nil) 에러가 생길 수 있다고 생각해서 옵셔널로 구현한 후, init(from:) 을 통해 기본 값을 넣어주려고 했지만, 
    1. 꼭 필요한 데이터의 경우 유실된 것에 에러가 생기지 않고 기본 값으로 대체되면 알아차리기 힘든 점이 있고, 
    2. 사용자가 기본 값과 일치하는 위치에 있을 경우, 정상 동작한다고 착각을 할 수 있다고 생각하여 
구현하지 않았습니다. 이 부분에 대해서 어떤 처리가 더 나은 것인지 의견을 묻고싶습니다.

이상입니다 😶
바쁘실텐데 시간 내주셔서 감사드리고, 감기 조심하세요~

2021-01-19 14:16 UTC, delmaSong requested changes
수고하셨습니다! 코드와 PR 메시지에 고민한 흔적들이 엿보여 좋았습니다 😀

>여러 상황에 의해 데이터가 유실됐을 경우, Key Not Found 또는 Value Not Found(nil) 에러가 생길 수 있다고 생각해서 옵셔널로 구현한 후, init(from:) 을 통해 기본 값을 넣어주려고 했지만,
꼭 필요한 데이터의 경우 유실된 것에 에러가 생기지 않고 기본 값으로 대체되면 알아차리기 힘든 점이 있고,
사용자가 기본 값과 일치하는 위치에 있을 경우, 정상 동작한다고 착각을 할 수 있다고 생각하여
구현하지 않았습니다. 이 부분에 대해서 어떤 처리가 더 나은 것인지 의견을 묻고싶습니다.

기본적으로 데이터가 있을 수도 있고 없을 수도 있는 것의 판단은 서버에서 합니다. 무조건 존재하는 필드라면 non-optional 타입으로 만들고, 서버에서 보내주지 않을 수도 있는 값이라면 optional 타입으로 만듭니다. 
말씀하신대로 데이터의 유실에 대한 것이라면 그것을 모델 부분에서 거르기보다는 일단 요청을 보내고 받아왔을 때 `값이 누락되지 않았는지, 미리 정의된 API에 맞게 보내주는지(제대로 디코딩이되는지)` 등을 판단합니다. 
현재 단계에선 API문서에 알맞게 모델을 생성해주고 그 이후에 디코딩 작업을 하면서 여러 발생가능한 에러상황에 대응하는 방어코드등을 작성해주시면 될 것 같습니다 😇

현재 `제대로 디코딩이 되는지`를 파악하는 작업을 해주시면 되겠습니다. 제가 확인하기론 제대로 디코딩이 되지 않고있네요

2021-01-19 14:16 UTC, delmaSong commented on WeatherForecast/WeatherForecast/CurrentWeather.swift
> +        case weather
아주 깔끔하고 좋네요 👍🏼
그런데 CurrentAPI JSON의 여러 필드 중 이 값들만 선정하신 이유가 무엇인지 궁금합니다
그리고 날씨와 온도가 같은 다른 날의 CurrentWeather는 어떻게 구분 가능한가요?

2021-01-19 14:16 UTC, delmaSong commented on WeatherForecast/WeatherForecast/ListForAccess.swift
> +    let temperature: Temperature
어떤 접근을 위한 무슨 리스트 라는건지 영 감이 안옵니다 🙃
이름을 바꿔봅시다!

2021-01-19 14:16 UTC, delmaSong commented on WeatherForecast/WeatherForecast/Weather.swift
> +}
날씨에 정말 icon만 필요한가요??????

2021-01-19 14:16 UTC, delmaSong commented on WeatherForecast/WeatherForecast/FiveDaysForecast.swift
> +    let city: CityForAccess
넘어오는 값을 디코딩해서 확인해보셨나요? 잘 변환이 되던가요?

2021-01-19 14:16 UTC, delmaSong commented on WeatherForecast/WeatherForecast/Temperature.swift
> +    }
요구사항 문서에는 온도를 섭씨단위로 사용한다고 나와있는데, 이 `Temperature`의 단위는 어떻게 되나요?

2021-01-20 15:20 UTC, iluxsm commented on WeatherForecast/WeatherForecast/FiveDaysForecast.swift
> +    let city: CityForAccess
JSON 데이터에서 볼 때, 위도 및 경도에 접근하려면 `coord` 키로 접근이 가능해야하는데 `coord` 키가 city로 한 번 감싸져있어서 해당 타입이 필요하다고 생각해요.

2021-01-20 15:22 UTC, iluxsm commented on WeatherForecast/WeatherForecast/CityForAccess.swift
> +    enum CordingKeys: String, CodingKey {
위도 경도로 API를 호출하기 때문에 해당 정보 이외의 위치 정보는 필요없다고 생각했어요. 5일 예보의 경우, UI 구현부를 봤을 때 필요한 부분이 없다고 판단했습니다.

2021-01-20 15:25 UTC, iluxsm commented on WeatherForecast/WeatherForecast/CurrentWeather.swift
> +        case weather
CurrentWeather는 현재의 날씨이므로, 일정 시간마다 API로 데이터를 받아올 때마다 자동으로 갱신되지 않을까 생각했습니다.
그리고 해당 값들만 선정한 이유는 UI 구현부에서 직접적으로 사용해야할 값들만 선정했습니다.

2021-01-20 15:27 UTC, iluxsm commented on WeatherForecast/WeatherForecast/Weather.swift
> +}
해당 아이콘 코드로만 이미지를 불러올 수 있을 것 같다고 판단했었어요. 날씨 코드, 문구, 설명 부분을 나타내는 `id`, `main`, `description` 이 필요할까요?

2021-01-20 15:37 UTC, iluxsm commented
@delmaSong
델마, 질문에 대한 좋은 답변과 리뷰 정말 고마워요 🙌
커밋이 조금 꼬여서.. 보기 힘드실 수 있습니다.. 죄송해요.

우선 코멘트 남겨주신 부분에 대한 답변과 수정 내역은 아래와 같아요!

[추가 및 수정 내역]
- 파일 네이밍을 변경했고, Model 폴더로 그룹을 지어줬습니다.
- JSON 데이터에서는 온도를 절대 온도로 나타내는데, 섭씨 온도로 나타내주기 위해 연산 프로퍼티를 활용했습니다.
- JSON 데이터에서 weather가 항상 하나의 배열로 이루어져있어서 접근할 때, 첫 번째 원소로 접근할 수 있도록 연산 프로퍼티를 활용했습니다.
- 그리고 Coordinates 파일의 키코딩을 활용하여 올바르게 데이터에 접근함에도 불구하고, JSON 키와 동일한 네이밍을 쓰지 않으면 데이터를 받아오지 못하는 버그를 발견하여 프로퍼티 네이밍을 수정했습니다.

2021-01-21 23:09 UTC, delmaSong commented
버그 해결하시느라 고생 많으셨어요! 다음 단계로 넘어가봅시다 🤓

2021-01-21 23:09 UTC, delmaSong approved these changes

2021-01-21 23:09 UTC, merged