Step 1: 타입 구현 (찌로)
yagom-academy/ios-weather-forecast pull request #15
Opened 2021-01-19 12:08 UTC by zziro95

@cmindy 
안녕하세요~ 스탭1 타입 구현해봤습니다.
리뷰 부탁드려요:)

#### 구현 내용
1. 현재 날씨와 5일 예보 api의 json데이터를 받기 위한 타입 `CurrentWeather`, `FiveDayWeather` 타입을 구현하였습니다.
2. 각각의 저장 프로퍼티의 타입을 구현하다 보니 공통 타입이 있어 공통 타입은 따로 파일로 빼주었습니다.
3. 비슷한 구조이지만 프로퍼티의 구성이 약간 차이가 있는 타입은 다른 네이밍으로 만들어 주어 구분하였습니다. (`CurrentWeatherMain` - `FiveDayWeatherMain` , `CurrentWeatherSys` - `FiveDayWeatherSys`)
4. 버전 호환이 가능하도록 @available 키워드 추가
5. 임시 데이터를 asset에 추가해 테스트 시도

#### 고민 내용
1. 처음에는 `CurrentWeather`, `FiveDayWeather`의 타입에 필요한 새로운 타입을 연관성이 있기 때문에 따로 파일로 빼지 않고 구현을 했었는데, 만들고 보니 두 타입이 공통으로 사용할 수 있는 타입이 몇 개 있어서 그 타입만 따로 빼주었습니다. 저만의 기준으로 이런 식으로 구현해보았는데 민디 의견을 들어보고 싶습니다.!
2. 테스트 관련 어려움을 마주하였습니다.
- 처음에 시뮬레이터 버전을 프로젝트 타겟 버전과 같은 12.0으로 맞추고 테스트를 실행했을 때 실패해야 할 테스트임에 불구하고 성공한다고 나왔습니다.
- 이후 시뮬레이터를 12Pro로 선택해서 진행하였더니 예상한 데로 테스트가 잘 진행되었습니다.
- `testCurrentWeatherData()` 메서드까지는 예상한데로 테스트가 진행되었으나 `testFiveDayWeatherData()`에서는 다시 실패해야 할 테스트임에도 테스트가 성공했다고 나왔습니다.
- 콘솔에 뜨는 Warning 메시지와 오류 내용을 살펴보고 조사해봤는데 이유를 찾기 어려웠습니다. 관련 내용에 대해 힌트를 얻을 수 있을까 여쭤보게 됐습니다.!

행복한 하루 보내세요오~😚

2021-01-20 12:06 UTC, cmindy requested changes
고생하셨습니다 찌로! 👏 
다만 실제로 json을 넣어서 decode를 해보면 디코딩에 실패하고 있습니다. 😢 
json 값을 보면 어떤 속성은 있기도 하고 없기도 한데, 어떤 부분인지 캐치하시면 쉽게 해결하실 수 있을거예요!

> 처음에는 CurrentWeather, FiveDayWeather의 타입에 필요한 새로운 타입을 연관성이 있기 때문에 따로 파일로 빼지 않고 구현을 했었는데, 만들고 보니 두 타입이 공통으로 사용할 수 있는 타입이 몇 개 있어서 그 타입만 따로 빼주었습니다. 저만의 기준으로 이런 식으로 구현해보았는데 민디 의견을 들어보고 싶습니다.!

저는 다른 타입으로 빼주는 편이긴 해요. 어느정도 연관성이 있는 타입이면 같은 파일 안에 구현해주기도 합니다 👀 정말 그 타입안에서 사용될거라고 하면 중첩으로 선언해주는 편입니다.
저는 타입이 구분되어 있는 편이 코드를 읽을 때 편해서 이런 방법을 지향하고 있습니다 :)
앞으로 계속 모델 타입을 구현하다 보면, 찌로도 더 기준이 확실해지시겠죠 흐흐 그러면 저한테도 다시 알려주세요 📢 이런 얘기 듣는건 언제나 즐거우니까용! 

> 테스트 관련 어려움을 마주하였습니다.
처음에 시뮬레이터 버전을 프로젝트 타겟 버전과 같은 12.0으로 맞추고 테스트를 실행했을 때 실패해야 할 테스트임에 불구하고 성공한다고 나왔습니다.
이후 시뮬레이터를 12Pro로 선택해서 진행하였더니 예상한 데로 테스트가 잘 진행되었습니다.
testCurrentWeatherData() 메서드까지는 예상한데로 테스트가 진행되었으나 testFiveDayWeatherData()에서는 다시 실패해야 할 테스트임에도 테스트가 성공했다고 나왔습니다.
콘솔에 뜨는 Warning 메시지와 오류 내용을 살펴보고 조사해봤는데 이유를 찾기 어려웠습니다. 관련 내용에 대해 힌트를 얻을 수 있을까 여쭤보게 됐습니다.!

이 부분은 코드에 코멘트를 남겨놓았으니 참고해주세요!

2021-01-21 23:29 UTC, zziro95 commented
@cmindy 
고마워요 민디☺️ 어렵기만한 했던 타입설계가 민디의 의견덕분에 재미있게 느껴지네요!
다양하게 생각해볼 수 있게 해주셔서 감사해요~
리뷰해주신 내용에 대해 고민후 수정해 보았습니다
쓰다보니 긴,,글이 되었어요.. 확인해주시면 감사하겠습니다🙏

[수정 사항]
1.
`Codable`에 대해서 살펴보았습니다. 
선언부분을 보면 자주 같이 쓰이고 연관이 있는, Encodable & Decodable 프로토콜을 typealias로 설정을 해주었음을 확인할 수 있었습니다.
쉽게 이해하자면 디코딩과 인코딩을 모두 가능하도록 지원해주는 프로토콜입니다. 
이 프로젝트의 경우 JSON 데이터를 읽어오는 경우 밖에 없다고 생각하여 Codable 대신 Decodable 프로토콜을 채택하도록 수정하였습니다.

2.
`CodingKey`에 대해서도 다시 생각해보게 되었습니다.
스네이크케이스로 되어있던 부분을 통일감있게 카멜케이스로 변환해주기 위해 사용하였는데, 축약된 표현이나 타입의 프로퍼티로서 모호한 네이밍을 좀 더 명확하게 바꿔줄 수 있다는 장점이 있다는것을 파악하여 수정해 보았습니다.

[고민해본 내용]
3.
> CurrentWeatherMain - FiveDayWeatherMain 이 두가지 타입은 어떤 프로퍼티에 차이가 있어서 다르게 구성해주셨나요?

이 코멘트에 대한 대답이 될 수도 있을것 같습니다.

Main, Rain, Snow의 타입이 CurrentWeather과 FiveDayWeather 타입에 공통적으로 등장하지만 API를 통해 받게되는 JSON데이터에 전달 받는 키값의 종류(개수?)의 차이가 있었습니다.(Rain으로 예를 들자면 현재날씨는 1h,3h를 전달받고 5일일기예보는 3h만 전달받습니다.)

어떻게 효율적으로 전달받을 수 있을까 고민을 해봤는데 1. 공통된 타입을 만들되 1h과 같이 받을수도 있고 그렇지 않을지도 모르는 프로퍼티를 옵셔널 타입으로 선언하는 방법이 있었고, 2. 아예 공통된 타입을 따로 빼지않고 현재날씨, 5일일기예보 각 각의 타입안에 따로 따로 구현해주는 방법이 있었습니다.

2번의 방법을 선택하게 되었고 그에 따른 장 단점을 아래와 같다고 생각합니다.

장점
- 서버에서 뿌려주는 (현재날씨, 5일예보) JSON 데이터의 구조가 바뀔 경우 각각 독립된 타입에서 바뀐 부분만 수정해주면 된다.

단점
- 공통 되는 타입이 많을수록 중복코드가 많아진다. (실제로 적용하는 과정에서 생각보다 엄청난 양의 코드가 중복을 확인했습니다.. 장점이라고 생각했던 부분을 집어삼킬정도?! 관련된 또 다른 api의 데이터를 받아와야한다면? 코드의 중복은 더 많아질 것으로 예상됩니다. 이 구조에 대해 다시 고려해볼 필요가 있다고 생각합니다!! )
- CurrentWeather, FiveDayWeather 타입의 뎁스가 깊어지고, 가독성이 떨어진다

4.
Decodable과 CodingKey를 공부하다 보니 애플 공식문서에 init을 필수로 구현해야 한다는 것을 알게되었습니다. 그러나 프로젝트에서 JSON 데이터를 다룰때 init을 구현하지 않아도 별다른 오류가 발생하지 않아 의문이 생겨 살펴보았는데 답을 찾지 못했어요.
(이니셜라이저에 대해서 살펴봤을때 구조체의 멤버 와이즈 이니셜라이저가 실마리를 푸는 시작점이 되지않을까 했는데 거리가 멀어보이더라구요.. )
힌트를 주실 수 있을까요??🥺

5.
가능한 모든 데이터를 받고 싶은데 어떤 데이터가 필수로 들어오는지 전혀 파악할 수 없었습니다.
예시 데이터를 활용했을때 `임시적`으로 오류를 회피하고자 CurrentWeather의 rain, snow, FiveDaysWeather의 snow 프로퍼티 타입을 옵셔널타입으로 선언하였습니다. 

`keyNotFound` 문제를 해결하는 방법은 `init을 이용해 기본값을 넣어주는 방식`과 `모든 프로퍼티를 옵셔널 타입으로 설정`하는 두가지 방식이 존재하는 것 같은데 제 생각에는 `모든 프로퍼티를 옵셔널 타입으로 설정` 이 좀더 안전한 방법이지 않을까 생각이 들었습니다. 이 부분에 대한 민디의 의견은 어떤지 궁금해요!!🧐

2021-01-22 14:05 UTC, cmindy approved these changes
ㅋㅋㅋㅋㅋ 그마음.. 이해합니다 저도 쓰다보니까 자꾸 길어지더라구요ㅎㅎ; 이것도 길어졌네요ㅋㅋㅋㅋㅋ
앗.. 근데 브랜치가 `lina0322:step1-zziro` 이렇게 되어있는데 리나레포에서 브랜치를 만드셨나요? -> 이거 상관 없는 거라면 머지할게요 dm이나 답변해주세요.

3. 오 정말 잘 정리해주셨네요. 말씀해주신대로 다른 API에서 이 데이터 모델을 사용하는 경우도 있을거예요. 그렇다면 중복은 더더 많아지겠죠 ㅎㅎ.. 
저는 개인적으로 찌로에게 필수적인 데이터로만 구성을 하는 걸 추천해드리고 싶어요. 그렇게 하다 보면 중복 코드를 줄여보실 수 있을 거예요. 작은 단위로 나눠서 파일로까지 나눠지면 더더 가독성이 올라갈거예요. 저는 메인에 표시될 때 Main, Rain Snow.. 이런 것들의 키값의 차이가 크지 않다고 봐서 충분히 빼볼 수 있을 것 같습니다. (+옵셔널이나 container를 활용해볼 수도..? 🤔 )
지금도 충분히 고민을 잘해주시고 계셔서 어떤 방향으로 결정이 될지 기대가 되네유 ㅎㅎ!

4. [Swift-Evolution](https://github.com/apple/swift-evolution/blob/main/proposals/0166-swift-archival-serialization.md ) Codable이 제안된 swift-evolution의 제안서인데 이 링크가 좀 참고가 될 수 있겠네요. 👀 길긴한데.. 원하시는 답은 앞부분만 읽으셔도 충분할 것 같아요ㅎㅎ

5. **가능한 모든 데이터**.. 이부분은 UI가 정해지거나 어떤 걸 표현해볼지 생각하면 좀 더 수월할거예요.
저 같은 경우는 보통 그리는 데 필요한 데이터들만 모델링을하는 편이예요. 일단 최소로 구현을 시작해서 요구사항이 변경되는 것에 따라 모델도 변경을 해줬던 것 같네요.
작은 단위부터 시작하면 중복이 되었을 때도 재사용하기 편해서 이런식으로 진행했던 것 같아요 :) 작은 단위들로 나눠놓으면 이곳 저곳 재활용할 가능성이 더 높을 거예요.
**어떤 데이터가 필수**로 들어오는지... 이 부분은 아마 협업을 하면서 정해나갈 수도 있고, API 문서에 정의되어있을 수도 있겠죠? 하지만, 아무리 잘 정한다고 하더라도 그 데이터가 필수적이라는 건 보장을 할 수가 없어요. 필수로 들어온다고 해도 실제로는 누락이 되어서 안들어올 수도 있습니다 😹 때에 따라 다르긴 하지만.. 이런 이유로 저도 프로퍼티를 옵셔널로 설정하는 편인 것 같습니다.

2021-01-22 16:30 UTC, zziro95 commented
(늦은 시간이라 태그는 달지않을게요. 그래도 알림이 가려나..? 이거 알려주시면 좋을거 같아요!)

확인 감사합니다~! 
링크 들어가서 읽어봤더니 속이 뻥~ 해피해피하네요
브랜치는 `리나`와 서로 스탭별 코드 리뷰를 해보기 위해 콜라보레이터로 참여해서 프로젝트 진행하는 방식으로 해봤어요
가능한 모든 데이터를 받아와서 요구서의 변경에 대비를 해보려했는데 (직접 코드의 중복을 경험해 보기도 하고) 민디의 말대로 UI에 어떤게 표현되는지와, 그걸 보여주기 위해 어떤 데이터가 필요한지 고민해 최소로 구현하는게 더 효율적이라고 생각이 들어요~!
나중에 추가적으로 필요한 데이터가 생긴다면 넣어주기만 하면되니 그 방식이 더 효율적일것 같아요🤩

구조의 리팩토링과 추가로 달아주신 멘트는 스탭2 진행해보면서 적용해보겠습니다
덕분에 스탭1 (많은 고민도 해보고 어려웠?지만) 😊재미있게 진행했습니다.🙇‍♂️

머지 부탁 드립니다.

2021-01-22 16:35 UTC, cmindy reviewed
ㅎㅎ 알림은 오지만 상관없습니다!! (진짜리얼트루) 멘션해주셔도 되구욥ㅎㅎ 언제든 남겨주세용. 
머지할게요 🥳

2021-01-22 16:35 UTC, merged