Step2-fkwksi
yagom-academy/ios-weather-forecast pull request #19
Opened 2021-01-20 17:39 UTC by wonhee009

@AppleCEO 

- NetworkConfig로 url, appID, 위치 좌표로 urlString 변환을 관리
- weatherNetwork에 공통으로 사용하는 통신 코드 관리
- 사용자가 위치 정보 공유 허용 안할시 설정 창으로 이동하여 설정할 수 있도록 구현(설정창으로 넘어는 가지만 프로젝트가 test app여서 설정에서 위치 정보 공유를 바꿀 수 없더라구여...ㅎㅎ)
- 각 클래스별 책임을 나누려고 노력했습니다!ㅎㅎ

코드 리뷰 부탁드려요🙇‍♂️

2021-01-21 02:07 UTC, AppleCEO requested changes
라자냐 고생하셨습니다!
적어주신 대로 객체 간 역할이 잘 나뉘어진 느낌이었습니다.
몇가지 코멘트 남겨놨습니다.
확인해보세요~

2021-01-21 02:07 UTC, AppleCEO commented on WeatherForecast/WeatherForecast/ViewController.swift
> +extension ViewController: CLLocationManagerDelegate {
extension 을 다른 파일로 빼낸 것과 안 빼낸 것은 어떤 기준으로 나누셨나요? 🔢

2021-01-21 02:30 UTC, wonhee009 commented
@AppleCEO 

- LocalizedError에 대한 설명은 [여기](https://velog.io/@wonhee010/Enum과-Error에-대하여)에 정리해뒀습니다!
- enum WeatherAPIKey로 네이밍 변경했습니다!
- extension을 파일로 따로 뺀 경우는 범용적으로 사용할 수 있는 기능들은 파일로 따로 뺐습니다!

- WeatherModel, ForecastModel을 두어 데이터를 관리했습니다.
- 네트워킹은 제네릭을 사용해 디코딩하도록 수정했습니다.

2021-01-21 15:05 UTC, AppleCEO requested changes
라자냐 고생하셨습니다.
여러가지 신경을 많이 쓴 게 느껴지는 코드였습니다.
몇가지 의견 달아놨습니다.
화이팅입니다~

2021-01-21 15:05 UTC, AppleCEO commented on WeatherForecast/WeatherForecast/Network/NetworkConfig.swift
> +        var urlString = baseURL
기본 URL 보다 더 명확한 이름은 없을까요?

2021-01-22 01:22 UTC, wonhee009 commented
@AppleCEO 

- WeatherAPITypes로 변경했습니다! API Key는 뭔가 명확하지 않았는데 APITypes는 명확한거 같아요!
- BaseURL보다 WeatherBaseURL이 더 명확한거 같아서 변경했습니다.

- 싱글톤 패턴의 장점은 객체가 필요할 때 매번 생성하는 것이 아니라 최초 생성된 하나의 인스턴스를 사용합니다.
다른 클래스와 데이터를 공유할 수 있고요.
단점으로는 
싱글톤 패턴을 사용했을때의 장점은 다른 클래스들과 싱글톤 객체를 공유할수록 결합도가 높아집니다.
또한, 메모리를 계속 점유하고 있기도 하고요.

2021-01-22 01:24 UTC, AppleCEO approved these changes
제가 의도했던 바는 고정된 URL이라는 의미로 fixedURL 정도가 어떨까 생각했습니다.
다음 스탭을 진행하면서 참고해주세요 ㅎㅎ

2021-01-22 01:24 UTC, merged