innie step1
yagom-academy/ios-weather-forecast pull request #20
Opened 2021-01-20 18:23 UTC by innieminnie

메이슨 안녕하세요! 늦은시간죄송합니다!
 @myssun0325 

[주요내용]
- 타입은 크게 ForecastingSystem, CurrentWeatherInformation, FiveDaysForecastingInformation 으로 세가지로 분류했습니다. 프로젝트의 Model 디렉토리를 새로 생성하여 세 타입에 해당하는 파일을 담았습니다.

-  CurrentWeatherInformation, FiveDaysForecastingInformation은 JSON데이터를 외부API를 통해 받아서 연결지어지는 타입입니다. 각각의 타입의 일부를 구성하기 위해서 외부 API요청을 필요로 하는 데이터 (도시정보, 위치정보 등등) 또한 모두 타입으로 구현했으며 CurrentWeatherInformation, FiveDaysForecastingInformation 에 대해 직접적으로 연관된 타입에 따라 같은 파일 내에 담았습니다.

- 온도 섭씨 설정은 URL요청문에 unit = metric 을 추가했습니다.

-   ForecastingSystem은 원하는 기능에 따라 (현재 날씨 확인 or 5일 기상예보) makeModel 메소드 호출을 JSON데이터와 타입을 연결짓고자 했습니다.

- ForecastingSystem의 private메소드는 extension으로 분리하였습니다.

- API의 호출 과정에서 데이터 유실 가능성에 따른 에러 발생을 Result Type을 활용하여 처리하고자 했습니다. 

[etc]
- JSON데이터의 dt값은 일단 호출한 시간이 필요할 거 같긴 해서 구현한 타입의 프로퍼티에 넣었는데, 만약 이후 스텝에서 필요하다면 DateFormatter를 활용해서 현재 시간으로 바꾸는 것을 시도해볼 예정이고, 필요없으면 삭제하겠습니다!

2021-01-21 17:34 UTC, myssun0325 requested changes
👍너무 수고하셨습니다!! 처음부터 너무 완벽하지 않아도됩니다!! Result 타입을 사용하셨군요 짱짱!

- 뷰컨트롤러에서 접근하는 입장에서 봤을 때 currentWeather와 fiveDaysForecasting를 각 API에 대해서 나눠서 접근했고 그에 따른 모델링을 분류한건 굉장히 좋은 아이디어 같습니다. 
- 코드의 재사용성이나 중복에 대해서도 질문해주셨는데, 두 파일만 놓고봤을 때 currentWeather와 fiveDaysForecasting에서 양쪽 모두 사용되는 모델이 한쪽 파일에만 있는 경우도 있군요 이 경우 이 모델은 독립된 파일로 분리하는건 어떨까요? 파일안에 관련된 모델들을 모아두는것도 좋지만 Weather라든지 Temperature 같은 경우는 여기저기서 사용되기 때문에 분리를 해도 좋을거 같네요~ 클래스가 아닌 파일을 잘 나누는 것도 연습해보면 좋을거 같습니다. 

- `ForecastingSystem` 도 모델폴더에 있는데 다른모델과는 다르게 네트워킹을 하고있군요 역할을 고민해볼 수 있을거 같습니다.

- 모델링 관련해서 개인적인 의견을 물으신거에 대해선: 저 같은 경우엔 모델링은 변경에 유연하게끔 날씨앱을 구현한다고하면 어떤것들이 필요할까?라고 요구사항에 대해 먼저 생각하고 아직 어떤것들이 필요하지 모른다면 가장 최소한의 것들로만 만들어놓고 요구사항이 진행됨에 따라 추가를 하거나 변경을 할거 같네용

- URLSession을 활용한 네트워크 코드가 매우 훌륭합니다. ⭐️⭐️⭐️⭐️⭐️

- 모델타입을 정의할 때 프로퍼티를 `let`이 아닌 `var`로 선언하신 이유가 있나요~??

- 가장 아쉽고 고민하셨던 부분에 대해서 말씀드리면...
여기에 아마 또 다른 새로운 API가 추가가 되면 여러개의 중복되는 코드가 생성되겠네요 그래서 고민이실거같습니다.
중복을 제거하기 위해서 여러가지 방법을 시도해볼 수 있을거 같네요 일단 가장 간단한 방법으로 메서드를 더 작게 만들어보는건 어떨까요? 잠시 글렌이랑 얘기나눴던거처럼 모듈화, 컴포넌트화에 대해서 고민해본다면
이미 다 만들어진 덩치큰 녀석을 재사용하는것보단 작은녀석들을 재사용하는게 더 쉽겠죠?(레고 블럭2개보단 1개가 더 재사용성이 높겠죠?)
메서드를 쪼갤 때 중복된 부분을 공통적으로 묶고 다른 부분을 파라미터로 줄 수 있는 방법도 있을거 같네요.

2021-01-21 17:34 UTC, myssun0325 commented on WeatherForecast/WeatherForecast/Model/ForecastingSystem.swift
> +        let dataTask = urlSession.dataTask(with: requestURL) { (data, response, error) in
위에서 urlSession을 변수에 사용하지않고 (재사용되지 않고, singleton 객체는 어디서든 접근이 가능한게 장점이기도 하죠?!) 요기에 `URLSession.shared.dataTask...`으로 사용해도 괜찮겠네요.

2021-01-21 17:34 UTC, myssun0325 commented on WeatherForecast/WeatherForecast/Model/FiveDaysForecastingInformation.swift
> +struct City: Decodable {
디코딩만 필요하기 때문에 필요한 Decodable만을 채택해서 모델링했군요 굉장히 잘하셨습니다!

이번 단계에서 굉장히 중요한 부분이기 때문에 이미 잘알고 있겠지만 한번더 상기하고 넘어가면 좋을거 같아용!

Codable과 CodingKey는 각 프로토콜은 무엇이고, 언제사용하는 것일까요? 간단히 설명해주세요!

2021-01-21 17:34 UTC, myssun0325 commented on WeatherForecast/WeatherForecast/Model/ForecastingSystem.swift
> +        guard let requestCall = makeRequestCall(for: feature) else {
requestCall은 중첩적인 네이밍같아요 request만으로 충분할 수 있겠군요~ 하지만 여기서 requestCall이 request가 아닌 URL타입이네용

2021-01-21 18:03 UTC, myssun0325 commented
(Option) make로 만든 메서드를 만드셔서 그 고민에 대한건 팩토리 메서드나 팩토리 패턴에 대해서 한 번 궁금할 때 찾아보시면 도움이 될거에요.
아래는 Swift API Guidelines에 나온건데요 (우와 네이밍말고 이런것도 있습니다 ㅋㅋ) 잠깐 훔쳐보자면

쉽게 생각해서 아이스크림 공장이 있는데 공장에 `딸기를 가져다주면` 딸기 아이스크림을 생성해서 나한테주고, `초콜릿을 공장에 갔다주면` 초콜릿 아이스크림을 `다시 나한테 준다고 생각`할 수 있어요.

<img width="793" alt="image" src="https://user-images.githubusercontent.com/26790375/105391897-ee9e5580-5c5d-11eb-8c5f-1af70dafccab.png">

2021-01-23 19:09 UTC, innieminnie commented on WeatherForecast/WeatherForecast/Model/ForecastingSystem.swift
> +            print("URL 생성 실패")
throw(), assert(), precondition(), preconditionFailure(), fatalError() 가 대표적으로 있습니다.

throw() - do try catch 문을 활용하여 에러발생가능한 부분에 에러처리에 관해 작성해줍니다.
assert() - 어떠한 조건에 대한 참/거짓 판별로 활용합니다.
precondition(), preconditionFailure() - assert와 유사하지만 debug에서만 검증되는 assert와 달리 debug, release 빌드에서 전부 검증된다는 차이가 있습니다.
fatalError() - 해당 부분에 접근하면 프로세스가 즉시 종료됩니다.

코드 리팩토링 과정에서 URL을 만드는 작업은 이후 단계로 진행하기 이전에 미리 전처리 되어야하는 작업이라 생각되어 preconditionFailure()을 활용해보았습니다.

2021-01-23 19:09 UTC, innieminnie commented on WeatherForecast/WeatherForecast/Model/FiveDaysForecastingInformation.swift
> +struct City: Decodable {
Codable은 Decodable & Encodable의 기능을 합친 프로토콜로 외부작업물을 가져와 디코딩시키거나, 내부작업물을 외부작업물과 원활하게 교류하도록 인코딩 시키는 작업을 쉽게 가능하게  합니다.

CodingKey는 Codable을 통해 가능해진 encoding, decoding 과정에서 key값을 맞춰주는 과정을 작성하기 위해 요구되는 프로토콜입니다.

2021-01-23 19:09 UTC, innieminnie commented
@myssun0325 
메이슨 안녕하십니까 step1 개선해보았습니다~!

우선 제가 고민하던 부분을 중점으로 리뷰해주신점, 고민점에 맞게 방향 제시해주신 점, 세세하게 리뷰 이곳저곳 신경써서 남겨주신게 느껴져서 감사합니다. 다 읽어보고 폭풍감동받고갑니다 ㅠㅠㅠㅠㅠㅠㅠㅠ.

[주요 수정 및 생각과정 정리]
- 모델타입에 제가 프로퍼티를 전부 var로 했었는데 무의식적으로.. 작성한 부분이였어서 let으로 교체했습니다! 

- 기존에 코드 내용이 거의 유사하던 matchDataWithCurrentWeather와 matchDataWithForecastingFiveDays 메소드를 fetchResource,  라는 메소드를 통해 타입에 상관없이 접근하여 원하는 데이터를 네트워크를 통해 받을 수 있도록 했습니다. 

- 공통으로 사용가능한 fetchResource를 호출하는 메소드를 두 개로 분리해서 announceCurrentWeather와 announceFiveDaysForecasting으로 방향을 바꿨습니다. 이전에는 makeModel이라는 메서드에서 파라미터를 달리하여(오늘날씨정보 / 5일예보) 호출했다면, 아예 메소드 두개로 만들어서 두 메소드의 마지막 부분에 공통적으로 fetchResource를 호출하는 것이 더 적합해보였습니다. 대신 URL 생성부분을 각각 요구하는 기능에 맞게 다르게 생성하는 작업을 앞에서 진행한뒤, 생성된 URL을 활용하여 fetchResource를 호출합니다.

- 결과적으로 기존의 makeModel에서 url생성 및 확인, 네트워킹을 통한 데이터와 모델 패칭작업을 전부 해주던 것에서 announceCurrentWeather와 announceFiveDaysForecasting 메소드 분리시키게 되었습니다.

- 먼저 기존코드를 1차적으로 수정하여 저렇게 분리해놓고보니, ForecastingSystem 자체에 메소드가 너무 많다고 생각되어 URLMaker타입생성을 통해 아예 URL만드는 작업을 따로 해주는 개체를 만들었습니다. 

- 위에 말씀드린 리팩토링 과정을 구현하는 데 있어 Result Type을 좀 더 활용해보는 기회가 되었습니다!

- 이전 리뷰 곳곳에서 메소드를 쪼개보아라고 하신 것에 대해 신경을 썼습니다 !

2021-01-24 06:53 UTC, myssun0325 approved these changes
- URLSession 메서드를 잘 분리하여 이전에 하던 이니의 고민이(중복, API가 늘어날때마다 dataTask를 계속 계속 만들어야했던...) 해결되었군요!! 😌 편안하겠군요.!  굉장히 잘 분리하셨습니다!! 분리가 깔끔하군요
- 모델의 분리도 굉장히 잘하셨습니다!
- "URL 생성 error" 라든지 with: "forecast" 등과 같이 문자열이 하드코딩되어있는 경우가 있는데요. 이런경우 어떤 장단점이 있을까요? 이니의 의견이 궁금합니다. (요건 다음 단계 PR에 올려주시거나 다음단계 진행하면서 답변주세용)
네이밍이나 오타관련해서는 다음 '커밋'에서 고민해보면 되겠군요 ~ 다음 단계에서 만나요 👋

2021-01-24 06:53 UTC, myssun0325 commented on WeatherForecast/WeatherForecast/URLMaker.swift
> +struct URLMaker {
만약에 URLMaker가 아래와 같이 날씨와 같은 특정 URL을 만들어주는거라면 `URLMaker` 보다는 어떤 URLMaker인지가 명확하면 더 좋겠네용

2021-01-24 06:53 UTC, myssun0325 commented on WeatherForecast/WeatherForecast/URLMaker.swift
> +        if let validateURL =  URL(string:"\(baseURL)/\(keyword)?lat=\(geographicCoordinate.latitude)&lon=\(geographicCoordinate.longitude)&units=\(temperatureUnit)&appid=\(myKey)") {
URL(string: 앞에 띄어쓰기 오타!

2021-01-24 06:53 UTC, myssun0325 commented on WeatherForecast/WeatherForecast/ForecastingSystem.swift
> +            preconditionFailure("URL 생성 error")
고민해본 포인트가 좋습니당~

2021-01-24 06:53 UTC, myssun0325 commented on WeatherForecast/WeatherForecast/ForecastingSystem.swift
> +    public func announceFiveDaysForecasting(result: @escaping (Result<FiveDaysForecastingInformation,NetworkError>) -> Void) {
뷰컨트롤러입장에서 ForecastingSystem에 announce해줘!라고 했을 때 announce라는 동사가 이 메서드의 역할을 잘 표현해줄지 네이밍을 고민해보아도 좋을거 같아요~

2021-01-24 06:59 UTC, myssun0325 commented on WeatherForecast/WeatherForecast/Model/ForecastingSystem.swift
> +            print("URL 생성 실패")
Wow.!

2021-01-24 07:02 UTC, merged