날씨 정보 [Step1] - 잼킹, 호싱잉
yagom-academy/ios-weather-forecast pull request #33
Opened 2021-09-28 17:18 UTC by jaemuYeo

@wonhee009 

안녕하세요 라자냐!! 반갑습니다 ☀️😀
리뷰 잘 부탁드립니다! 부족한 부분이 많을 것 같아요 😂

## 고민한 부분 / 조언받고 싶은 부분
- 모델 구현시 어떤 프로퍼티가 사용될지 구분이 쉽지 않을 정도로 많은 프로퍼티가 API문서에 있었는데, UI가 기능 상세에 나와있지 않고해서 일단은 response에 나와있는 모든 프로퍼티를 작성해봤습니다.
- 모델 구현시 프로퍼티 타입에 필요한 여러 타입들이 두 모델에서 비슷한 이름으로 되어있지만
내부 프로퍼티는 몇 가지가 다르게 되어있어 중첩타입으로 구현하였는데 적절하게 구현한건지 의문입니다,,
- 디코딩 에러와 API에러 처리 관련해서 print(error.localizedDescription)을 지양해야한다고해서,
DebugPrint()와 Error타입을 채택한 열거형을 통해서 에러처리를 해줘볼까하다가 
LocalizedError를 채택한 열거형으로 만들어서 처리해줘봤는데요.
적절한 처리였는지 궁금하고, 실무에서는 어떤 방식으로 처리하시는지 궁금합니다!!
- fetchCurrentWeather(completion:)메서드와 fetchFiveDaysWeather(completion:)메서드는
escaping클로저를 뺄까 넣을까 하다가 동시성과 관련된 처리를 해주게 될 경우가 필요한 것 같아서
(활동학습에 해당 내용이 들어있어서..) escaping클로저를 파라미터로 받는 함수로 만들어줘 봤습니다.

위도와 경도에 대한 부분은 다음 스텝이여서 임의로 위치를 정해놓았습니다!

2021-09-29 08:54 UTC, wonhee009 requested changes
잼킹, 호싱잉 스텝1 수고하셨습니다!🎉
리뷰 및 코멘트 남겨놨으니 확인 부탁드립니다🙏

1. response의 모든 데이터를 구현한 점은 현재 UI가 나와있지 않으므로 괜찮다고 생각됩니다. 이후 UI 상세가 나온다면 사용하지 않는 데이터들은 정리해도 좋을거 같습니다.
2. 중첩타입으로 구현한 점도 좋습니다.
3. > print(error.localizedDescription)을 지양
에 대해서는 제가 전체적인 문맥은 모르지만 `print()`로 에러를 출력하는걸 지양하자는거 같은데요.
제가 이해한게 맞을까요?
4. > 동시성과 관련된 처리를 해주게 될 경우가 필요한 것 같아서
어떤 경우가 있을까요?

- `currentWeather`과 `FiveDaysWeather` 데이터를 정의할때 API에서 내려주고 있는 `coord`, `main`과 같은 네이밍을 그대로 사용하고 있네요. Swift에서는 약어는 지양하는걸 권장하고 있습니다. 또한 이런 이름만 보고도 어떤 프로퍼티인지 알 수 있어야 전반적인 코드 이해도가 올라간다고 생각하는데 어떠신가요?
- `currentWeather`과 `FiveDaysWeather`이 Codable을 채택하고 있는데요. Codable을 채택하신 이유가 있을까요? [Codable 공식문서](https://developer.apple.com/documentation/swift/codable)를 확인해보면 Codable이 `typealias Codable = Decodable & Encodable` <- 이렇게 구성되어 있는걸 확인할 수 있는데요. `Decodable`과 `Encodable`은 무엇일까요?

2021-09-29 08:54 UTC, wonhee009 commented on WeatherForecast/WeatherForecast/Data/WeatherDataManger.swift
> +        }
APIError로 타입 캐스팅되지 않는 경우에는 어떻게 되나요?

2021-09-29 08:54 UTC, wonhee009 commented on WeatherForecast/WeatherForecast/Data/WeatherDataManger.swift
> +            }
`_` 와일드카드를 사용하셨네요! error가 있다면 failure 처리하기 위해 사용한거로 보이는데요.
`if error != nil { }`은 어떤가요?
사용하지 않는 프로퍼티를 굳이 만들어야하나 생각이 들어서요.

2021-09-29 08:54 UTC, wonhee009 commented on WeatherForecast/WeatherForecast/Protocol/JSONDecodable.swift
> +protocol JSONDecodable {}
```swift
protocol JSONDecodable {
     func decodeJSON()
}
```
으로 정의하고 아래에서 extension으로 기본 구현을 정의해줘도 동일하게 작동할거 같습니다.

2021-09-30 12:28 UTC, jaemuYeo commented
### Codable을 선택한 이유
타입알리어스를 통해 Decodable과 Encodable을 담고 있다는 것은 숙지했습니다!
다만 Decodable과 Codable의 성능차이가 큰 차이가 없다고 생각하여
좀 더 범용적으로 사용가능한 Codable을 채택하게 되었습니다 😀
이 부분에 대해 라자냐의 의견도 궁금합니다!!

2021-09-30 12:32 UTC, Hosinging commented on WeatherForecast/WeatherForecast/Data/CurrentWeather.swift
> +    let coord: Coord
UI가 없는 상황에서 api의 모든 프로퍼티를 만들어둔 상황이라서 UI가 나오고 어떤게 사용하고, 사용하지 않는지가 확인이 되면 그때 해당 네이밍들의 약어를 풀면어떨까 생각을 했었습니다.
먼저 말씀주셔서 FiveDaysWeather와 currentWeather모델에 Main과 Coord타입과 프로퍼티명을 약어가 아닌 아래와 같이 적절한 네이밍으로 수정해줬습니다.

main -> mainInfo
coord -> coordinate

2021-09-30 12:52 UTC, jaemuYeo commented on WeatherForecast/WeatherForecast/Protocol/JSONDecodable.swift
> +protocol JSONDecodable {}
정의하고 기본 구현한 것과 extension을 통해 바로 구현한 것과의 차이가 있을까요??

2021-10-01 01:27 UTC, wonhee009 commented on WeatherForecast/WeatherForecast/Protocol/JSONDecodable.swift
> +protocol JSONDecodable {}
정의하고 기본 구현을 한다면 프로토콜만 보고도 어떤 메서드를 가지고 있는지 알 수 있지 않을까요?
정의하지 않고 기본 구현을 한다면 잼킹이나 호싱잉이 아닌 다른 개발자가 봤을때 해당 프로토콜이 어떤 기본 정의를 가지고 있는지 파악하는데 시간이 걸릴 것 같습니다!

2021-10-01 01:29 UTC, wonhee009 commented
> ### Codable을 선택한 이유
> 타입알리어스를 통해 Decodable과 Encodable을 담고 있다는 것은 숙지했습니다! 다만 Decodable과 Codable의 성능차이가 큰 차이가 없다고 생각하여 좀 더 범용적으로 사용가능한 Codable을 채택하게 되었습니다 😀 이 부분에 대해 라자냐의 의견도 궁금합니다!!

해당 프로젝트에서는 Encodable을 사용할 일이 없을텐데 정의해서 여쭤봤습니다!
다른 개발자가 해당 코드를 본다면 struct/class가 Codable을 채택함으로써 Encodable에 열려있다고 유추할 수 있고 이런 부분들이 개발하는데 에러를 발생 시킬 수 있다고 생각합니다.
따라서 저는 최소한의 변경 가능성에만 코드를 열어두고 점차 기능이 추가되면서 필요한 부분을 추가적으로 코드를 열어두는 방식을 많이 사용합니다.

2021-10-01 01:36 UTC, wonhee009 requested changes

2021-10-01 01:36 UTC, wonhee009 commented on WeatherForecast/WeatherForecast/Data/CurrentWeather.swift
> +    let sys: Sys
이런 부분의 네이밍도 개선되어야 할 것 같습니다😃

2021-10-01 01:36 UTC, wonhee009 commented on WeatherForecast/WeatherForecast/Data/WeatherDataManger.swift
> +                completion(.failure(.emptyData))
디코딩에 실패했을시 호출될거 같은데요.
```swift
 guard let data = data else {
                 completion(.failure(APIError.emptyData))
                 return
             }
```
이미 위에서 빈 데이터인지 검증해주고 있기 때문에 데이터가 빈 상황은 아니고 디코딩에만 실패한거기 때문에 새로운 에러 타입이 필요한지 않을까요?

2021-10-01 07:29 UTC, Hosinging commented
WeatherDataManager의 fetchCurrentWeather()와 fetchFiveDaysWeather()함수에서 에러 처리 해주는 부분을 Result타입 사용시 에러 타입이 해당 타입으로 넘어오는 부분을 착각해서 다시 타입캐스팅을 해주고, 타입캐스팅이 안되면...이라는 분기문을 사용했었습니다.

Result타입에 대해서 확인해보고 다시 수정을 해보는 과정에서 에러 처리를 유저에게는 UI적으로(예: Alert)보여주고, 개발자인 저희는 print, debugPrint, fatalError, assertionFailure, assertion등의 함수로 처리 할 수 있을 것으로 확인해봤는데요. 

1. alert와 같이 유저에게 보여줄 수 있는 장치가 마련되지 않았을 때는 앱이 종료되는 것을 피하면서 에러 처리를 해주는 방법이 print, debugPrint와 같은 출력문을 통해 처리해주는 방법 외에  어떤게 있을지 궁금합니다.

2. 유저에게 보여주는 alert와 같은 장치가 마련되지 않았을 때는 assertion, , assertionFailure, fatalError와 같이 크래시를 발생시키고, 어느 파일, 어느 라인에서, 어떤 메시지로 에러가 발생되는가를 가능하게 하는 것도 개발자가 확인하기 위한 용도로 사용하면 좀 더 빠른 처리가 가능하지 않을까 생각, 고민을 해봤습니다. 이런 메서드는 지양하는게 좋을지 궁금합니다.

라자냐는
1. 네트워킹+디코딩 하는 코드에서 Result타입을 사용했을 경우, failure에 담겨 넘어오는 에러를 switch문에서 어떤 식으로 처리해주는지 궁금합니다. (예제 코드를 덧붙여 주시면 감사하겠습니다)

2. 네트워킹+디코딩 하는 코드에서 throwing function을 사용했을 경우, throwing된 에러를 어떤식으로 처리해주는지 궁금합니다. (예제 코드를 덧붙여 주시면 감사하겠습니다)

2021-10-01 07:39 UTC, jaemuYeo commented on WeatherForecast/WeatherForecast/Data/WeatherDataManger.swift
> +                completion(.failure(.emptyData))
라자냐 말씀대로 디코딩 실패에 대한 에러이기 때문에 APIError에 케이스를 추가하여 보았습니다!
또 다르게 생각했던 방법으로는 리뷰에 말씀해주신 것 처럼 `새로운 에러 타입이 필요하지 않을까`에 대한 고민으로
JSONDecodable 파일에서 ParsingError 타입에 있는 `decodingError`
케이스를 가져다가 사용해야 될까 생각도 해보았습니다.
그렇게 되면 Result타입의 에러 부분이 APIError 타입이 아닌 Error 타입으로 들어와야해서 일단은 전자로 진행하였는데
어떤 방법이 옳은 방법일까요??

2021-10-02 10:10 UTC, wonhee009 approved these changes
1. alert와 같이 유저에게 보여줄 수 있는 장치가 마련되지 않았을 때는 앱이 종료되는 것을 피하면서 에러 처리를 해주는 방법이 print, debugPrint와 같은 출력문을 통해 처리해주는 방법 외에 어떤게 있을지 궁금합니다.

`print()`를 통해서 에러를 출력하는걸 지양해야한다고 말한거는 출력문도 비용이 발생하기 때문입니다.
따라서 꼭 필요한 경우에 사용하는게 좋다고 생각합니다.

2. 유저에게 보여주는 alert와 같은 장치가 마련되지 않았을 때는 assertion, , assertionFailure, fatalError와 같이 크래시를 발생시키고, 어느 파일, 어느 라인에서, 어떤 메시지로 에러가 발생되는가를 가능하게 하는 것도 개발자가 확인하기 위한 용도로 사용하면 좀 더 빠른 처리가 가능하지 않을까 생각, 고민을 해봤습니다. 이런 메서드는 지양하는게 좋을지 궁금합니다.

크래시를 발생시켜 어느 곳에서 에러가 발생하는지 아는 것도 하나의 방법일 수 있다고 생각합니다.
하지만 그런 크래시가 사용자가 사용하는 중에 발생한다면 크리티컬하지 않을까요?

- 네트워킹+디코딩

"에러를 switch문에서 어떤 식으로 처리"하는지에 대해서 잘 이해 못했습니다.
저는 보통 failure에 담겨오거나 throw된 에러는  에러를 처리해주는 메서드로 넘겨서 처리합니다.
해당 메서드에서 switch문으로 처리하고요.

2021-10-04 09:51 UTC, wonhee009 approved these changes

2021-10-04 09:52 UTC, merged