Step 1 : 타입 구현 (태태)
yagom-academy/ios-weather-forecast pull request #4
Opened 2021-01-18 12:52 UTC by uuu1101

@O-O-wl 붱이🦉 오랜만이에요 ! 🙌 
리뷰 부탁드립니다 !

- JSON에서 화면에 필요한 정보만 struct로 정의
- Temperature : 현재온도, 최저, 최고 기온을 가지고 있는 타입
- Weather : 날씨 아이콘을 가지고 있는 타입 
- ForecastFiveDays : 5일 기상예보에 필요한 Timestamp의 개수, 날짜 및 시간, 날씨아이콘, 온도를 가지고 있는 타입
- CurrentTemperature : 현재 날씨 정보를 나타내는데 필요한 도시, 날씨아이콘, 온도를 가지고 있는 타입 

- AppDelegate, SceneDelegate : iOS 버전에 맞게 어노테이션 추가 (13.0 이하 버전도 지원)

2021-01-18 19:23 UTC, O-O-wl requested changes
태태 고생하셨습니다
JSON decode가 실제로는 실패하고있습니다. 
수정해서 Commit 부탁드리겠습니다.
연습하는 단계이니 좀 더 많은 값들을 담아내는 연습을 해보시는 걸 추천드리고 싶습니다.
이후 단계에서 사용되지 않는 프로퍼티는 삭제하는 걸로 할까요 ㅎ ㅡㅎ🧼 
프로젝트를 여니 모델에 해당하는 파일들이 보이지 않습니다.
`project.pbxproj`가 어떤 역할을 하는 지 확인해보면 좋을 것 같습니다.

2021-01-18 19:23 UTC, O-O-wl commented on WeatherForecast/WeatherForecast/CurrentWeather.swift
> +        case weather = "weather"
JSON의 필드와 Model의 프로퍼티명이 동일한 경우에는 생략할 수 있답니다
생략은 의도를 표현할 수 있을 것 같아요

2021-01-18 19:23 UTC, O-O-wl commented on WeatherForecast/WeatherForecast/Temperature.swift
> +struct Temperature: Codable {
Codable은 어떤 프로토콜인가요?
Encodable / Decodable에 대해서도 공부해보셨을까요?

2021-01-18 19:23 UTC, O-O-wl commented on WeatherForecast/WeatherForecast/ForecastFiveDays.swift
> +    let temperature: Temperature
실제로 JSON decode를 해서 필드의 뎁스랑 타입들을 확인해보셔야할 것 같습니다. 💥

2021-01-19 06:05 UTC, uuu1101 commented
@O-O-wl  꼼꼼한 리뷰 너무 감사합니다! 😄
악.. JSON 예시를 보고도 작성하였는데 Key값을 제대로 작성을 못했네요.(?) 
리뷰를 받고 너무 민망해서 어쩔줄 몰랐어요..
필드의 뎁스랑 타입을 다시 확인하고 수정하였습니다.

1.혹시 실제로 모델이 decode되는 건 확인해보셨을까요?
key값이 불일치하는 것 같아요.

> temp_min 이라고 보고,읽고 min_temp라고 작성을 하였네요. 💦💦💦 

2. JSON의 필드와 Model의 프로퍼티명이 동일한 경우에는 생략할 수 있답니다.
생략은 의도를 표현할 수 있을 것 같아요.

> 생략해보았습니다 . 

3. Codable은 어떤 프로토콜인가요?
Encodable / Decodable에 대해서도 공부해보셨을까요?

> 네, 먼저 Codable의 정의는 
  >-  _"A type that can covert itself into and out of an external representation"_
으로 자신을 변환하거나 외부표현으로 변환할수 있는 타입입니다.
 Codable의 typeAlias 보면 Decodable & Encodable 로 두 프로토콜을 준수하는 타입이라고 이해해보았습니다. 
>- Decodable : 외부표현에서 디코딩 할 수 있는 타입
>- Encodable : 외부표현으로 인코딩 할 수 있는 타입
이고 여기서 외부표현은 JSON 이라고 이해하였습니다.

4. 실제로 JSON decode를 해서 필드의 뎁스랑 타입들을 확인해보셔야할 것 같습니다. 💥

>  API의 JSON 예시를 볼 때 [ ] 를 제대로 확인을 못하였네요.😭
 ViewController에 관련 메서드를 작성하여 직접 decode 하여 확인해보았습니다.

2021-01-19 07:25 UTC, O-O-wl commented
> @O-O-wl 꼼꼼한 리뷰 너무 감사합니다! 😄
> 악.. JSON 예시를 보고도 작성하였는데 Key값을 제대로 작성을 못했네요.(?)
> 리뷰를 받고 너무 민망해서 어쩔줄 몰랐어요..
> 필드의 뎁스랑 타입을 다시 확인하고 수정하였습니다.
> 
> 1.혹시 실제로 모델이 decode되는 건 확인해보셨을까요?
> key값이 불일치하는 것 같아요.
> 
> > temp_min 이라고 보고,읽고 min_temp라고 작성을 하였네요. 💦💦💦
> 
> 1. JSON의 필드와 Model의 프로퍼티명이 동일한 경우에는 생략할 수 있답니다.
>    생략은 의도를 표현할 수 있을 것 같아요.
> 
> > 생략해보았습니다 .
> 
> 1. Codable은 어떤 프로토콜인가요?
>    Encodable / Decodable에 대해서도 공부해보셨을까요?
> 
> > 네, 먼저 Codable의 정의는
> > 
> > * _"A type that can covert itself into and out of an external representation"_
> >   으로 자신을 변환하거나 외부표현으로 변환할수 있는 타입입니다.
> >   Codable의 typeAlias 보면 Decodable & Encodable 로 두 프로토콜을 준수하는 타입이라고 이해해보았습니다.
> > * Decodable : 외부표현에서 디코딩 할 수 있는 타입
> > * Encodable : 외부표현으로 인코딩 할 수 있는 타입
> >   이고 여기서 외부표현은 JSON 이라고 이해하였습니다.
> 
> 1. 실제로 JSON decode를 해서 필드의 뎁스랑 타입들을 확인해보셔야할 것 같습니다. 💥
> 
> > API의 JSON 예시를 볼 때 [ ] 를 제대로 확인을 못하였네요.😭
> > ViewController에 관련 메서드를 작성하여 직접 decode 하여 확인해보았습니다.

혹시 Decodable이 아닌 Codable을 구현하신건 
Encode를 하는 경우가 있는 걸까요 해당 스탭에서는 Decode만 이뤄지는 것 같아요

2021-01-19 10:55 UTC, uuu1101 commented
@O-O-wl  안그래도 코드를 다시 보다가 그 부분을 방금 수정했는데 PR이 와있었네요 ! 감사합니다.

2021-01-19 13:59 UTC, O-O-wl approved these changes
고생하셨어요 태태 
머지할게요
다음 스탭 진행하면서 아래 코멘트도 한번 확인해주세요 🙇‍♂️

2021-01-19 14:16 UTC, merged