Step1 타입 구현 sodae
yagom-academy/ios-weather-forecast pull request #5
Opened 2021-01-18 13:01 UTC by zdodev

@Limwin94 리뷰 부탁드립니다!

- 현재 날씨 정보를 저장하기 위한 타입을 정의하였습니다.
- 현재 날씨 정보 타입을 재사용하여 앞으로 5일 예보에 대한 타입을 정의하였습니다.
- 날씨 부가정보 타입을 정의해보았습니다.

2021-01-19 13:26 UTC, Limwin94 requested changes
고생하셨습니다! 
모델에 해당하는 타입들을 잘 나눠서 하나의 폴더에 잘 정리해두셨더라고요 👍🏻 

현재 날씨에 해당되는 타입은 정상적으로 가지고 오나, 5일 예보에 해당하는 타입에서 json 디코딩이 실패하고 있습니다. 
그리고 현재는 사용하지 않을 것 같은 값이더라도 다른 리뷰어분들의 의견과 같이 내려주는 값을 최대한 많이 받아와 봤으면 합니다. :)

나머지 확인해볼 사항들은 코멘트로 남겨놓았습니다.
화이팅입니다. 🤓

2021-01-19 13:26 UTC, Limwin94 commented on WeatherForecast/WeatherForecast/WeatherJSONType/ForecastWeather.swift
> +struct ForecastWeather: Codable {
여기서는 json 디코딩이 제대로 이루어지지 않고 있어요 한번 확인 부탁드릴게요 :)

2021-01-19 13:26 UTC, Limwin94 commented on WeatherForecast/WeatherForecast/WeatherJSONType/Sys.swift
> +    let sunset: Int?
옵셔널을 쓰신 이유가 있을까요?

2021-01-19 15:38 UTC, zdodev commented
@Limwin94 리뷰해주셔서 감사합니다~

추가적인 코멘트에 대해서 생각해보았습니다.

- dt와 sys란 약어는 어떤식으로 표현이 가능할까요? 스위프트에서는 약어의 사용을 어떤식으로 권장하고 있을까요?

dt와 sys라는 약어를 json 변수만 보고 그냥 지나쳤습니다. 스위프트에서는 축약어를 쓰지 않고 풀어서 써야한다고 권장하고 있습니다. 그래서 dt는 dateTime, sys는 지역정보를 담고 있어서 local 이라는 변수명으로 수정해보았습니다.

- 옵셔널을 쓰신 이유가 있을까요?

현재 날씨와 5일 예상 날씨의 json 변수들이 비슷한 것을 보았습니다. 그래서 현재 날씨와 5일 예상 날씨의 모델을 나누지 않고 재사용 하도록 정의해보았습니다. 해당 부분은 5일 예상 날씨에서는 전달되지 않는 값이라 옵셔널로 선언했습니다. 마찬가지로 현재 날씨에서는 "pod" 라는 값이 전달되지 않기 때문에 "pod"의 값도 옵셔널로 선언, 추가해보았습니다.

추가적으로 5일 예상 날씨 디코딩 부분을 수정하고 전달해주는 값에 대한 변수들을 추가해보았습니다. 전달해주는 값중에 API Doc 표기에서 internal parameter와 예시에서 데이터 타입이 존재하지 않은 부분(값을 전달받을 때 어떠한 값이 전달되는지 잘 모르겠습니다..")은 제외했습니다.

수정사항에 대해서 리뷰 부탁드리겠습니다!!🙇

2021-01-20 10:31 UTC, Limwin94 approved these changes
고생하셨습니다. 

두개의 타입 모두 json 디코딩이 잘됩니다 👍🏻 
축약어 또한 잘 풀어서 의미를 명확하게 나타내신것 같아요.
현재 날씨와 5일 예상 날씨의 모델을 나누지 않고 재사용 하도록 하신건 좋은 의견이라 생각해요. :)

이후 하나의 모델을 가지고 접근할때 현재/5일 예상 날씨에서 사용하지 않는 프로퍼티에 대해서 방어코드만 잘 작성해주시면 될 것 같습니다.
추가로 Codable을 Decodable로만 써도 될지 고민해주시면 좋겠어요 🤓

다음 스텝에서 뵐게요!

2021-01-20 10:32 UTC, merged