날씨 정보(전) [Step2] Luyan
yagom-academy/ios-weather-forecast pull request #53
Opened 2021-10-13 17:11 UTC by KimWanki

비비(vivi) @YebinKim 
안녕하세요!

늦은 시간 PR 죄송합니다.ㅎㅎ

#### 구현 사항 관련 내용

1. 특정 지역 또는 사용자의 위도, 경도를 바탕으로 날씨를 받아오기 때문에 정확한 위치 정보가 요구되지 않는다고 판단해 location manager의 desiredAccuracy를 수정하였습니다.

2. step2에서 위도, 경도를 기반으로 날씨 정보를 가져와야 하는데, 여기서 requestLocation()을 사용했습니다. 
날씨 조회의 경우, 사용자의 위치가 갑작스럽게 변경되는 경우는 없을 거라는 생각으로 requestLocation()이 직접 호출되는 시점으로 제한하였습니다.
```swift
requestLocation

Request a single location update.

The location update will be delivered via the standard delegate callback,
 i.e. locationManager:didUpdateLocations:
``` 
추후 특정 지역의 위도, 경도를 바탕으로 날씨를 받아올 경우, 해당 메서드를 직접 호출을 하는 방향으로 구현하고자 했습니다.

3. step2에서의 위치 정보를 출력하기 위해 print() 메서드를 사용해서 임시로 구현해두었습니다.

---
부족한 부분들이 정말 많을텐데, 리뷰 잘 부탁드립니다(콕콕 찔러주세요 🪡) ; )

2021-10-14 17:33 UTC, YebinKim requested changes
루얀 안녕하세요~
날씨정보 프로젝트(후)의 리뷰를 맡은 비비입니다 😄
날씨정보 프로젝트(전) Step2 작성 고생 많으셨어요! 😆👏
따로 질문은 없어서 라인별 코멘트 및 그 외 궁금한 점 위주로 코멘트를 드려볼게요~

---

#### 1. 커밋 메세지를 중간부터 영문만 쓰도록 변경하신 거 같은데 이유가 있을까요??


#### 2. 11cd9ba 커밋과 c6938b0 커밋처럼 유사한 내용의 커밋은  **squash 또는 fixup rebase 를 통해 커밋을 병합**시켜줄 수 있어요~!


#### 3. 4a669d5 커밋은 어떤 작업을 수행한 것인지 이해가 잘 되지 않아요 🤔


#### 4. ece7fe4 커밋의 side effects를 지웠다는 것은 APIEndPoint.swift 파일의 누락으로 빌드가 되지 않는 것을 수정했다는 뜻으로 보이는데요 🤔 이 경우에는 *fixed build error* 와 같이 작업의 내용을 더 파악할 수 있는 코멘트를 작성하는 것이 좋을 거 같아요~


#### 5. 0a6ee06 커밋의 영향으로 4a669d5, b3e2e75 커밋에서는 프로젝트 빌드가 수행되지 않는데요 😵 함께 협업할 때는 빌드가 되지 않는 커밋을 올렸을 때 다른 작업자에게 영향을 줄 수 있기 때문에 지양하는 편이 좋을 거 같아요~


#### 6. 프로젝트 폴더의 레퍼런스 참조가 누락된 부분이 있어보여요! 확인 부탁드립니다 ☺️

<img width="256" alt="Project Util" src="https://user-images.githubusercontent.com/38066039/137367463-a81697ec-8950-4ea0-93bf-46fe0c07b48d.png">


#### 7. `.xcworkspace` 프로젝트 워크스페이스 파일은 깃헙 레포에 필수로 올릴 필요가 없는 파일이자 `pod install` 액션이 없을 경우 실행이 불가능한 파일이기 때문에 `.gitignore` 파일을 사용해 레포에 올리지 않도록 설정해보면 어떨까요?


---

이번 스텝에서의 핵심 경험 4가지는 적절히 수행되었다고 생각하는데요!
특히 네트워크 모델을 제네릭으로 작성하고 `HTTPMethod` 를 통해 네트워크 메서드의 사용성을 높힌 것은 멋진 활용이었습니다 😆

<img width="471" alt="Step2" src="https://user-images.githubusercontent.com/38066039/137367593-420a97f4-ec7e-4186-8f08-181bf0717057.png">

스텝 핵심 경험이 모두 수행되었기 때문에 바로 머지를 진행할 수도 있겠지만,
**Info.plist 에서의 키값에 대한 description 누락**과 **6번의 폴더 레퍼런스 누락** 건은 수정을 하고 머지를 진행하는 것이 좋을 거 같아 우선 Request Changes 로 요청 드렸어요.

혹시 추가로 이번 스텝에서 더 수정하고 넘어갔으면 하는 부분이나 설명이 필요한 코멘트가 있다면 말씀해주세요~ 🙆‍♀️🙌

2021-10-14 17:33 UTC, YebinKim commented on WeatherForecast/WeatherForecast/Scene/MainViewController.swift
> +        }
alert 생성 코드와 present 코드가 메인스레드에서 실행될 수 있도록 꼼꼼히 코드를 작성하셨군요! 😊👏

2021-10-14 17:33 UTC, YebinKim commented on WeatherForecast/WeatherForecast/Scene/MainViewController.swift
> +            else { return }
두 분기문(99번 라인의 if 구문과 102번 라인의 guard 구문)을 분리해서 작성한 이유가 있을까요?

2021-10-15 01:19 UTC, KimWanki commented on WeatherForecast/WeatherForecast/Scene/MainViewController.swift
> +            else { return }
`error`을 처리하는데 사용한 `if`문은 조기 종료를 위한 코드로 생각해본다면 `guard`가 더 적절해보이는군요!

2021-10-15 01:25 UTC, KimWanki commented on WeatherForecast/WeatherForecast/SupportingFiles/Info.plist
> +	<string>권한 요청합니다</string>
덕분에 심사 지침에 대해서도 한번 읽어볼 수 있었네요! 감사합니다  🤩🤗

2021-10-15 01:44 UTC, YebinKim approved these changes
필수 코멘트 반영 고맙습니다!
Step3 진행도 화이팅이에요 😆
DM으로 전달드렸듯 Step2는 바로 머지 진행할게요~ 고생 많으셨습니다 👏👏

2021-10-15 01:44 UTC, merged