날씨 정보 [Step3] shapiro, coden
yagom-academy/ios-weather-forecast pull request #55
Opened 2021-10-14 13:13 UTC by ictechgy

@YebinKim 
안녕하세요 비비~! [STEP3]를 후딱 만들어서 PR을 날려봅니다! ㅎㅎ 
사실 이번에는 해결하지 못한 점들도 조금 있고 해서 여쭤볼게 많습니다..! 
이번에도 잘 부탁드립니다! 🙏
&nbsp;   
## 구현내용
1. TableView의 헤더뷰 UI 구현
헤더뷰에 들어갈 뷰를 커스텀으로 만들어서 붙이는 방식으로 구현하였습니다!

2. TableView CustomCell
커스텀 셀을 코드로만 구성하여 만들었습니다.

3. RefreshControl
사용자 상호작용이 일어났을 때 `CLLocationManagerDelegate`의 `locationManager(_:didUpdateLocations:)`를 직접 호출하는 방식으로 구현하였습니다.

4. 셀 이미지 지연로딩 문제
각각의 셀에 아이콘 이미지에 대한 `iconId`를 부여하여 해결하였습니다. 
    - 셀이 재사용되기 전 아이콘에 대한 imageView를 `nil`이 되도록 구현하였습니다.
    - `iconId`가 다른 경우 네트워크를 통해 받아온 이미지가 세팅되지 않도록 하였습니다.
    -  `iconId`가 같은 경우 여러번 이미지가 업데이트 되는 것을 방지하기 위해 이미지가 `nil`인 경우에만 이미지가 세팅되도록 만들었습니다.

5. DateFormatter 날짜표현
    - DateFormatter를 이용하여 서버에서 가져온 예보날짜를 `Date`로 변형 한 후 다시 `String`으로 변환되도록 구현하였습니다. 

&nbsp;   
## 해결하지 못한 점 && 궁금한 점
1. `MainWeatherViewController`에서 `MainWeatherTableViewCell`에 데이터를 설정해주는 방식에 대하여

```swift
//MainWeatherTableViewCell.swift 
func configure(data: WeatherForOneDay) {
        
}
```
DataSource에서 데이터를 셀에 세팅해줄 때 어떠한 방식으로 세팅시켜주는 것이 가장 적절한가요? 저희는 아래와 같은 3가지 방식들을 생각해 보았는데요!

1. 위처럼 구체적인 Model타입을 넘겨주고 셀 내부에서 필요한 데이터를 뽑아 알아서 세팅하도록 하는 방법
    - View가 Model을 직접적으로 아는 것은 부적절하다는 의견이 있음(MVC 위배)
2. 뷰 컨트롤러에서 개별적으로 데이터를 넘겨주는 방법(String이나 ImangeView를 메서드 파라미터로 일일히 넘기는 방법)
    - 또는 DataSource에서 셀의 개별 프로퍼티에 직접 접근하여 바로 설정하는 방법
    - 셀에 대한 것은 셀에서 하는 것이 맞지 않은가 하는 의견이 있음
3. 데이터를 가지고 있음을 기대할 수 있는 어떤 프로토콜을 만들어두고 이를 이용하는 방법(의존성 역전)
    - 해당 프로토콜을 준수하는 구체적인 하위 타입을 정해야함

 + `MainWeatherViewController`에서 `MainWeatherHeaderView`에 데이터를 설정해주는 방식도 일단은 위의 1번 방식을 사용하도록 설정해 두었습니다.
&nbsp;   
2. `UITableView`의 `HeaderView`에 대하여.

- 왜 이 친구는 높이를 직접 설정해줘야 하는지 모르겠습니다!
    - 동적으로 높이가 알아서 설정되도록 할 수는 없을까요? (기기별로 알아서 조절된다던지 하도록)
- 구글에서 찾아봤을 때, 다른 사람들은 `layoutIfNeeded()`를 써주던데, 이걸 꼭 써야 하는 걸까요? 
- 일단 아래의 방식을 사용하여 해결하였는데 이게 어떤 방식으로 동작하는 것인지, 다른 방법은 없는 것인지 궁금합니다.
    
  ```swift
  private func sizeHeaderViewHeightToFit() {
      guard let headerView = tableView.tableHeaderView else {
          return
      }
      let height = headerView.systemLayoutSizeFitting(UIView.layoutFittingCompressedSize).height
      var frame = headerView.frame
      frame.size.height = height
      headerView.frame = frame
  }
  //headerView에 컨텐츠가 들어갔을 때마다(address, 온도별로 따로) 매번 호출되도록 하고 있음
  ```
- 저희가 내린 결론은 일단 "커스텀 헤더 뷰 내에서 스스로의 크기를 아는 것은 소용이 없고, 외부에서 직접 테이블 뷰의 헤더뷰 크기를 지정해주어야 하는 것 같다." 인데요! 이게 맞는 걸까요? 
    &nbsp;
3. 날짜 요구사항에 맞게 `Date`를 표현하는 방법에 대하여
    - `DateFormatter.dateFormat` 설정으로 하는 것은 아닌 것 같은데... 방법을 모르겠습니다. 
    - `setLocalizedDateFormatFromTemplate`을 이용해서 별 짓을 다 해봤는데, `월/일(요일) 시간` 형식으로 출력하려면 어떻게 해야하는 것인지 모르겠습니다. 
    - 게다가 `locale`을 `.current`로 설정했는데, 기기 언어 및 지역을 한국으로 했음에도 날짜 표기가 변하지가 않네요. 왜 그런것인지.. 잘 모르겠습니다. 
&nbsp;   
4. `HeaderView`의 AutoLayout이 왜 터지는지 모르겠습니다.
모르겠습니다. 계속 콘솔에는 뭐라뭐라 나오는데 이유를 도저히 모르겠네요..!  도와주세요!!!!  🙏🥲🙏

2021-10-15 08:05 UTC, YebinKim requested changes
코든, 샤피로 안녕하세요~
드디어 날씨정보 프로젝트의 1차 완성..!! Step3까지 왔네요 🥳
Step3까지 완성하느라 고생 많으셨습니다 👏👏

이번에도 구현 내용 상세하게 작성해주신 덕분에 쉽게 코드를 이해할 수 있었어요 😄
커밋에 대해서도 더 코멘트 드릴 내용은 없어서 바로 질문부터 답변드려볼게요!



---

#### 1. ViewController에서 View에 Model 데이터를 설정해주는 방식에 관하여

오호 아키텍쳐에 기반해 Model 데이터를 설정하는 방법에 관해 고민해보셨군요! 🤩

말씀하신 것 처럼 1번의 방식은 뷰가 모델을 알게 되는 문제가 있지만, 모델 데이터를 세팅하는 책임을 뷰가 가져가기 때문에 컨트롤러의 책임을 나눌 수 있다는 장점이 있고,
3번의 방식은 2번과 같이 컨트롤러에서 뷰 세팅에 대한 책임을 가지게 될 거 같네요.
각각의 방법에 대한 장단점을 잘 분석하신 거 같아요! 😄👏👍

정답은 없겠지만 저는 1번의 방식을 선호하는 편인데요.
왜냐하면 **뷰의 내용을 보여주는 것에 대한 책임은 뷰가 가지고 있는 게** 맞다고 생각하기도 하고, 뷰의 **UI 세팅 로직은 뷰 UI 프로퍼티의 초기화 코드(`resetAllContents()`)와 나란히 배치**하는 편이 이해가 잘 되며, **뷰의 UI 프로퍼티를 컨트롤러가 접근할 일이 없도록** 작성하기 위해 이 방법을 선호해요!
다만, UI 설정 외의 이미지 다운로드 로직 등은 뷰가 가지고 있지 않도록 해주는 편이구요.
즉, **표시 가능한 모델 또는 데이터를 뷰로 넘겨주는 방식**을 선호해요~

그래서 저는 1번의 방법을 선호하지만 이 방법이 정답은 아니라고 생각합니다! 😮
뷰가 모델을 알 수 없는 상황 또는 뷰에 로직을 추가하기 어려운 상황 등 상황에 따라 다른 방법을 선택할 수도 있을 거 같아요~



#### 2. `UITableView` 의 `HeaderView` 높이 설정 방법에 관하여

오호 이 부분 Section Header랑 헷갈렸었는데요! 😅
관련해서 문서를 찾아보니 [tableHeaderView](https://developer.apple.com/documentation/uikit/uitableview/1614904-tableheaderview) 의 높이를 설정하기 위한 UITableViewDelegate 프로토콜의 메서드는 따로 없는 것으로 보여요 🤔
다만, 해당 문서에서 `set the height of that view to a nonzero value` 로 높이 설정의 필요성을 언급하고 있기 때문에 높이를 설정하는 코드가 필요할 것으로 보이네요!

그리고 [layoutIfNeeded()](https://developer.apple.com/documentation/uikit/uiview/1622507-layoutifneeded) 는 해당 뷰의 레이아웃 업데이트를 즉시 호출시키는 메서드인데요.
뷰를 생성한 직후 화면에 표시되기 전까지는 레이아웃 업데이트가 일어나지 않았기 때문에 뷰에는 아직 제약조건의 값이나 지정한 frame 값이 적용되지 않았을 수 있어요.
그래서 `layoutIfNeeded()` 또는 [setNeedsLayout()](https://developer.apple.com/documentation/uikit/uiview/1622601-setneedslayout) 등의 레이아웃 업데이트 메서드를 사용함으로써 뷰에 업데이트된 값을 적용시킬 수 있는데요.
**즉시 레이아웃 업데이트가 완료된 상황에서의 높이값이 필요한 현재와 같은 경우** `layoutIfNeeded()` 호출이 필요한 경우가 있었을 수도 있겠다는 생각이 드네요!

여담으로 `layoutIfNeeded()` 는 `DispatchQueue.main.async` 와 함께 대부분의 레이아웃 문제 상황에서 즉시 문제를 해결해줄 수 있는 마법의 코드지만.. 가능하면 문제의 원인을 해결하는 것이 좋다고 생각하기 때문에 저는 불필요한 사용을 지양하고자 합니다 ☺️



#### ⭐️ 3. 요구사항에 맞게 `Date` 를 표현하는 방법에 관하여

질문을 종합해보자면 프로젝트 요구사항대로 `월/일(요일) 시간` 형식으로 표현하고자 `DateFormatter.dateFormat` 와 `setLocalizedDateFormatFromTemplate(_:)` 을 사용했지만 반영이 되지 않아 고민을 하신 것으로 보이는데요 🤔
각각의 [문서](https://developer.apple.com/documentation/foundation/dateformatter/1413514-dateformat)를 봤을 때도, 제가 생각했을 때도 현재 코드 작성은 잘 되어 있지만, 기기 언어 및 지역을 한국으로 했음에도 날짜 표기가 변하지가 않는 문제 때문에 원하는 결과 화면을 보지 못 하셨을 거 같아요..!

우선 이 문제는 이전에 저도 고민해봤지만 명확히 답을 찾진 못 한 문제인데요..! (혹시 원인을 알게 되면 저도 꼭 알려주세요 😂)
아마 `Locale.current` 는 프로젝트의 다국어로서 지원되는 언어에 대해서만 정보를 가져올 수 있는 것으로 보여요 🤔
[문서](https://developer.apple.com/documentation/foundation/nslocale/1409990-current)를 봤을 때는 사용자의 현재 지역에 따라 정보를 가져와야 할 것 같은데.. 실기기에서나 시뮬레이터에서나 지역 설정을 바꿔봐도 `Locale.current` 는 바뀌지 않더라구요 😅
하지만, 사진과 같이 프로젝트 Info에 다국어를 추가하면 `DateFormatter.dateFormat` 의 설정대로 `월/일(요일) 시간` 형식이 잘 보이는 것을 확인할 수 있어요!

<img src="https://user-images.githubusercontent.com/38066039/137453130-165036ef-ff8d-461c-b398-71d7bc5b8cdb.PNG" width=50% height=50%>

그리고 공식문서를 봤을 때, 설정앱에서의 사용자의 설정 언어를 가져오기 위한 방법으로 [preferredLanguages](https://developer.apple.com/documentation/foundation/locale/2293155-preferredlanguages) 를 사용하는 것도 권장하고 있으니 이 프로퍼티를 활용해보는 것 또한 생각해볼 수 있을 거 같아요~



#### 4. `HeaderView` 의 AutoLayout 이 에러 메세지 출력에 관하여

우선 콘솔창에 출력되는 Visual Format Language 형태의 레이아웃을 쉽게 보는 사이트를 하나 소개드릴게요!
https://www.wtfautolayout.com

그리고 에러문구의 내용처럼 UIViewAlertForUnsatisfiableConstraints 심볼을 브레이크 포인트에 추가해서 디버깅해보는 방법 또한 있는데요.

현재 디버깅을 해보았을 때도 문제 원인을 파악하기가 쉽지 않아서.. 이 부분은 저도 고민을 좀 더 해보도록 할게요 🤔



---

Step3 진행 고생 많으셨습니다~!
회의실에서 말씀드렸듯 현재 **UI에서 한국어가 표시되지 않는 문제**(⭐️ 표시 된 문제)는 수정하고 머지를 진행했으면 하는데요 ☺️
그 외의 핵심 경험들은 모두 충분히 진행되어 보입니다 🙆‍♀️🙌

<img width="320" alt="Step3" src="https://user-images.githubusercontent.com/38066039/137453263-c90c6c09-86ee-4886-896a-4eadb16b4994.png">

그 외의 수정사항을 더 반영했으면 하거나 설명이 필요한 코멘트가 있다면 말씀해주세요~ 👀👂

2021-10-15 09:44 UTC, YebinKim approved these changes
필수 코멘트 반영 고맙습니다~
다음 스텝 진행도 화이팅입니다!! 🙆‍♀️👏

2021-10-15 09:44 UTC, merged

2021-10-15 16:02 UTC, ictechgy commented on WeatherForecast/WeatherForecast/Controller/MainWeatherViewController.swift
> +    private func updateHeadView(to newInformation: WeatherForOneDay?) {
해당 부분 미쳐 생각하지 못했습니다. 고쳐보도록 하겠습니다!

2021-10-15 16:22 UTC, shapiro711 commented on WeatherForecast/WeatherForecast/View/MainWeatherHeaderView.swift
> +class MainWeatherHeaderView: UIView {
저희가 놓쳤습니다... 수정해볼게요!!!

2021-10-15 16:23 UTC, shapiro711 commented on WeatherForecast/WeatherForecast/View/MainWeatherHeaderView.swift
> +        let absoluteZero = -273.15
사실 스탭4 내용을 보고 단위에 대한 FormatManager 라는 타입을 따로 빼서 관리를 하려 했습니다... 그래서 후딱 넘어간 경향이 있는것 같아요 ㅠㅜ

2021-10-20 16:37 UTC, YebinKim commented on WeatherForecast/WeatherForecast/View/MainWeatherTableViewCell.swift
> +        if weatherIconImageView.image == nil {
오호! 작성하신 의도를 들어보니 왜 nil을 확인해야 하는지가 이해되었어요!
그렇다면 말씀하신 **동작에 대한 검증의 역할**은 뷰가 아닌 컨트롤러가 가져야 하는 것이 아닌가 대해서도 한 번 생각해보면 좋을 거 같습니다 ☺️

2021-10-20 16:45 UTC, YebinKim commented on WeatherForecast/WeatherForecast/View/MainWeatherTableViewCell.swift
> +    func resetAllContents() {
오호 저도 몰랐던 부분이네요 😄👍
문서를 읽어보니 잠재적인 성능 문제를 방지하기 위해 컨텐츠와 관련이 없는 설정에 대해서만 `prepareForReuse()` 메서드에서 초기화를 해주는 것이 좋다는 것! 이해했어요~

2021-10-20 17:02 UTC, YebinKim commented on WeatherForecast/WeatherForecast/Controller/MainWeatherTableViewDataSource.swift
> +                guard cell.iconId == imageId else {
셀 재사용이 있을 때는 이론적으로 발생할 수 있는 일이겠네요!
이에 대한 설명은 코든과 샤피로가 이해하신 내용이 맞습니다 😄👍

클로저는 내부 블럭이 실행될 때 외부의 값을 얻어오고 있으니 네트워크 응답이 많이 늦어진 상태에서 셀을 새로 그려줄 경우, 셀 재사용에 의해 현재 cell.iconId 가 달라지고 imageId 는 바뀌지 않을 가능성이 있겠네요.

하지만 이 상황에서 동작의 핵심은 **네트워크 응답을 기다리던 중 현재 셀에 대한 요청이 변하는 경우**이기 때문에 네트워크 요청을 취소하고 다시 보내는 것이 필요할 거 같다는 의문이 남긴 합니다 🤔

혹시 제가 이해한 상황과 설명하고자 한 상황이 다르다면 말씀해주세요~ 더 얘기 나눠봅시다!