날씨정보(후) [Step1] hosinging
yagom-academy/ios-weather-forecast pull request #59
Opened 2021-10-15 02:20 UTC by Hosinging

안녕하세요 라자냐~! @wonhee009 
어제 말씀드린대로 새벽에 마무리 지을 수 있을거라 생각했는데, 연습했던 방법 말고 새로운 방법을 시도해보다가 발생한 변수들과 놓친 부분때문에 해결하지 못한 부분이 있어서 완전한 마무리는 짓지 못했지만, 기한을 더 넘기기 전에 PR을 우선 보내게됐습니다. 
참고할 부분이나 놓친 부분에 대해서 피드백 주신다면 감사하겠습니다. 
잘 부탁드립니다.

## 미완료인 부분
1. 이미지 데이터 받아오기 및 표시
이 부분을 tableviewprefetching을 이용해서 구현해보려고 초반에 만들어나다가 꼬였는데, 이후에 해야될 작업들이 많아서 일단은 그 상태로 홀드하고, 다른 작업들을 우선 진행했습니다.
PR후 잠시 휴식을 취한 후 오후 중에 해당 방법으로 다시 해결을 시도하든, 다른 방법으로 시도하든 다시 도전해보도록 하겠습니다.

2. Alert에서 변경과 현재 위치로 데이터 다시 받아오기
기존에 만들어둔 현재 날짜와 5일 날짜 데이터를 가져오는 메서드들을 location을 받아 하나의 메서드 안에서 각각 호출을 할 수 있도록 리팩터링했고, 만들어진 하나의 메서드를 alert의 각 버튼의 completion안에서 호출하고 테이블뷰를 리로드하도록 구현했는데, 네트워킹해서 값을 프린트 해본 결과로는 잘 나오는데 어디를 놓친 것인지 새로운 좌표로 다시 불러와서 테이블뷰를 업데이트 하는 작업이 되지 않고 있습니다.
차분히 다시 보면 될 것 같은데 잠시 휴식을 취하고 다시 도전해도록 하겠습니다.

---

## 고민했던 부분
- 셀에 들어가는 스택뷰에서 어떤 방식으로 해야 기능상세와 같은 UI를 구성할 수 있을지 고민이 됐습니다. 스토리보드에서는 쉽게 적용했던 내용이 코드로 적용해보니 실행해보기 전에는 보이지 않고, 조금 다른 부분이 있는 것 같아서...현재 UIImageView의 intrinsicContentSize를 오버라이드해서 기능상세와 비슷하게 ui구성은 했지만 고정값이기 때문에 추후 해결해야될 것 같습니다.(이 부분은 네트워킹으로 데이터를 받아오는 부분을 prefetching으로 구현해보려다 막혀서 임시 이미지를 UI에 반영해 본 내용을 기준으로 적은 것 입니다.)

- nil coalescing Operator를 문법적으로는 어느 상황에서 쓰는지 알지만 실무에서 잘 쓰이는지, 쓰인다면 어느 상황에서는 피하고, 어느 상황에서는 사용해도 되고 그런게 있는지 궁금합니다. 개인적으론 항상 옵셔널 바인딩을 통해서 옵셔널을 해제하고 사용했었는데, 특정값을 리턴해야하는 경우 guard let구문에서 (리턴되는 차이점은 제외하고) else 블록에 넣는 임의의 리턴 값들이 nil coalescing과 별다를바가 없는 것 같다는 생각이 갑자기 들어서 질문드려봅니다.

2021-10-15 12:55 UTC, wonhee009 requested changes
호싱잉 수고하셨습니다!😀
코멘트 남겨놨으니 확인 부탁드려요!🙏

- nil coalescing Operator
실무에서는 잘 사용하지 않습니다.
`guard let`과 `??`이 갖는 의미를 생각해보면 좋을거 같습니다.
`guard let`은 공식문서에서도 나와 있듯 early exit가 가능하죠. else 문에는 return뿐만 아니라 throw, continue, break를 적을 수도 있고요.
`??`는 어떤가요? `??` 항상 어떠한 유의미한 값이 들어가게 되죠.

2021-10-15 12:55 UTC, wonhee009 commented on WeatherForecast/WeatherForecast/Data/WeatherDataManger.swift
> +                URLResource.QueryParam(name: "\(ParamName.lang)", value: Lang.korea)
`"\(ParamName.lat)"` 이런 형태가 반복되는거 같은데요. 반복되는 부분을 분리할 수 있을까요?

2021-10-15 12:55 UTC, wonhee009 commented on WeatherForecast/WeatherForecast/Extension/extension + Date.swift
> +}()
현재 사용하는 곳이 없는거 같은데요 맞을까요?

2021-10-15 12:55 UTC, wonhee009 commented on WeatherForecast/WeatherForecast/Extension/extension + Double.swift
> +extension Double {
<img width="543" alt="image" src="https://user-images.githubusercontent.com/30456206/137488303-c0c0196a-257a-4a78-bc5a-187d49105290.png">

`String(latitude)`같은 부분도 Double extension에 
```
func toString() -> String {
     return String(self)
}
```
같이 구현해서 사용할 수 있지 않을까요?

2021-10-15 12:55 UTC, wonhee009 commented on WeatherForecast/WeatherForecast/Views/CustomHeaderView.swift
> +enum AlertResource: String {
`AlertResource`라는 네이밍은 모호한거 같아요.
어떤 Alert에 대한 정보인지 알 수 있으면 좋지 않을까요?

2021-10-15 12:55 UTC, wonhee009 commented on WeatherForecast/WeatherForecast/Views/CustomHeaderView.swift
> +enum AlertResource: String {
그리고 `CustomHeaderView` 파일과 같이 있을만한 내용인가요?

2021-10-15 12:55 UTC, wonhee009 commented on WeatherForecast/WeatherForecast/Views/CustomHeaderView.swift
> +//        button.isUserInteractionEnabled = true
사용하지 않는 코드는 지워주세요😀

2021-10-15 12:55 UTC, wonhee009 commented on WeatherForecast/WeatherForecast/Views/CustomHeaderView.swift
> +
줄바꿈이 잘못 들어간거 같아요:)

2021-10-15 12:55 UTC, wonhee009 commented on WeatherForecast/WeatherForecast/Views/CustomHeaderView.swift
> +        NotificationCenter.default.post(name: NSNotification.Name("alert"), object: nil)
"alert"라는 NotificationName이 너무 모호한거 같아요.
NotificationName은 범용적으로 쓰일 수 있는 만큼 어떤 것에 대한 Notification인지 알 수 있는 네이밍이 좋지 않을까요?

2021-10-15 12:55 UTC, wonhee009 commented on WeatherForecast/WeatherForecast/Data/URLResource.swift
> +        case fiveDays = "/data/2.5/forecast"
enum rawValue로 url 조합에 이용하고 있네요.
rawValue란 무엇일까요?
```swift
enum PathType {
        case current
        case fiveDays

        var path: String {
            switch self {
            case .current:
                return "/data/2.5/weather"
           ...
            }
        }
    }
```
위의 코드와 호싱잉의 코드랑 어떤 다른 점이 있을까요?

2021-10-20 22:33 UTC, TheoPyeon commented on WeatherForecast/WeatherForecast/Data/WeatherURL.swift
> +//}
테스트해보는 과정에서 특정 코드를 넣었다가 지웠는데 지우는 것을 미처 확인 못했던 것 같습니다. 확인했습니다.

2021-10-20 23:00 UTC, Hosinging commented on WeatherForecast/WeatherForecast/Data/WeatherURL.swift
> +//}
테스트해보는 과정에서 특정 코드를 넣었다가 지웠는데 지우는 것을 미처 확인 못했던 것 같습니다. 확인했습니다.

2021-10-20 23:00 UTC, Hosinging commented on WeatherForecast/WeatherForecast/Extension/extension + Date.swift
> +}
테스트해보는 과정에서 특정 코드를 넣었다가 지웠는데 지우는 것을 미처 확인 못했던 것 같습니다. 확인했습니다.

2021-10-20 23:00 UTC, Hosinging commented on WeatherForecast/WeatherForecast/Models/CurrentWeather.swift
> +    let name: String
아님을 확인했습니다. 필요한 부분만 남기고 정리했습니다.

2021-10-20 23:00 UTC, Hosinging commented on WeatherForecast/WeatherForecast/Models/CurrentWeather.swift
> +    }
확인했습니다. 따로 타입을 분리해줬습니다.

2021-10-20 23:00 UTC, Hosinging commented on WeatherForecast/WeatherForecast/Controllers/WeatherListViewController.swift
> +        control.tintColor = self?.view.tintColor
특별한 이유는 없었습니다. 참고했던 예제에서 해당 방식으로 했었고, 특별히 거슬리는 색상이 아님을 확인했고, 해당 방식과 같이도 할 수 있음을 알 수있도록 하기 위해 그대로 사용해봤습니다.

2021-10-20 23:01 UTC, Hosinging commented on WeatherForecast/WeatherForecast/Controllers/WeatherListViewController.swift
> +        tableView.register(CustomHeaderView.self, forHeaderFooterViewReuseIdentifier: CustomHeaderView.identifier)
보다 직관적인 네이밍으로 변경했습니다.

2021-10-20 23:04 UTC, Hosinging commented on WeatherForecast/WeatherForecast/Controllers/WeatherListViewController.swift
> +        bringCoordinates()
잘 지켜지지 않는 부분들이 있어서 이런 의문이 드실 수도 있다고 생각합니다.ㅠㅠ 
locationManager를 생성하고, 좌표를 가져오는 코드를 하나의 함수로 담아서 사용할 수도 있겠지만, 생성하는 부분과 좌표를 가져오는 부분을 분리해보고자 했습니다. 이런 경우는 하나로 담아서 사용하는게 적절했을까요?

2021-10-20 23:07 UTC, Hosinging commented on WeatherForecast/WeatherForecast/Controllers/WeatherListViewController.swift
> +//            let formattedDateString = "\(dateFormatter.string(from: date))시"
지우는 것을 미처 확인 못했던 것 같습니다. 확인했습니다.

2021-10-20 23:09 UTC, Hosinging commented on WeatherForecast/WeatherForecast/Controllers/WeatherListViewController.swift
> +        if let unWrappedFiveDaysWeatherData = WeatherDataManager.shared.fiveDaysWeatherData {
싱글턴 객체의 멤버에 바인딩하고, 그 값을 사용하기 때문에 사용하지 않음을 확인했지만, 미처 지우지 못했던 것 같습니다. 확인했습니다.

2021-10-20 23:30 UTC, Hosinging commented on WeatherForecast/WeatherForecast/Controllers/WeatherListViewController.swift
> +            cell.cellConfiguration(date: date, minTemperature: minTemperature)
FivedaysWeather 데이터를 주입받아 그리는 방식으로 수정해봤습니다.

2021-10-20 23:32 UTC, Hosinging commented on WeatherForecast/WeatherForecast/Controllers/WeatherListViewController.swift
> +            return UIView()
nil값의 반환이 가능하지만, 위와 같은 방식으로 빈 객체를 반환하는 코드 예제에 익숙하다보니 해당 방식으로 해봤던 것 같습니다.

2021-10-20 23:40 UTC, Hosinging commented on WeatherForecast/WeatherForecast/Controllers/WeatherListViewController.swift
> +        if let unWrappedCurrentWeatherData = WeatherDataManager.shared.currentWeatherData, let area = area, let local = local {
unWrappedCurrentWeatherData가 위에서 언급된 unWrappedFiveDaysWeatherData와 같은 맥락으로 볼 수 있고 위가 수정되면 이곳도 같이 수정되어야된다고 생각되어 해당 부분을 수정하며 같이 네이밍 부분 수정했습니다.

바인딩 구문에서 area 와 local이 결국 하나의 주소를 표현하므로, 좌표를 주소로 변환하며 전역변수에 담아 사용할 수 있도록 수정해 해당 바인딩 구문을 줄일 수 있도록 수정했습니다.

2021-10-20 23:42 UTC, Hosinging commented on WeatherForecast/WeatherForecast/Controllers/WeatherListViewController.swift
> +        }
data를 주입해서 그리는 방식으로 수정했습니다.

2021-10-20 23:52 UTC, Hosinging commented on WeatherForecast/WeatherForecast/Views/CustomHeaderView.swift
> +        NotificationCenter.default.post(name: NSNotification.Name("alert"), object: nil)
NSNotification.Name을 확장해서 노티피케이션 이름을 지정해주고, 
```swift
NSNotification.Name.changeCoordinateAlert
```
다음과 같은 직관적 네이밍의 노티피케이션을 사용하는 형태로 수정해줬습니다.

2021-10-20 23:54 UTC, Hosinging commented on WeatherForecast/WeatherForecast/Views/CustomHeaderView.swift
> +
확인했습니다.

2021-10-20 23:58 UTC, Hosinging commented on WeatherForecast/WeatherForecast/Data/URLResource.swift
> +        case fiveDays = "/data/2.5/forecast"
계산속성을 통해 값을 매칭해주는 패턴을 사용해볼까 고민해본적이 있습니다. PathType.path로 접근했을 때 지정된 case에 맞는 동일한 값을 리턴해주기 때문에 더 간단한게 아닐까 생각해봤기 때문인데요. 제가 경험한 바로는 오히려 기본값으로 접근하는 것에 비해 case추가와 함께 switch문에 관련 분기 코드가 추가되어야되기 때문에 오히려 더 불편해지는 것이 아닌가 생각이 들어 기본값을 사용하는 형태로 이 부분도 정리를 해봤습니다. 혹시 기본값의 사용이 코드의 가독성을 떨어뜨린다거나 문제가되는 부분이 있어서 위와 같은 패턴의 처리가 더 좋은 그런게 있을까요?

2021-10-21 00:08 UTC, Hosinging commented on WeatherForecast/WeatherForecast/Views/CustomHeaderView.swift
> +enum AlertResource: String {
다양한 Alert가 있을 때 어떤 식으로 관리를 할까..고민을 해봤었는데요. 따로 관리하는 파일을 두고 하지 않을까 싶어 해당 방식으로 해볼까 고민해봤지만, 헤더뷰와 관련된 Alert의 Resource이고 추가 Alert가 없다고 생각되어 해당 부분에 위치를 시켜봤었습니다. 

Alert가 많아지고, 내용이 다양해진다면 어떤 방식으로 관리가 이루어지는게 좋을까요? 라나쟈는 어떤 방식으로 관리를 하시는지 궁금합니다.

HeaderViewAlertResource와 같은 네이밍으로 좀 더 직관적으로 보일 수 있도록 수정해봤습니다.

2021-10-21 00:21 UTC, Hosinging commented on WeatherForecast/WeatherForecast/Extension/extension + Double.swift
> +extension Double {
참고해서 반영했습니다.

2021-10-21 00:23 UTC, Hosinging commented on WeatherForecast/WeatherForecast/Extension/extension + Date.swift
> +}()
해당 부분을 활용하려고 뒀지만, 당시에는 활용을 하지 않았던게 맞습니다. 
활용 필요한 부분에서 활용할 수 있도록 했습니다.

2021-10-21 00:34 UTC, Hosinging commented on WeatherForecast/WeatherForecast/Controllers/WeatherListViewController.swift
> +            guard let strongSelf = self else { return }
참고한 예제에서 해당 네이밍과 같은 형태로 사용을 하기도했고, [weak self]로 캡쳐가 해제될 수 있게(?)해줬더니 self가 전부다 옵셔널처리가 되길래 바인딩된 self는 해제가 되지 않는 느낌인 것 같아서 해당 네이밍이 뭔가 이상하지 않다고 생각했던 것 같습니다. 그래서 그대로 사용했었고, 밑에 self?.는 혼용해서 사용하는게 가능한지 궁금해서 작성했었던 것인데 미처 수정을 못했습니다. 해당 부분 수정했습니다.

2021-10-21 00:39 UTC, Hosinging commented on WeatherForecast/WeatherForecast/Data/WeatherDataManger.swift
> +        builder.pathType = path
해당 메서드가 중복되는 기능이 있어서 해당 메서드는 제거했습니다.

2021-10-21 01:12 UTC, Hosinging commented on WeatherForecast/WeatherForecast/Data/WeatherDataManger.swift
> +                    print(error.localizedDescription)
Notification을 통해 실패가 전달됐을 때 Alert가 표시될 수 있도록 해줬습니다.

2021-10-21 01:41 UTC, Hosinging commented
안녕하세요 라자냐 @wonhee009 
tableView reloadData와 DataSource관련한 부분들을 좀 더 깔끔하게 할 수 있지 않을까..쉽게 할 수 있지 않을까 해서...수고스럽더라도 말씀드렸었던 내용들의 반영을 위해 각 각의 것들에 대한 연습을 해보고 반영해보고자 노력을 기울였었는데요... 하나 하나로 해볼 때는 잘됐었는데 막상 프로젝트에 하나로 담으려고 하니 문제가 되는 부분들이 생겨났고, 이 부분들 해결이 되지 않는데 마지막이 다가오는 시점에 위의 실패를 받아들이지 못하고 좀 더하면 되겠지  좀 더 보면 되겠지 뭘 놓쳤을까...계속 혼자 해결해보려고 붙잡고 있다보니 리뷰에 대한 피드백도, 프로젝트 진행도, 구조적으로 만져보고자 했던 부분들도 모두 다 늦어지는 유감스러운 상황이 되었습니다. 

해서, 이렇게는 안되겠다 싶어서 일단은 기존 테이블뷰 데이터 소스를 처리하는 방식으로 리뷰 주신 내용들을 수정하며, 전 프로젝트 스텝3에서 반영되었어야될  내용 일부와 현재 프로젝트 스텝1에서 반영할 수 있는 부분들 일부를 반영을 해봤습니다.

- 이미지 표시, 헤더뷰 리로드, 날짜 정상 표시, 데이터 가져오는게 실패했을 때 Alert표시 등

---
> 해결하지 못한 부분, 고민한 부분

1. 새로운 위치값 입력 후 날씨 데이터 가져오기 후 일부만 표시, 현재 위치로 변경 시 변경된 데이터 일부만 표시
- 헤더뷰와 테이블뷰를 다시 데이터를 가져와서 헤더뷰와 테이블뷰를 리로드 하는 방식으로 구현해봤는데 
헤더뷰의 주소값은 변경이 되지만, 헤더뷰와 테이블뷰 셀의 데이터가 변경이 되지 않는 현상
- 위치 설정 Alert에서 '현재 위치로 재설정'하거나, 특정 좌표로 '변경'했을 때 두 번을 해줘야 적용이 되는 현상


해결하지 못한 부분이 어떤 이유에서인지, 어떤 것을 반영해보면 좋을지 키워드나 코드로 알려주신다면 확인해서 추가 반영해보겠습니다. 감사합니다.

2021-10-21 11:17 UTC, wonhee009 commented on WeatherForecast/WeatherForecast/Controllers/WeatherListViewController.swift
> +        bringCoordinates()
역할을 분리하기 위해 따로 작성하셨군요😀

2021-10-21 11:23 UTC, wonhee009 commented on WeatherForecast/WeatherForecast/Data/URLResource.swift
> +        case fiveDays = "/data/2.5/forecast"
제가 생각하는 rawValue는 말 그대로 기본값이라고 생각해요.
호싱잉 코드에서 PathType의 rawValue는url을 만드는데 필요한 파라미터들을 가지고 있는데요.
이런 부분들이 PathType의 기본값일까?라는 생각이 들어서요.
물론 어떤게 더 좋다라기 보단 저의 생각일뿐입니다.😀

2021-10-21 11:26 UTC, wonhee009 commented on WeatherForecast/WeatherForecast/Views/CustomHeaderView.swift
> +enum AlertResource: String {
AlertResource는 전체 서비스에서 사용되는 모든 alert에 대해서 관리하는거 같아요.
사용되는 alert의 종류가 많아진다면 AlertResource로 관리하기에는 너무 힘들지 않을까요?
저는 보통 alert 콘텐츠를 alert을 호출하는 곳에서 주입하는 식으로 했던거 같습니다.

2021-10-21 12:02 UTC, wonhee009 requested changes

2021-10-21 12:02 UTC, wonhee009 commented on WeatherForecast/WeatherForecast/Controllers/WeatherListViewController.swift
> +        if let unWrappedCurrentWeatherData = WeatherDataManager.shared.currentWeatherData, let address = address {
`if let`으로 unWrapping을 했는데 `unWrappedCurrentWeatherData`라는 네이밍은 어색한거 같아요.

2021-10-21 12:02 UTC, wonhee009 commented on WeatherForecast/WeatherForecast/Controllers/WeatherListViewController.swift
> +                WeatherDataManager.shared.fetchWeatherDatas(location: CLLocation(latitude: currentLocation.latitude, longitude: currentLocation.longitude)) {
`fetchWeatherDatas()`에서 DispatchQueue에 넣어주고 있는데요.
`DispatchQueue.global().async`안에 다시 넣어줘야하나요?

2021-10-21 12:02 UTC, wonhee009 commented on WeatherForecast/WeatherForecast/Controllers/WeatherListViewController.swift
> +                    }
`fetchWeatherDatas`로 날씨 정보를 가져오고 그 이후에 테이블뷰를 리로드하는 코드로 보이는데요.
location이 업데이트되면 `func locationManager(_ manager: CLLocationManager, didUpdateLocations locations: [CLLocation])` <- 해당 메서드가 호출될거 같은데요.
날씨 정보를 가져오는 메서드는 해당 메서드 내에서 호출해야하는거 아닌가 생각이 듭니다.

2021-10-21 12:02 UTC, wonhee009 commented on WeatherForecast/WeatherForecast/Controllers/WeatherListViewController.swift
> +    }
위치를 가져오는데 실패했음을 사용자가 몰라도 괜찮을까요?

2021-10-21 12:02 UTC, wonhee009 commented on WeatherForecast/WeatherForecast/Controllers/WeatherListViewController.swift
> +        WeatherDataManager.shared.fetchCurrentWeather(location: location) { result in
해당 메서드는 현재 날씨만 가져오는거로 보이는데요.
`reloadHeaderView()`라서 UI만 업데이트해주는거로 보여요.
두개를 분리해보는건 어떨까요?

2021-10-21 12:02 UTC, wonhee009 commented on WeatherForecast/WeatherForecast/Data/URLBuilder.swift
> +    }
URLBuilder는 인스턴스가 생성된 후에는 pathType이 바뀔 일이 없을거 같은데요.
해당 메서드가 필요한가요?

2021-10-21 12:02 UTC, wonhee009 commented on WeatherForecast/WeatherForecast/Data/URLBuilder.swift
> +    }
둘 다 queries에 append해주는 메서드로 보이는데요.
addQueries(_ queries: [])만 사용해도 되지 않을까요?

2021-10-21 12:02 UTC, wonhee009 commented on WeatherForecast/WeatherForecast/Data/URLBuilder.swift
> +        }
```swift
urlComponents.path = pathType.rawValue
```
로 해도 동일하게 동작할거 같습니다.

2021-10-21 12:02 UTC, wonhee009 commented on WeatherForecast/WeatherForecast/Extension/extension + UIView.swift
> +}
UIView가 URLMakable을 채택할 일이 있나요..?

2021-10-21 12:02 UTC, wonhee009 commented on WeatherForecast/WeatherForecast/Views/IntervalWeatherTableViewCell.swift
> +    func cellConfiguration(data: FivedaysWeather, indexPath: IndexPath) {
`cell.cellConfiguration()`으로 사용될거 같은데요.
`cell.configure()`로 해도 의미가 통할거 같습니다.
cell이 반복되어 나오는게 부자연스러운거 같습니다.

2021-10-21 12:02 UTC, wonhee009 commented on WeatherForecast/WeatherForecast/Views/CurrentWeatherHeaderView.swift
> +    func configurationHeaderView(data: CurrentWeather, address: String) {
`headerView.configurationHeaderView()`로 사용될거 같은데요.
`headerView.configure()`로도 의미가 통할거 같습니다.

2021-10-21 12:02 UTC, wonhee009 commented on WeatherForecast/WeatherForecast/Protocol/URLMakable.swift
> +}
```swift
extension URLMakable {
     var urlBuilder { return URLBuilder() }
}
```
로 기본 구현을 해놓는다면

```swift
extension UIView: URLMakable {
     var urlBuilder { return URLBuilder() }
}
```
을 안해줘도 될거 같습니다.

2022-03-24 13:44 UTC, closed without merging