날씨정보(전) [Step3] 수박, 샬롯
yagom-academy/ios-weather-forecast pull request #65
Opened 2021-10-16 13:26 UTC by yaewonLee

@leejun6694 , @soo941226

안녕하세요 쿠마 미완성 상태이지만 피드백 받고싶어서 PR 보냅니다 🙇🏻‍♂️

---

## 고민했던 점
* 기존의 URLGenerator와 NetworkManager의 로직들이 변경된다면 아주 수고스러운 일이 될 것 같다는 생각에, ImageEndPoint라는 타입을 만들어서 URLGenerator와 NetworkManager는 일을 확장하는 형태로 구현이 되도록 고민을 해보았습니다.
* 현재 MainViewController가 많은 기능을 직접 담당하게 되면서 문서가 매우 길어지고 있는데, 이러한 부분을 나누는 게 좋을지 그대로 가는 게 좋을지 고민하고 있는 상태입니다. 나누자면 값을 주고받는 부분이 필요해질 것이며 이러한 부분을 구현하느라 시간을 보낼 것 같았고... 안나누자니 타입이 비대해지면서 앞으로 추가될 기능들을 덧붙이다가 에러가 생기면 해결하기가 점점 힘들어질 것 같았습니다...

## 궁금한 점
* TableView가 연관되어지는 뷰들에 대해서 이름을 명료하게 파악할 수 있도록 고민을 해보았는데, 짓다 보니 MainViewTableViewHeaderView와 같은 이름이 되었는데 이런 부분이 적절하다고 생각되시는지 궁금합니다.

2021-10-18 20:50 UTC, leejun6694 requested changes
이전에 리뷰 드렸던 내용과 구현을 다하지 못했던 부분을 반영해보는 시간을 가져보아요 : )
이유를 여쭤보는 리뷰가 조금 있는데, 천천히 답변 달아주시면 감사합니다!

2021-10-18 20:50 UTC, leejun6694 commented on WeatherForecast/WeatherForecast/Location/LocationManager.swift
> +        workItem = DispatchWorkItem {
생소한 코드네요!?
`DispatchWorkItem` 은 type 이 아닌가요?

2021-10-18 20:50 UTC, leejun6694 commented on WeatherForecast/WeatherForecast/Network/APIEndPoint.swift
> +    static let APIKey = (name: "appid", value: "a529112a5512a01db04290ddf7b83639")
네이밍을 대문자로 시작하는 이유가 있을까요?

2021-10-18 20:50 UTC, leejun6694 commented on WeatherForecast/WeatherForecast/Network/NetworkManager.swift
> +    func request(
request method 가 하나로 관리될 수 있을 것 같습니다.
천천히 생각해볼까요?

2021-10-18 20:50 UTC, leejun6694 commented on WeatherForecast/WeatherForecast/Network/Parser.swift
> +    private let decoder = JSONDecoder()
decoder 를 property 로 갖고 있는 이유가 있을까요?

2021-10-18 20:50 UTC, leejun6694 commented on WeatherForecast/WeatherForecast/Protocol/Requestable.swift
> +    associatedtype Path: RawRepresentable
Path 도 다시 한번 생각해볼까요!?

2021-10-18 20:50 UTC, leejun6694 commented on WeatherForecast/WeatherForecast/Protocol/Requestable.swift
> +        return result
mirror...? 어떤 구조인지 잘 이해가 안되는데, 설명 부탁드려요~~!

2021-10-18 20:50 UTC, leejun6694 commented on WeatherForecast/WeatherForecast/ViewController/Main/MainViewController.swift
> +        tableView.dataSource = self
`viewDidLoad` 에 `tableView` 와 관련된 코드가 많습니다.
이 부분도 method 로 정리해볼까요?

2021-10-18 20:50 UTC, leejun6694 commented on WeatherForecast/WeatherForecast/ViewController/Main/MainViewController.swift
> +        super.viewDidAppear(animated)
추가 구현이 없는 method 는 제거 부탁드려요 : )

2021-10-18 20:50 UTC, leejun6694 commented on WeatherForecast/WeatherForecast/ViewController/Main/MainViewController.swift
> +
아직 구현이 안된 부분은 TODO 를 남겨주시면 감사합니다~~

2021-10-18 20:50 UTC, leejun6694 commented on WeatherForecast/WeatherForecast/ViewController/Main/MainViewTableViewCell.swift
> +    let iconView = UIImageView()
`timeLabel`, `temperatureLabel`, `iconView` 도 위치를 다시 생각해볼까요?

2021-10-18 20:50 UTC, leejun6694 commented on WeatherForecast/WeatherForecast/ViewController/Main/MainViewTableViewCell.swift
> +class MainViewTableViewCell: UITableViewCell {
View 가 중복되고 있네요...ㅎㅎ
네이밍은 어렵지만 ㅠㅠ 다시 생각해볼까요?

2021-10-18 20:50 UTC, leejun6694 commented on sampleOfCurrent.json
> +{
전에 말씀 드렸던 각 model 에 정의해보는건 어떨까요?

2021-10-18 20:54 UTC, leejun6694 commented
- 기존의 URLGenerator와 NetworkManager의 로직들이 변경된다면 아주 수고스러운 일이 될 것 같다는 생각에, ImageEndPoint라는 타입을 만들어서 URLGenerator와 NetworkManager는 일을 확장하는 형태로 구현이 되도록 고민을 해보았습니다.

> 현재 NetworkManager 도 충분히 잘 구현해주셨습니다. 다만, 저희가 얘기 나눴던 것처럼 조금 더 발전을 위해서 로직을 변경하는 수고스러운 일을 도전해보죠!

- 현재 MainViewController가 많은 기능을 직접 담당하게 되면서 문서가 매우 길어지고 있는데, 이러한 부분을 나누는 게 좋을지 그대로 가는 게 좋을지 고민하고 있는 상태입니다. 나누자면 값을 주고받는 부분이 필요해질 것이며 이러한 부분을 구현하느라 시간을 보낼 것 같았고... 안나누자니 타입이 비대해지면서 앞으로 추가될 기능들을 덧붙이다가 에러가 생기면 해결하기가 점점 힘들어질 것 같았습니다...

> MVC (Massive ViewController) 를 해결하는 것은 쉽지 않은 일입니다. 크게 걸리는 부분이 없다면, 이 부분은 이번엔 넘어가보시죠~~!

- TableView가 연관되어지는 뷰들에 대해서 이름을 명료하게 파악할 수 있도록 고민을 해보았는데, 짓다 보니 MainViewTableViewHeaderView와 같은 이름이 되었는데 이런 부분이 적절하다고 생각되시는지 궁금합니다.

> `View` 단어가 너무 많이 반복되는 것 같습니다ㅠㅠ

2021-10-19 01:51 UTC, soo941226 commented on WeatherForecast/WeatherForecast/Location/LocationManager.swift
> +        workItem = DispatchWorkItem {
말씀하시고자 하는 의도를 정확히 파악하지 못한 거 같아요~

2021-10-19 06:47 UTC, soo941226 commented on WeatherForecast/WeatherForecast/Network/Parser.swift
> +    private let decoder = JSONDecoder()
제거하는 쪽으로 반영하였습니다~

2021-10-19 06:47 UTC, soo941226 commented on WeatherForecast/WeatherForecast/ViewController/Main/MainViewController.swift
> +        tableView.dataSource = self
setUpTableView라는 메소드를 정의하여 호출하는 쪽으로 변경해보았습니다

2021-10-19 06:47 UTC, soo941226 commented on WeatherForecast/WeatherForecast/ViewController/Main/MainViewController.swift
> +        super.viewDidAppear(animated)
감사합니다 반영하였습니다~~

2021-10-19 06:48 UTC, soo941226 commented on sampleOfCurrent.json
> +{
실제 프로젝트에서는 들고 있을 필요가 없을 것 같아서, 테스트 프로젝트에서 모델을 확장하여 정의하는 쪽으로 구현을 해보았습니다.

2021-10-19 07:00 UTC, yaewonLee commented on WeatherForecast/WeatherForecast/Location/LocationManager.swift
> +        workItem = DispatchWorkItem {
locationManager의 좌표를 받아오는 메서드가 간헐적으로 연달아 호출되는 경우가 있었는데 이렇게 되면 테이블뷰의 cell에 같은 값이 연달아 들어가게 되는 문제가 발생할 것 같았습니다. 연달아 오는 좌표에 대한 응답 중에 마지막 응답만 사용하면 될 것 같아서 `디바운스`라는 개념을 공부해서 적용해보았습니다 ! 
workItem?.cancel() 을 통해 앞의 호출되는 응답들을 취소하고 workItem을 재정의 해주고 DispatchQueue.global()의 asyncAfter 메소드를 통해 0.3초 동안 들어오는 응답중 마지막 응답만 실행되도록 구현해보았습니다.

2021-10-19 07:03 UTC, soo941226 commented on WeatherForecast/WeatherForecast/Network/APIEndPoint.swift
> +    static let APIKey = (name: "appid", value: "a529112a5512a01db04290ddf7b83639")
apiKey로 정정하였습니다~

2021-10-20 04:38 UTC, yaewonLee commented on WeatherForecast/WeatherForecast/ViewController/Main/MainViewTableViewCell.swift
> +class MainViewTableViewCell: UITableViewCell {
MainTableViewCell 로 변경해보았습니다!

2021-10-20 04:42 UTC, soo941226 commented
안녕하세요 쿠마!! 피드백해주신 내용을 토대로 전체적인 리팩토링을 해보았습니다.

전체적인 결과는 아래와 같습니다
1. Requestable이라고 하는 protocol을 정의한 뒤 이것을 채택하는 타입들을 정의하여 요청과 응답이 1:1로 매칭이 되도록 해보았습니다.
2. 그 외에는 말씀하신 부분들에 대해서, UI 부분을 제외하고는 전체적으로 반영을 한 거 같습니다~!

그런데 이미지 요청과 같은 경우때문에 말씀하신 것처럼 NetworkManager.request를 하나로 통합하기 어려웠는데 이에 대한 쿠마의 의견을 여쭙고 싶습니다~! 힌트를 받을 수 있을까요?

2021-10-20 20:16 UTC, leejun6694 approved these changes
리뷰 내용을 너무나 잘 반영해주셨습니다 : )
어떻게 느끼고 계실진 모르겠지만,,, 발전할 수 있는 부분이 많은 스텝이었고, 충분히 잘 진행해주신 것 같습니다.
다음 스텝에서도 같이 얘기 많이 나누면 좋겠네요!

+ 몇부분은 리뷰를 추가했습니다. 확인 부탁드려요~

2021-10-20 20:16 UTC, leejun6694 commented on WeatherForecast/WeatherForecast/Network/Parser.swift
> +
불필요한 줄바꿈이 있습니다 : )

2021-10-20 20:16 UTC, leejun6694 commented on WeatherForecast/WeatherForecast/Network/URLGenerator.swift
> +
여기도...!

2021-10-20 20:16 UTC, leejun6694 commented on WeatherForecast/WeatherForecast/ViewController/Main/MainTableViewCell.swift
> +class MainTableViewCell: UITableViewCell {
final 을 계속 추가해주었던 것 같은데, 여기는 누락되었네요~

2021-10-20 20:16 UTC, leejun6694 commented on WeatherForecast/WeatherForecast/ViewController/Main/MainTableViewCell.swift
> +    let timeLabel = UILabel()
property 의 위치 또는 접근 제어를 고려했으면 좋겠습니다ㅎㅎ

2021-10-20 20:16 UTC, leejun6694 commented on WeatherForecast/WeatherForecast/ViewController/Main/MainTableViewCell.swift
> +    private func layoutContents() {
하나의 method 가 너무 길어지고 있습니다.
조금 더 나눠볼까요?

2021-10-20 20:16 UTC, merged