날씨 정보(전) [STEP 3] Luyan
yagom-academy/ios-weather-forecast pull request #66
Opened 2021-10-18 14:39 UTC by KimWanki

비비.. @YebinKim 

안녕하세요. **비비**! ㅎㅎ

Step3 PR 보냅니다 ㅎㅎ.
이번 PR을 기한에 맞춘다고, 정말 기능에 집중해서 프로젝트를 진행한 것 같아요. 사실 좀 더 시간을 가지고 고민을 하고 싶었던 부분들도 있었는데, 일단 구현부터 하고 고민하면서, 리팩토링을 해보자 하는 생각입니다!

그래서 그런지.. 제대로 진행하지 못한 부분도 일부 있다고 생각하고, 많은 결함이 발견될 거라고 생각됩니다. 발견된 부분이 있다면, 꼭 찝어주시면 좋을 것 같아요.

### 구현 중 에러 사항 및 궁금한 점들(?)
---
1. 오토 레이아웃과 관련해서도 해결하지 못한 이슈들이 있습니다.
`stackView`에서의 `layout` 관련한 에러 발생 부분들인데, `wtfautolayout` 페이지를 이용해서 디버깅을 시도 중인데, 좀 더 수정해서 계속 반영해보도록 하고 있습니다. 어떤 제약에서 문제가 발생한 것인지 한번 봐주시면 좋을 것 같아요.

2. 애플 공식 문서를 바탕으로 `refresh control` 의 `UI`에 대한 구현은 했는데, 이벤트 발생이 제대로 이뤄지고 있지 않은 것 같아요. 내부에서`requestLocation()` 메소드를 실행해서 다시 `location`에 대한 정보를 받고, 내부 로직에서 `tableView.reloadData()`가 진행되도록 구현을 해두었는데, 어떤 부분에서 문제가 발생하는건지 한번 봐주시면 합니다. 

3. 뷰에 원하는 형식으로 데이터를 출력하기 위해 `model`의 `extension` 안에 계산 프로퍼티나, 형식 변환 메서드를 두고, `cell`이나 `header`의 `configure()` 메서드 안에서 사용했는데, 모델의 역할의 영역에서 해당 부분을 해석해도 괜찮을지 고민이 조금 되었네요(책임을 누가 가져야하는가? ~~이 부분은 사실 항상 고민을 하게 되는 것 같아요.~~ 비비의 의견이 궁금합니다.)

4. 옵셔널 해제를 위한 `flatmap`의 사용을 많이 했는데, 추가적인 변수명 설정을 하지 않고, `if let { } else `처럼 `else`에서 추가적인 작업이 요구되지 않는다 라고 생각하면 `flatmap`을 사용한 것 같아요. 하지만 일반적으로 `guard`나 `if let`을 사용했을 때보다 코드를 읽는데 가독성이 떨어질 수 있지 않을까하는 생각이 문득 들었습니다. 옵셔널 해제를 위한 `flatmap`의 사용이 잦아졌을 때, 가독성 측면에서 비비는 어떻게 생각하시는지도 궁금합니다.

---
이번 주도 즐거운 한 주 보내세요!! 🐦🐦

2021-10-19 18:28 UTC, YebinKim requested changes
루얀 안녕하세요~
Step3 완성까지 고생 많으셨습니다! 😄👏
기한에 맞춰 완성하느라 고생한 흔적이 보이는 커밋 로그였는데요..! (한 번에 너무 많은 양을 커밋한 1af1290 등)
아쉬웠던 부분은 리팩토링을 하면서 천천히 개선 진행해보아요!! 🙆‍♀️👍

우선 질문부터 답변 드려볼게요!



---

#### 1. 오토레이아웃 디버그 경고 메세지와 관련한 문제

이 문제는 저도 좀 더 고민해보고 다시 답변을 드릴게요! 🤔
현재 작성해둔 오토레이아웃 제약사항은 문제가 없는 것으로 보이는데.. 디버그 경고 메세지가 여러 개 뜨는 상황이라 좀 더 확인이 필요할 거 같아요 🙏



#### 2. refresh control 의 이벤트가 제대로 수행되지 않는 문제

이벤트 발생이 제대로 이뤄지지 않는 문제는 잘 모르겠지만..!
현재 **refresh control 과 테이블뷰가 겹치며**, **업데이트가 완료되지 않았음에도 refresh control 이 사라지는 문제**가 있는 것으로 보이는데요 🤔

<img src="https://user-images.githubusercontent.com/38066039/137968953-5cd5cde2-900c-4e0f-891a-d51ff64c7d58.PNG" width=50% height=50% />

관련해서 아래 라인별 코멘트에 남겨두었으니 확인 부탁드려요~

혹시 제가 인지한 것과 다른 문제가 있다면 다시 얘기해주세요! 함께 회의실에서 확인해봅시다 😆



#### 3. 모델 내부에서 연산 프로퍼티 / 메서드를 통해 변환 작업을 수행하는 것에 관하여

오호 저도 늘 고민하는 부분인데요 🤔
저는 개인적으로 모델이 가공 완료된 데이터(뷰에 표시할 형태로 가공된 데이터)를 가지는 것은 선호하지만,
매개변수를 통해 받은 값을 변환하는 역할을 하는 **인터페이스 메서드**는 모델이 아닌 별도의 컨트롤러가 가져야 할 책임이라는 생각이 들어요!

모델의 책임은 **화면에 표시될 데이터를 가지는 것** 이라고 봤고, 데이터를 가공하는 것은 그 외 컨트롤러 등의 역할이라고 생각했기 때문인데요.
만약 모델에서 가공이 완료된 데이터를 가지고자 했다면 인터페이스 메서드가 아닌 **내부 메서드를 통해 모델을 생성할 때 부터 가공된 값을 가지고** 있거나 **연산 프로퍼티를 통해 값을 가져올 때 가공**시키고자 했을 거 같아요 😄 (단, 이때는 원본값이 유실되거나 원본값과 가공된값을 두 벌로 가지고 있어야 한다는 문제가 있을 거에요)

즉, 현재의 `convertToCelsius(with:)` 메서드는 제가 생각하기에는 모델보다는 컨트롤러 또는 그 외 유틸 클래스의 책임에 가깝다고 생각합니다! 😊



#### 4. 옵셔널 해제를 위한 `flatMap` 과 if / guard 옵셔널 해제 방법을 비교했을 때의 가독성에 관하여

저는 개인적으로 `flatMap` 내부 블럭이 2중 이상으로 중첩되어 사용되었을 때나 축약어($0) 를 사용했을 때 한 번 더 생각하고 코드를 읽어봐야 해서 if / guard 보다는 읽는데 조금 불편하다고 느꼈는데요..!
익숙하지 않은 사용 방법이라 읽는데 불편함이 있었을 뿐 flatMap 으로 옵셔널을 해제해서 사용하는 방법이 if / guard 방법보다 더 안 좋다고는 생각하지 않습니다! 😊
다만, 루얀이 말씀하신 추가적인 작업이 요구되지 않을 때 뿐만 아니라 들여쓰기가 적은 간단한 작업에 대해서만 `flatMap` 을 사용해보는 것 또한 생각해볼 수 있을 거 같아요~



---

추가로 현재 노치가 있는 디바이스에서 **노치 영역 여백 문제**와 **여백과 statusBar 가 겹쳤을 때 statusBar 의 내용을 확인할 수 없는 문제**가 있는 것으로 보여요~

<img src="https://user-images.githubusercontent.com/38066039/137969080-8010e4c4-5022-45ad-986e-662997582d93.PNG" width=50% height=50% />

(제 집 주소가 보여서 가렸습니다 😋)

이번 스텝에서의 핵심 경험은 아래 5가지였는데요.

<img width="329" alt="Step3" src="https://user-images.githubusercontent.com/38066039/137969105-98fcf211-90ea-4722-bf4d-0b427c179329.png">

질문으로도 얘기해주셨듯 **Refresh Control 동작**에 문제가 있고 루얀이 느끼기에 아쉬웠던 부분도 **리팩토링**을 진행한 후 머지를 진행해보면 좋을 거 같아 Request Changes 로 요청 드릴게요!

혹시 설명이 필요한 코멘트가 있다면 언제든 DM 또는 깃헙 코멘트를 통해 알려주세요~ 😆🙌

2021-10-19 18:28 UTC, YebinKim commented on WeatherForecast/WeatherForecast/Entry/SceneDelegate.swift
> +        weatherViewController.view.backgroundColor = .white
스토리보드를 전혀 사용하지 않고 구현하셨군요!
`WeatherViewController` view의 배경색을 정하는 작업은 `WeatherViewController` 코드 안에서 작성해줄 수는 없었을까요? 🤔

2021-10-19 18:28 UTC, YebinKim commented on WeatherForecast/WeatherForecast/Network/URLGenerator.swift
> +    private static let iconURL = "https://openweathermap.org/img/w/"
새로운 네트워크 작업을 추가할 때 기존 네트워킹 코드를 잘 활용하셨군요! 🤩👏

2021-10-19 18:28 UTC, YebinKim commented on WeatherForecast/WeatherForecast/Scene/WeatherTableViewCell.swift
> +    func setup() {
`setUp()` 메서드는 이름만 보고 어떤 역할을 수행할지를 기대하기가 어려운 거 같아요 🤔
메서드의 내용을 유추할 수 있을만한 네이밍으로 변경해보면 어떨까요?

2021-10-19 18:28 UTC, YebinKim commented on WeatherForecast/WeatherForecast/Extensions/UIView+.swift
> +            view.translatesAutoresizingMaskIntoConstraints = false
뷰를 `addSubviews(_:)` 할 때 `translatesAutoresizingMaskIntoConstraints` 옵션을 false 로 바꾸게 되면 오토리사이징마스크를 사용하고자 했던 뷰에 대해서는 오동작이 발생할 가능성이 있어보이는데요 🤔
`addSubviews(_:)` 메서드를 수행했을 때 `translatesAutoresizingMaskIntoConstraints` 를 false 로 설정하고자 한 이유가 있을까요?

2021-10-19 18:28 UTC, YebinKim commented on WeatherForecast/WeatherForecast/Scene/WeatherViewController.swift
> +        self.view = weatherView
`view` 에 `weatherView` 를 `addSubview(_:)` 하지 않고 갈아치기 해준 이유가 무엇일까요?? 🤔

2021-10-19 18:28 UTC, YebinKim commented on WeatherForecast/WeatherForecast/Scene/WeatherViewController.swift
> +    override func viewDidLoad() {
`viewDidLoad()` 메서드 내의 코드가 모두 행간 띄움 없이 붙어있네요! 👀
관련 있는 코드끼리 행간을 띄우고, 가능하면 각 코드를 intialize~~View() 와 같이 초기화 메서드를 통해 호출하는 편이 더 가독성이 좋을 거 같은데요! 🤔
혹시 어떻게 생각하실까요?

2021-10-19 18:28 UTC, YebinKim commented on WeatherForecast/WeatherForecast/SupportingFiles/Assets.xcassets/mar.imageset/Contents.json
> +      "filename" : "mar.png",
혹시 배경파일 이미지의 이름인 "mar.png" 는 어떤 의미일까요..?
어떤 파일인지 프로젝트 안에서 검색해보고 나서야 배경 파일임을 알 수 있었어요 😅

2021-10-19 18:28 UTC, YebinKim commented on WeatherForecast/WeatherForecast/Util/ImageCache.swift
> +let imageCache = ImageCache()
ImageCache 를 활용하셨군요! 😆👍
싱글턴 등의 방식 대신 전역 변수로 `ImageCache()` 를 사용한 이유가 있을까요?

2021-10-19 18:28 UTC, YebinKim commented on WeatherForecast/WeatherForecast/Util/ImageLoader.swift
> +let imageLoader = ImageLoader(session: URLSession(configuration: .default))
`imageLoader` 또한 전역 변수로 선언되었네요! 👀
마찬가지로 전역 변수로 사용한 이유가 무엇일까요?

2021-10-19 18:28 UTC, YebinKim commented on WeatherForecast/WeatherForecast/Scene/WeatherViewController.swift
> +                                           latitude: location.coordinate.latitude)
정렬이 되지 않은 코드가 있네요! 👀
정렬이 필요한 코드를 드래그하고 `control + i` 단축키를 누르면 일괄 정렬을 수행할 수 있습니다~!

2021-10-19 18:28 UTC, YebinKim commented on WeatherForecast/WeatherForecast/Scene/WeatherViewController.swift
> +        }
`refreshControl` 의 셀렉터 메서드가 동작하자마자 `endRefreshing()` 를 호출하고 있네요! 👀
`self.locationManager.requestLocation()` 의 동작이 끝났을 때(위치 업데이트가 완료되었을 때) `endRefreshing()` 를 호출하는 게 필요해보여요 😊

2021-10-19 22:06 UTC, KimWanki commented on WeatherForecast/WeatherForecast/Entry/SceneDelegate.swift
> +        weatherViewController.view.backgroundColor = .white
헛. 이부분을 SceneDelegate 에서 해주고 있었군요. 뷰에 대한 부분은 해당 뷰에서 바꾸도록 해볼게요!

2021-10-20 04:55 UTC, KimWanki commented on WeatherForecast/WeatherForecast/Extensions/UIView+.swift
> +            view.translatesAutoresizingMaskIntoConstraints = false
뷰를 구성할 때, 오토리사이징 마스크를 사용하지 않고, 오토레이아웃만을 사용해서 뷰를 구성하고자 할때마다 계속 중복적으로 작성해줘야하는 일어나는 코드라는 생각이 들었어요! 
듣고 보니 만약 오토리사이징마스크를 사용하려고 한다면, 해당 메소드의 사용이 오동작을 만들 수 있을 것 같네요!
해당 부분 수정 반영해보겠습니다 👍

2021-10-20 06:09 UTC, KimWanki commented on WeatherForecast/WeatherForecast/Scene/WeatherTableViewCell.swift
> +    func setup() {
해당 부분 수정 반영하였습니다 👍 👍 👍

2021-10-20 06:10 UTC, KimWanki commented on WeatherForecast/WeatherForecast/Scene/WeatherViewController.swift
> +    override func viewDidLoad() {
지금 코드에서는 어떤 라인이 어떤 역할을 하는지 정확히 구분이 안되고 있네요!
해당 부분 각각 기능에 맞춰 메소드로 변경해보겠습니다 :)

2021-10-20 06:12 UTC, KimWanki commented on WeatherForecast/WeatherForecast/SupportingFiles/Assets.xcassets/mar.imageset/Contents.json
> +      "filename" : "mar.png",
배경파일의 이미지 이름도 무엇을 말하는지 제대로 파악이 어려워서 가독성을 해칠 수 있는 요소가 될 수 있을 것 같네요!
현재는 이미지 파일이 하나지만, 이미지 파일이 많아질 경우, 네임스페이스를 만들어서 관리해도 좋을 것 같다는 생각도 듭니다!

2021-10-20 07:25 UTC, KimWanki commented on WeatherForecast/WeatherForecast/Scene/WeatherViewController.swift
> +        self.view = weatherView
`view`를 그리는 부분에 대한 것을 `weatherView` 내부에 다 작성해주려고 했습니다.
`weatherView`라는 인스턴스가 subVi`e`w들 전체 컨테이너 역할을 하고 있어서 `weatherView`가 `weatherViewController`의 `view`를 대체할 수 있겠다고 판단했는데, `view`를 바꿔주는 이 방식이 아닌 `addSubview`를 사용했을 경우, 뷰를 한 층 더 쌓는다는 생각이 들었어요. 
그런데 위에서 말씀하신, `status bar`과 겹치는 부분에 대한 레이아웃 문제가 `addSubview`를 사용했을 경우 해결되는군요.. (~~허허~~) 아직 이유를 찾지는 못했습니다ㅠ 
아예 뷰 컨트롤러가 가리키는 뷰를 바꾸는 방법은 지양되어야 할까요?

2021-10-20 07:42 UTC, KimWanki commented on WeatherForecast/WeatherForecast/Util/ImageCache.swift
> +let imageCache = ImageCache()
질문에 대해서 고민해보면서 전역 변수와 싱글톤 패턴에 대해서 인터넷을 좀 검색해보았는데 전역 변수의 대체를 위한 클래스로 싱글톤 패턴을 사용하는 패턴을 많이 볼 수 있었는데요!😀 현재 구현한 어플의 기능을 봤을 때, 자원이 지속적으로 사용되는 뷰만 존재한다고 생각했고, 해당 뷰에서 자원에 대한 해제가 요구되지 않아서 싱글톤 패턴이 전역 변수의 단점을 보완하는 역할을 하기 어렵다는 판단이 들어 전역 변수로 선언해 사용했습니다. 전역에서 접근을 허용하려고 할때, 싱글톤 패턴 외 다른 방법들도 있을까요?

2021-10-20 07:54 UTC, KimWanki commented on WeatherForecast/WeatherForecast/Util/ImageLoader.swift
> +let imageLoader = ImageLoader(session: URLSession(configuration: .default))
위에 코멘트 남겼습니다!!

2021-10-20 07:54 UTC, KimWanki commented on WeatherForecast/WeatherForecast/Scene/WeatherViewController.swift
> +                                           latitude: location.coordinate.latitude)
:) :) 👍

2021-10-20 17:32 UTC, YebinKim commented on WeatherForecast/WeatherForecast/Scene/WeatherViewController.swift
> +        self.view = weatherView
오호 네네! 뷰를 한층 더 쌓지 않기 위해 이렇게 작성해볼 수 있겠네요.

저는 self.view 와 weatherView 가 현재 같은 인스턴스에 접근할 수 있게 되었다는 점과
[view](https://developer.apple.com/documentation/uikit/uiviewcontroller/1621460-view) 는 UIViewController 가 관리하는 뷰로서 그 역할이 다르다고 생각해 가능하면 커스텀 없이 사용하고자 하는 편이어서 코멘트 드렸어요~

애플에서 공식적으로 이를 지양하고 있진 않은 거 같네요 🤔

2021-10-20 17:45 UTC, YebinKim requested changes
루얀 안녕하세요~
Step3 수정 고생 많으셨습니다! 😆👏
요청드렸던 Refresh Control 동작 및 리팩토링 진행된 건은 확인했어요!

그런데 최신 커밋을 빌드했을 때 아직 **노치 영역까지 배경화면이 적용되지 않고 statusBar 의 내용을 확인할 수 없는 문제** 가 남아있는 것으로 보이는데요..!
이 부분 한 번만 더 확인 부탁드려요 😊

<img width="320" src="https://user-images.githubusercontent.com/38066039/138144288-da62b8cd-ebca-4163-8a56-95309551279b.PNG">

화면 수정만 확인되면 이번 스텝에서의 핵심 경험은 모두 충족되었다고 생각해서 바로 머지 진행할게요~

그 외의 수정사항을 더 반영했으면 하거나 설명이 필요한 코멘트가 있다면 말씀해주세요~ 👀👂

2021-10-20 17:45 UTC, YebinKim commented on WeatherForecast/WeatherForecast/Scene/Protocol/ViewConfiguration.swift
> +protocol ViewConfiguration {
뷰의 기본 세팅을 프로토콜로 일관화시켰군요! 👀👍

2021-10-21 00:55 UTC, KimWanki commented
|수정(전)|수정(후)|
|---|---|
|<img width="435" alt="image" src="https://user-images.githubusercontent.com/57824307/138190122-2dc45cb1-6129-40cc-93cc-786e9aa8975b.png">|<img width="437" alt="image" src="https://user-images.githubusercontent.com/57824307/138190227-6a862eab-ebff-4ad2-99d4-73815a03ab2e.png">|

비비!
최종 PR 빌드했을 때(수정(전)) 배경화면까지 일치하도록 수정을 해보았는데요!
(사실 constraint 코드에서 safeAreaLayoutGuide를 제거한게 전부입니다..!)
최종 수정된 PR에서 status bar가 혹시 안보이는 문제가 발생했을까요? ㅠㅠ 

제가 topAnchor을 safeAreaLayoutGuide에 제약을 걸어줬던 부분은 하단처럼 statusbar과 tableview의 contents들이 겹쳐진다는 생각이 들어서 였는데, 말씀해주신 것처럼 노치까지 배경화면을 두는게 좀더 자연스러운 화면 구성 방식일까요?? ( 제가 노치를 안써서.. 노치와 관련된 UX 가 없습니다ㅋㅋ)
|수정(전)|수정(후)|
|---|---|
|<img src="https://user-images.githubusercontent.com/57824307/138190929-c7c7d510-9cfa-4d9f-b09b-4ec876d04a87.png" width="350" height="800">|<img src="https://user-images.githubusercontent.com/57824307/138190770-cbc14ace-8903-42df-b875-2832a43bcdc9.png" width="350" height="800">|


(12pro 시뮬레이터 기준으로 반영한 이미지입니다!)

2021-10-21 03:53 UTC, YebinKim commented
루얀 안녕하세요~
코멘트 반영 고맙습니다!

1차 수정 버전에서 statusBar 가 잘 보이고 있음에도 제가 코멘트를 잘못 썼네요 😅
이 부분 사진과 함께 상세히 설명해주셔서 고맙습니다 🙏
코멘트로 혼동을 드린 점도 죄송해요 🙇‍♀️

DM에서 얘기 나눈대로 배경화면이 노치 영역까지 적용된 모습이 가독성을 해치지 않으며 보기에도 더 예쁘다고 판단되어 이대로 머지 진행할게요~
다음 스텝 진행도 화이팅입니다! 😆👏

2021-10-21 03:53 UTC, merged