날씨 정보 (후) [STEP 1] Marco
yagom-academy/ios-weather-forecast pull request #67
Opened 2021-10-18 16:20 UTC by Marcorable

@GREENOVER

@Keeplo

안녕하세요 그린 😂

저번 PR에서 말씀해주신 브랜치는... 제가 아무 생각없이... 진행해버린 실수 였습니다 ㅠㅠ;;
이번엔 머지 시점에서 구분상 step 4 브런치로 새로 파서 진행해보았습니다....

생각보다 쉬울줄 알았는데.. 
제가 짠 로직에 제가 걸려 넘어지는 고난을 좀 겪고.. 
이번 스텝에서 조언을 구하고 싶은 부분도 있고 PR을 통해 너무나 많은 걸 그린 덕분에 배워가고 있어서,,,
빠르게 PR을 남겨봅니다..
### 고민했던점 🤔
* 최초 Location 읽어오기와 실패시 얼럿 구현
이번 프로젝트 동작 관련해서 
![image](https://user-images.githubusercontent.com/24707229/137765373-d605d32d-033e-48e6-8cc0-75216c0b5d8d.png)
![image](https://user-images.githubusercontent.com/24707229/137765441-c89f4c5b-009e-4fdb-88ef-7e9950657a04.png)
위 사진과 같은 형태로 이미 Location 읽어온 상태에서 변경(1)과 최초 위치 읽어오기 실패일때 변경(2)이 
다른 Alert을 띄워주고 다른 처리를 하는 형태로 구현하게 되었습니다.
현재 위치를 저장하는 프로퍼티를 만들고 비어있다면 요청하고 요청해서 읽어오지 못한다면 (2)
읽어 왔다면 현재위치를 저장하고 (1) 
형태로 구현해서 나누어 보았습니다.

### 피드백 받고 싶은 부분 😹
* Delegate를 통한 ViewModel과 ViewController 간의 통신
이미 ViewModel을 프로퍼티로 가지고 있는 ViewController을 다시 ViewModel에 위임하는 형태로
어쩌면 순환 적인 관계처럼 보이는 형태의 구현을 하게 되었습니다.
ViewModel에 currentLocation 과 같은 데이터를 두도록 해보다 보니
ViewController에서 분기를 나눌만한 것도 ViewModel에서 진행하도록 구현하게 되고 그러다보니 이런 형태가 작성되었습니다.
보시기에 위험성이 있는 부분이나, 잘못된 부분은 없는지 또는 그린의 생각은 어떤지 궁금합니다..

* Alert 구현
여태 캠프를 진행해오면서 Alert을 여러번 마주칠 기회가 있었는데 
항상 큰 리팩토링이나 좋은 아이디어를 구상해보지 못하고 매번 하나씩 모두 작성하는 형태로만
 구현을 해왔습니다.. 이번에도 두 동작에서 다른 부분만 나눠주는 수준에 메서드 분리정도만 진행해보았는데...
혹시 Alert 구성에도... 좋은 팁이 있을지 궁금합니다...

### 해결하지 못한 부분 🤯
* AutoLayout 구현...
이전 스텝에서 기능상세와 달리 HeaderView의 이미지 영역이 없었다가 업데이트 될때 이미지가 채워지며 정상적인 구동을 하는 듯 보였으나,
<img width="419" alt="image" src="https://user-images.githubusercontent.com/24707229/137769220-2b820543-06ae-4ba9-8213-6cfe04e6a73e.png">

그 증상 또한 제가 AutoLayout을 잘 처리하지 못한 문제로 이번 스텝에서 터진것 같습니다..
HeaderView의 CGRect를 지정해서 TableView 크기를 전달해도 제 예상대로 동작하지 않고..
다른 시점에서 HeaderView에 제약을 주면.. 정상적으로 동작하지 않고..  
다양한 실험에서 답을 얻지 못하고... 원인을 파악하지 못하며 해결하지 못했습니다.

동작은 기능상세의 기대대로 구현되어서 보내는 이번 PR이 조금 더 고민해보지 않고 PR을 날린 결과가 되겠지만...
다음 스텝이 목적이라기 보다 그린의 피드백을 받고 다른 부분을 고민하면서도 계속 시도해보고 고민해보겠다는 의미로 ...
해결되지 못했지만 PR을 보내봅니다...
혹...시나 제가 놓치는 부분이 있다면... 조언도 부탁드려요 ㅠ;;
1. UIButton의 기본 Layer와 내부 Title Label의 Layer가 다른 경우
<img width="1310" alt="image" src="https://user-images.githubusercontent.com/24707229/137769605-64722fc0-ace2-4b73-a9fa-cd2af055ac7e.png">
2. 헤더뷰의 leading과 trailing을 가득 채워줄거라 생각한 스택 뷰가 채워지지 않는 경우
<img width="1215" alt="image" src="https://user-images.githubusercontent.com/24707229/137769751-b5bb476e-9c44-472e-bb44-74cf37e425d4.png">
이 경우는 스택 뷰나 Headerview 자체에 제약을 줘보았는데 해결이 안된 상황입니다 ㅠㅠ;;

---

PR을 너무 과제 제출처럼 생각하지 않으려고 하다보니...
완벽하지 않지만.. 어느정도 기능 구현이 되었을 때 바로 PR을 보내게 되었습니다.
가볍게 지나칠 만한 것도 가볍게 말씀해주시면 무겁게 고민해보겠습니다 ㅠㅠ
이번 리뷰도 잘 부탁드립니다!!

ps. 조언해주신 dateFormatter 부분이 너무나 알려주신 대로 적용이 되었는데...
저도 최대한 쉽게 얻어가려 하기보다 고민 더 해보려고 노력하려고 하는데.. 
보여주셨던 그린 아이디어가 너무...;;; 좋아서 그대로 적용할 수 밖에 없었습니다...
조금 변명해보자면 Double 부분을 조사해보다가 extension으로 소수점 한자리 변환하는 걸 추가해보았는데
비슷한 형태인걸 인지해서 ... 습득했습니다 ㅎㅎ;;; 감사합니다!

2021-10-19 01:10 UTC, GREENOVER commented
@Keeplo 
이번 스텝도 빠르게 보내주셨네요!
고생하셨습니다 말꼬 ㅎㅎ
다만 한가지 걱정되는 부분이 있어요..!
제 PR을 반영해주는건 좋은데 너무 그거에 치우쳐서 생각해보는 시간이 적은가 걱정이됩니다.
그 본질적인 이유가 기한을 맞추기 위해 타이트한 일정 산출이였나 싶어요.
그래서 다음 스텝은 조금 더 기한보다는 충분히 삽질해보는 시간을 가져보는게 좋을것 같습니다!
뭔가 제 PR 코멘트들을 학습하시느라 충분한 탐구의 기회를 놓쳐버리는것 같아서 걱정이였습니다😅
그런다면 하루 늘어나더라도 충분히 지금 말꼬가 이번 PR에서 해결하지 못한 부분을 해결 할 수 있을것 같아 보여서 조심스럽게 말씀드립니다😅
그래도 이번 이전 스텝에서 수정사항들 충분히 반영된것과 이번 스텝에서 필수로 해야할 구현사항들 다 정상적으로 작동하는것 확인하였습니다👍
항상 스텝의 기한이 촉박한데 완성도 높게 구현해주시는점 최고에요!!

## 칭찬드리고 싶은 부분
- 짧은 기한에도 멋지게 완성해내셨네요! 일정 관리도 아주아주 중요한 부분입니다 💯
- 프로토콜 사용 능력 💯
- 스텝이 지날수록 코드 분리가 잘 이루어지고 있습니다! 💯

## 고민하셨던 부분에 대한 저의 의견
- 이 부분도 얼럿 구현을 공통적으로 빼시고 상황에 맞게 활용하신점 최곤데요!?
지금 말꼬가 구현하신 방향이 충분한 고민을 통해 좋은 결과물을 산출했다고 생각합니다ㅎㅎ

## 피드백 요청에 대한 저의 의견
- Delegate를 통한 ViewModel과 ViewController 간의 통신에 대해서 피드백을 드리자면 말꼬가 구현한 방향이 괜찮다고 생각합니다.
뷰모델에서 처리하고 VC가 어떻게 보면 뷰라고 볼 수 있으니 뷰는 정말 표현만 해줄때 사용하면 될거라봐요.
그러니 뷰에서는 로직적인 부분이 없이 뷰모델에서 처리 후 뷰모델을 받아와 업데이트 쳐주는 방식이 나은 방향일것 같아요.
그럼으로 지금 구조에서 딱히 문제가 되는 지점은 크게 없어보입니다.
다만, 얼럿을 띄워주는것도 VC에서 해줘야할지 빼서 버튼 클릭에 대한 액션 데이터를 다른쪽에서 받아 처리해줘야할지 고민해보면 좋을것 같습니다!
- Alert 구현에 대해 의견을 드리자면 지금 말꼬가 공통적으로 메서드로 잘 분리해주었다 생각합니다.
그러나 조금 더 개선시켜보자면 리뷰 코멘트에도 조금 언급했지만 메서드로만의 분리가 아닌 모듈로 따로 만들면 좋을것 같습니다.
이후 메인VC말고 다른쪽에서도 쓰인다면 지금의 코드는 분명 리팩토링 되거나 중복될거라 생각해요.
이참에 다양한 공통적으로 사용되는 부분들의 모듈화를 학습해보고 적용해본다면 더 유연한 코드가 될거라 생각합니다!

## 해결하지 못한 부분에 대한 저의 의견
- 현재 헤더뷰안에 이미지/날씨정보스택뷰/위치변경버튼 이렇게 3개가 스택뷰로 구성되어 있는것은 확인했어요!!
다만 지금 원하시는 UI가 안나오는 이유는 우선 2가지가 될 수 있을것 같아요.
1. 헤더뷰에안 스택뷰는 제약조건을 주었지만 헤더뷰 자체에서는 제약이 없어보입니다.
아래 제가 뷰디버깅을 하면서 제약조건을 확인해보는데 보시면 헤더뷰에서 제약조건이 없어 모호한 레이아웃의 메시지를 볼 수 있습니다.
![스크린샷 2021-10-19 오전 9 19 14](https://user-images.githubusercontent.com/72292617/137825300-a4dad3a8-0ea6-47b8-bdfb-a9c7881ee497.png)
![스크린샷 2021-10-19 오전 9 19 28](https://user-images.githubusercontent.com/72292617/137825311-db268d51-8514-4a87-9a34-e50e134b504f.png)
그래서 헤더뷰의 제약을 걸어주면 지금 헤더뷰의 넓이가 꽉 맞지 않게 나오는 현상을 해결할 수 있을거라 봅니다.
(말꼬가 첨부해준 2번 헤더뷰 사진에서도 보라색 경고 아이콘을 볼 수 있네요!)
2. 1번 답변과 유사한 맥락이라 보이는데 지금 헤더뷰내 스텍뷰 자체는 헤더뷰의 leading과 trailing에 맞춰 꽉 차 있습니다.
문제는 헤더뷰가 현재 제약이 없어 화면 넓이에 꽉 차 보이지 않는 부분인것 같습니다.
이를 위의 1번에 답변 드린 방향으로 생각해보시면 해결될거라 보입니다.
추가적으로, 현재 위치변경 버튼과 날씨정보(지역/기온등)가 스택뷰로 같이 감싸져 있는데 이렇게 사용하시려면 제 생각에는 사이에 빈 뷰가 들어가도 될것 같습니다.
이유는 만약 넓이만큼 헤더뷰를 꽉 차게 구성한다면 위치변경 버튼과 날씨정보뷰 사이 제약을 걸어줘야될거에요. 그래야 위치정보 버튼이 오른쪽에 붙게 나올것 같습니다.
이를 위한 방법은 다양한데 제가 방금 말씀드린 빈뷰를 넣어 줄수도 있고 날씨정보뷰와 제약을 걸어줄수도 있고,
아니면 아예 스택뷰에서 위치정보 버튼을 빼버리고 스택뷰와 위치정보뷰 사이에 제약을 걸어줄 수도 있겠어요!
저라면 왠지 마지막 방법으로 구현해봤을것 같습니다🧐

## 궁금한 부분
- 앱에서 `현재위치로 재설정` 버튼을 누르면 현재 위치 정보로 데이터를 받아오는 동작을 하지 않고
기존 가장 최신의 위치로 계속 남아있어 업데이트가 안되는것 같은데 저만 그런건지..!? 아님 제가 어떤 부분을 놓친건지 궁금합니다🧐
말꼬의 테스트에서 정상이라면 기능 동작하는 gif을 첨부해주시면 감사하겠습니다🙏🏻

이번에는 말꼬가 조금 더 고민해볼 수 있도록 포인트들만 짚어드려봤어요..!
혹시 좀 더 자세한 피드백이 필요하다면 말씀해주세요😄
궁금한 부분의 코멘트에서 동작하지 않아 보이는 기능이 있는것 같아서 리퀘스트 체인지로 드리고 제가 잘못 테스트했거나 기능에 대해 정상인걸 확인하면 머지하는 방향으로 진행하겠습니다☺️
저도 리뷰어가 처음이라 서툴러도 넓은 아량으로 이해해주시면 감사하겠습니다🙇🏻

2021-10-19 01:12 UTC, GREENOVER requested changes

2021-10-19 01:12 UTC, GREENOVER commented on WeatherForecast/WeatherForecast/Controller/MainWeatherTableViewController.swift
> +        refreshControl.tintColor = .green
ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ헉..!감사합니다...🤩🟢
다만 추후에 포폴로 사용하시고 이걸 상용하는 앱으로 본다면 크게 무리는 없지만 다른앱에서 인디케이터가 어느색상을 가장 많이 차용하는지?를 보고 적용해도 좋을것 같아요ㅎㅎ
HIG에 나와있을수도..?

2021-10-19 01:12 UTC, GREENOVER commented on WeatherForecast/WeatherForecast/Controller/MainWeatherTableViewController.swift
> +    @objc private func pressChangeButton() {
네이밍에서 궁금한점이 있습니다🙋🏻‍♂️
버튼을 누르는 동작을 나타날때 `press` `touch` `tap`등 다양하게 존재할텐데 `press`로 네이밍한 이유가 궁금합니다🙌
그리고 어떤 버튼을 누르는지 명확하지 않은것 같아서 만약 버튼이 여러개면 나중에 리팩토링해야될것 같아요.
지금의 네이밍을 따른다면 `pressChangeLocationButton`과 같은 네이밍은 어떨까요?

2021-10-19 01:12 UTC, GREENOVER commented on WeatherForecast/WeatherForecast/Controller/MainWeatherTableViewController.swift
> +        let formattedDate = intervalWeatherData.date.dateFormatString()
잘 반영해주셨네요!
한결 가독과 코드 분리가 잘 이루어졌습니다👍🏻

2021-10-19 01:12 UTC, GREENOVER commented on WeatherForecast/WeatherForecast/Controller/MainWeatherTableViewController.swift
> +        presentChangedLocation(title: "위치 변경", message: "변경할 좌표를 선택해주세요", optional: "현재 위치로 재설정")
얼럿이 나타나는걸로 생각하는데 좀 더 구체적인 `presentChangedLocationAlert`의 네이밍은 어떨까요?
여기서도 흔히 나타나는걸 사용할때 `present`와 `display`를 사용하곤 하는데 `present`로 나타내신 이유도 궁금해요!
저도 이런 네이밍들의 워딩을 뭘 선택해야할지 항상 고민인데 그건 정말 시니어가 되어도 쉽지 않은 부분들인것 같더라구요.
그래서 오픈소스들을 시간날때 많이 보면서 통상적으로 어떤 네이밍을 짓는다 보는게 정말 좋더라구요.
Swift 네이밍 가이드는 한계가 있기때문에..
추천합니다👍🏻

2021-10-19 01:12 UTC, GREENOVER commented on WeatherForecast/WeatherForecast/Controller/MainWeatherTableViewController.swift
> +    private func presentChangedLocation(title: String, message: String, optional: String?) {
오호 이렇게 공통된 얼럿 구현에 대해 로직으로 뺀점 좋습니다👍🏻
혹시 추후에 이 로직이 MaintWeatherTableVC가 아닌 다양한 부분에서도 쓰일 수 있을것 같은데,
별도 모듈로 빼서 주입받아서 사용하면 어떨까요?

2021-10-19 01:12 UTC, GREENOVER commented on WeatherForecast/WeatherForecast/Controller/Requirable.swift
> +protocol Requirable: NSObject {
크 역시 프로토콜 장인이시네요!

2021-10-19 01:12 UTC, GREENOVER commented on WeatherForecast/WeatherForecast/View/MainTableViewHeaderView.swift
> +    private let changeLocationButton: UIButton = {
위에서 언급한 부분이 요 버튼 부분이였네요..!
추후 다양한 버튼을 고려해 네이밍만 변경되면 좋을것 같습니다!

2021-10-19 01:12 UTC, GREENOVER commented on WeatherForecast/WeatherForecast/View/MainTableViewHeaderView.swift
> +        changeLocationButton.addTarget(target, action: action, for: .touchUpInside)
여기서는 버튼을 누르는 액션을 touchUpInside라고 터치의 네이밍으로 가져가네요! 'touch' 'tap' 'press'의 차이가 무엇일까요~? 그에 따른 적절한 네이밍이면 금상첨화!

2021-10-21 14:13 UTC, Keeplo commented on WeatherForecast/WeatherForecast/View/MainTableViewHeaderView.swift
> +        changeLocationButton.addTarget(target, action: action, for: .touchUpInside)
위 메서드의 이름에서는 `.touchUpInside`에 대한 설명이 없다보니 해당 설정을 주입하는 형태로 변경해보았습니다.

2021-10-21 14:13 UTC, Keeplo commented on WeatherForecast/WeatherForecast/Controller/MainWeatherTableViewController.swift
> +    private func presentChangedLocation(title: String, message: String, optional: String?) {
모듈에 관해서 고민하고 다른 캠퍼(의존모둠) 분들과 함께 고민을 해보다가
상속으로 새로운 모듈은 만드는게 꼭 좋은 방향이 아니라는 (불필요한 기능까지 상속받는 부분도 있어서) 정보도 있고 
[링크](https://medium.com/a-developer-in-making/uialertcontroller-in-swift-and-how-to-use-them-in-extension-or-in-custom-class-2d8dcf9cb292) 이런 블로그를 공유 받고 한번 읽어보고 고민해서

저의 코드에서 현재는 TableViewController를 기반으로 동작하지만 추가적인 화면 구성이 있더라도 
앱에서 가장 크게 사용되는 위치 관련 정보는 다양한 곳에서 사용될거라고 생각했습니다.
어떤 UIViewController의 형태여도 해당 Alert은 근본적인 데이터 변경에 필요한 Alert일거라 생각해서
UIViewController에 extenstion으로 주입해보았습니다..

좀 더 범용적 인걸 고민해보았는데. 결과적으로 제가 만든 함수나 모듈을 사용하기 전에 준비작업이 생기면
최초에 alertController 할당부터 present까지 동작 만큼 매번 생기기때문에 그다지 경제적이거나 좋은 방향은 아니라고 생각해서
ChangeLocation에 초점을 잡은 메서드를 만들어보는 것까지만 진행을 해보았습니다.

2021-10-21 14:13 UTC, Keeplo commented on WeatherForecast/WeatherForecast/Controller/MainWeatherTableViewController.swift
> +        presentChangedLocation(title: "위치 변경", message: "변경할 좌표를 선택해주세요", optional: "현재 위치로 재설정")
이 부분에서도 고민을 하고 조사했을때 UIViewController 문서에서 
<img width="981" alt="image" src="https://user-images.githubusercontent.com/24707229/138284299-1e8cbb4f-414a-45e8-9793-f7ee6c0df74b.png">
이런 부분도 있고 display는 좀더 렌더링되는 그래픽관련한 부분에서 더 쓰이는 듯한?? 몇몇 코드를 보아서... 
present 동사를 사용해 보았습니다.. 다른의미로 해당 메서드는 생성한 UIAlertController를 
해당 VC에 present하는 동작을 하기 때문에 이런 네이밍을 사용해보았습니다..

2021-10-21 14:14 UTC, Keeplo commented on WeatherForecast/WeatherForecast/Controller/MainWeatherTableViewController.swift
> +    @objc private func pressChangeButton() {
<img width="125" alt="image" src="https://user-images.githubusercontent.com/24707229/138295866-273127c6-434c-4ef2-8158-413fda34b711.png">
이 문장을 근거로 Tap이란 용어를 사용하면 기본적으로 UIButton을 동작하는 사용자 입력을 대표한다고 생각해서 변경해보았습니다.
그린이 언급해주신 좀 더 명확한 의미의 버튼 이름은 그린의 의견에 너무나 동의합니다... 

단어에 대해 조금 고민해보았습니다..

[Touches, Presses, and Gesture](https://developer.apple.com/documentation/uikit/touches_presses_and_gestures) 문서 처럼 근본적으로 사용자의 입력을 Touch와 Press 라는 용어를 사용한다고 인식했습니다.
<img width="185" alt="Screen Shot 2021-10-21 at 10 56 04 PM" src="https://user-images.githubusercontent.com/24707229/138292627-2fc85b01-ef80-46f5-9fa6-d0352f48d719.png">
위 사진처럼 사용자의 입력을 구분하기도 하는데 
전반적으로 사용자의 입력의 종류는 touch ...  이름으로 다양하게 표현하고,
단순히 버튼을 클릭하는 듯한 동작 (UILable, UITableViewCell 등)에 해당되는 표현으로 tap을 사용하고,
3D Touch 같이 force 프로퍼티등을 가진 [UIPress](https://developer.apple.com/documentation/uikit/uipress) 관련 자료까지 보게 되었습니다...

2021-10-21 14:20 UTC, GREENOVER commented on WeatherForecast/WeatherForecast/Controller/MainWeatherTableViewController.swift
> +    @objc private func pressChangeButton() {
최고네요!👍🏻
잘 찾아보신것 같아요..!
하나 추가로 붙이자면 touch하고 tap이 실제적으로 기능에서 어떤 미묘한 차이가 있는지 보면 좋을것 같습니다ㅎㅎ
Tap Gesture Recognize하고 touchesBegan이 어떤차이인지
의도치않게 사용자가 터치를 일으킨걸 인식하는지 안하는지 그런 차이가 있는걸로 기억해요!

2021-10-22 12:26 UTC, GREENOVER commented
@Keeplo 
말꼬 수정된 부분 확인하였습니다!!
4주간 너무 고생많으셨고 더 애플스러워졌다고 보입니다ㅎㅎ
이번 플젝도 성공적이라 저는 생각해요!
그동안 제 리뷰를 긍정적으로 봐주셔서 고맙습니다.
다음 프로젝트도 화이팅입니다ㅎㅎ

2021-10-22 12:26 UTC, merged