날씨 정보(후) [STEP 1] 건, 조이
yagom-academy/ios-weather-forecast pull request #68
Opened 2021-10-18 16:51 UTC by joey-ful

@lina0322 
엘림 안녕하세요!!
PR 피드백을 받자마자 ㅋㅋㅋㅋ PR을 날립니다
지난 PR은 말씀해주신대로 다음번 스텝에서 잘 반영해보겠습니다!
일부는 이번에 반영했어요 ㅎㅎ

컬렉션뷰의 헤더가 올라가지 않는 부분은 List Appearance를 plain에서 insetGrouped로 변경해 해결하였습니다 🥳

## 고민/궁금증
### 1. UIAlertController 생성 메서드 로직 중복
현재 UIAlertController의 extension 알럿을 생성하는 메서드를 두 개 구현했습니다.
하나는 주소가 있을 때의 알럿이고 하나는 주소가 없을 때의 알럿입니다.
- 주소가 있을 때는 "위치설정" 알럿 (버튼 라벨이 위치설정)
![image](https://user-images.githubusercontent.com/52592748/137766106-bbe6b454-7c62-43c2-b4ac-f7c14fd9f9e5.png)
- 주소가 없을 때는 "위치변경" 알럿 (버튼 라벨이 위치변경)
![image](https://user-images.githubusercontent.com/52592748/137766142-6cd92dc1-eac3-4fcc-a9ee-69a99d0433cb.png)

근데 두 알럿이 매우 흡사하게 생겨 로직이 많이 중복됨에도 어쩔 수 없이 별개의 메서드로 구현했습니다.
액션의 개수 및 액션이 추가되는 순서가 다릅니다.
매개변수로 어떤 알럿인지에 따라 분기처리를 할까 했는데 오히려 가독성이 떨어지는 것 같아 분리했는데
혹시 이렇게 해도 괜찮은지 아니면 더 좋은 방법은 없을지 궁금합니다. 😫 🤯

PR리뷰 강행군 때문에 고생 많으십니다 ㅋㅋ쿠ㅜ
감사합니다 🙏

2021-10-20 13:29 UTC, lina0322 requested changes
조이~ 건~ 하루만에 리뷰를 달게되었네요ㅎㅎ
지난번 리뷰에 달았던 것들 중에 아직 반영되지 않은 것들이 조금 있어요!
제가 이번에는 조금만 리뷰를 달아보았으니, 앞서 했던 리뷰들도 함께 정리하고 이번 스텝 마무리해볼까요?
앞에 PR에는 남기지말고, 여기다가 남겨주면 오히려 더 편할거같아요:)

그리고 저는 개인적으로 두 alert창이 전혀 다른 일을 하고있기 때문에
지금과 같이 나눈것이 더 좋습니다! 
이것은 개인의 취향도 있겠네요:)

이번에도 고생하셨고, 체크 다 끝나면 다시 한 번 호출해주세욥😚

2021-10-20 13:29 UTC, lina0322 commented on WeatherForecast/WeatherForecast/Extension/UIAlertController+Extension.swift
> +        let changeAction = UIAlertAction(title: "변경", style: .default) {_ in
뒤에 띄어쓰기!

2021-10-20 13:29 UTC, lina0322 commented on WeatherForecast/WeatherForecast/Extension/UIAlertController+Extension.swift
> +        let changeAction = UIAlertAction(title: "변경", style: .default) {_ in
UIAlertAction의 style에는 어떤게 있고, 어떻게 다르게 생겼나요😀

2021-10-20 13:29 UTC, lina0322 commented on WeatherForecast/WeatherForecast/Extension/UIAlertController+Extension.swift
> +    static func makeValidLocationAlert(
extension으로 구현한 이유가 있을까요?😄

2021-10-20 13:29 UTC, lina0322 commented on WeatherForecast/WeatherForecast/Extension/UIAlertController+Extension.swift
> +        let alert = UIAlertController(title: "위치변경",
플레이스 홀더처럼 이 스트링들도 어딘가에 저장되면 좋겠네요:)
따로 만들어도 좋고, 플레이스 홀더를 포함해 이런 문자열들을 함께 담을 수 있게 더 큰 범위로 새로 만들어도 좋고요!

2021-10-20 13:29 UTC, lina0322 commented on WeatherForecast/WeatherForecast/Extension/UILabel+Extension.swift
> +import UIKit
두개가 모두 필요한가요?😃

2021-10-20 13:29 UTC, lina0322 commented on WeatherForecast/WeatherForecast/WeatherForecastViewController.swift
> +    private let downloadDataGroup = DispatchGroup()
lazy 키워드를 선택하는 것과 선택하지 않는것의 기준은 무엇으로 하였나요?

2021-10-20 13:29 UTC, lina0322 commented on WeatherForecast/WeatherForecast/WeatherForecastViewController.swift
> +                downloadDataGroup.leave()
dispatchGroup을 사용해보셨군요!
enter와 leave는 어떤 식으로 동작하나요? 세마포어도 있었을텐데 둘의 차이는 무엇이 있을까요?

2021-10-20 23:37 UTC, joey-ful commented
@lina0322 
### (전)Step3 피드백에 대한 커멘트
지난번에 커멘트를 달지 못해 이곳에 한번에 정리했습니다🔥

#### extension에서의 init()구현
extension에서 struct의 커스텀 init()을 구현하면 멤버와이즈 init()도 사용할 수 있어 굳이 멤버와이즈 init()까지 선언해줄 필요가 없는 것을 확인했습니다!
- 다음과 같이 extension에서 커스텀 init()을 선언하도록 했고 멤버와이즈 init()의 선언은 제거했습니다 🙏
```swift
struct Address {
    let city: String
    let stree1: String
    
    var combined: String {
        return [self.city, self.stree1].joined(separator: " ")
    }
}

extension Address {
    init() {
        self.city = ""
        self.stree1 = ""
    }
}
```

#### hashable
- 자료를 키-값으로 저장하여 키를 넣어주면 해당하는 값을 반환하는 것을 해시 테이블이라고 이해했습니다. 
  - 자료는 실제로 해시 테이블에 저장되는데 키를 넣어야 해시테이블에 저장된 값의 주소를 알 수 있고 최종적으로 값을 받아올 수 있는 것이라 생각했습니다. 
  - 그리고 이렇게 키를 받아 해시테이블의 값을 반환하는 역할을 하는 것이 hasher라고 이해했습니다. 
- 그리고 같은 키를 넣으면 같은 값을 반환해야하고 특정 키를 넣으면 항상 해당하는 값을 반환받아야합니다. 이처럼 키끼리 구분이 가능해야해서 Hashable은 Equatable을 채택하고 있고 그 때문에 `==` 연산자로 키가 같은 상황을 정의해주었습니다.

#### UIKit, Foundation

말씀하신대로 UIImage만 import하기 위해 UIKit.UIImage를 import 해보았습니다!
Foundation은 기본 데이터 타입이랑 각종 계산과 네트워킹을 지원한다고 알고있습니다. 

#### URLCache
- 메모리 크기는 참고한 예제들에서 흔히 보이는 512 메가바이트로 키워주었습니다.
- URLSessionConfiguration은 URLSession에서 데이터 데이터를 업로드하거나 다운로드할 때의 설정을 의미하며 캐싱 policy나 여러 요구사항 등을 설정할 수 있습니다. shared는 싱글턴으로 기본적인 요청을 수행할 때 사용하며 default와는 달리 커스터마이징을 할 수 없습니다.
- ImageManager는 데이터를 이미지로 변환하는 작업을 하고 있고 request아닌 url로 요청을 보냅니다. 원래는 캐시를 들고 있는 싱글턴 구조도 생각했었는데 URLCache를 사용하게되면서 기존의 NetworkModule과 로직이 거의 흡사해진 것 같습니다. MediaNetworkable 프로토콜을 따르도록 하여 각종 미디어들을 다운/변환/가공하는 작업을 해줄 예정이었는데 엘림의 말씀을 듣고보니 중복코드를 최소화하는 식으로 리팩토링을 할 수 있는지 고민해보면 좋을 것 같습니다 🤩

#### SceneDelegate
- 이 부분은 엘림의 블로그를 우연찮게 보고 따라해봤어요ㅎㅎ 
- iOS12까지는 Process LifeCycle과 UI Lifecycle App Delegate에서 모두 관여했습니다.
- 멀티태스킹을 위하여 iOS13부터는 Process LifeCycle과 Session Lifecycle만 App Delegate가 맡으며, Scene Delegate가 UI Lifecycle 부분만 담당하게 바뀌되어 SceneDelegate에서 RootViewController를 만들어 첫 화면으로 보이도록 설정하였습니다.
- `makeKeyAndVisible()`을 실행해주어야 윈도우가 나타났습니다. 더 찾아보니 key로 만들어준 윈도우는 다른 윈도우보다 앞에 배치되며 키보드 입력 등을 받는다는 것을 알게되었습니다.

1) 연결될 scene을 `scene(_:willConnectTo:option:)`메서드로부터 전달받으면 그것을 윈도우에 담아줍니다.
2) scene을 UIWindowScene으로 다운캐스팅하여 UIWindow을 생성합니다.
3) window.rootViewController에 보여주고자 하는 ViewController를 대입시켜줍니다.
4) makeKeyAndVisible()로 보여주게 합니다.


```swift
func scene(_ scene: UIScene, willConnectTo session: UISceneSession, options connectionOptions: UIScene.ConnectionOptions) {
    guard let windowScene = (scene as? UIWindowScene) else { return }
    window = UIWindow(windowScene: windowScene)
    let mainViewController = SomeViewController()
    let navigationController = UINavigationController(rootViewController: mainViewController)
    window?.rootViewController = navigationController
    window?.makeKeyAndVisible()
}
```

#### fatal 동작이 일어나지 않게 하는 방법은 없을까요?😀
Failable Initializers는 초기화를 실패했을떄를 대비하는 이니셜라이저로 알고 있습니다.
그래서 default로 fatal Error가 발생하도록 구현이 되어있었는데요.
initializers가 실패했을때는 fatalError로 앱이 종료되는게 아닌 에러를 보여주는것이 좋다고 생각이 됬습니다. 그래서 이전에 배운 assertionFailure를 사용해봤습니다.
```swift
    required init?(coder: NSCoder) {
        super.init(coder: coder)
        assertionFailure(WeatherConstants.initFailure.text)
    }
```


#### formatter에서 extension하는건 어때요?
좋은것 같습니다. formatter를 extension으로 분리하여 Cell이 formatter를 안들고 있게되어 역할을 분리할수도 있고, 타입메서드로 구현하여 굳이 인스턴스화를 하지 않아도 되는 장점이 생긴것 같아요!


#### lazy를 선택하는 기준
self를 통해 다른 프로퍼티에 접근하거나 인스턴스 메서드를 사용하여 초기화 하는 프로퍼티의 경우 lazy로 선언을 하였습니다. 하지만 해당 코드를 다시보니 프로퍼티에 lazy가 필요없는 프로퍼티에 lazy가 붙어있어 lazy가 필요없는 프로퍼티들은 lazy를 삭제 하였습니다.



#### super.init을 해야하는 이유

* 생각해보면 부모 클래스의 프로퍼티들이 모두 초기화 해야 자식 클래스에서 사용할수 있다고 생각합니다.
  * 자식 클래스가 부모 클래스의 메서드를 오버라이드하고 있는 경우 부모 클래스가 해당 메서드에서 정의한 내용을 super.init()으로 실행해주어 부모 클래스가 의도한 부분도 온전히 실행되도록 해야한다고 생각합니다. 그래야만 부모 클래스에서 필수적으로 해주어야하는 기초 세팅을 마무리해 자식 클래스에서 버그나 오작동 없이 실행할 수 있다고 알고 있습니다.
  * 그리고 viewDidLoad()의 경우 [super.init()을 호출하라고](https://developer.apple.com/documentation/appkit/nsviewcontroller/1434476-viewdidload#:~:text=If%20you%20override%20this%20method%2C%20call%20this%20method%20on%20super) 되어 있는 것 같습니다.
* Swift의 class 초기화 과정은 Two Phase Initialization 과정을 거칩니다.
* Phase1에서는 각 저장된 프로퍼티를 정해진 초기값으로 초기화하는 과정입니다.
* Phase2에서는 새로운 인스턴스의 사용이 준비됐다고 알려주기 전에 저장된 프로퍼티에 대해 수정할수 있습니다.
![](https://i.imgur.com/jd2n0gY.png)

2021-10-20 23:39 UTC, jgkim1008 commented on WeatherForecast/WeatherForecast/WeatherForecastViewController.swift
> +    private let downloadDataGroup = DispatchGroup()
self를 통해 다른 프로퍼티에 접근하거나 인스턴스 메서드를 사용하여 초기화 하는 프로퍼티의 경우 lazy로 선언을 하였습니다. 하지만 해당 코드를 다시보니 프로퍼티에 lazy가 필요없는 프로퍼티에 lazy가 붙어있어 lazy가 필요없는 프로퍼티들은 lazy를 삭제 하였습니다.

2021-10-20 23:47 UTC, joey-ful commented on WeatherForecast/WeatherForecast/WeatherForecastViewController.swift
> +                downloadDataGroup.leave()
- 지금 날씨 앱에서는 `현재날씨`와 `5일치날씨`를 한 화면에서 동시에 보여주고 있습니다.
- 컬렉션뷰를 **한번에 업데이트하기 위해** `현재날씨`와 `5일치날씨`를 모두 받아온 시점을 알고 싶었습니다.
- 따라서 각 데이터에 대한 요청을 하기 전에 group에 enter를 하고 비동기 작업이 끝난 직후 leave를 해주었습니다.
- notify()를 해주면 group에 enter한 수만큼 leave되었을 때를 알 수 있어
다운받고 싶은 데이터들이 모두 받아진 시점을 알 수 있어 유용하다고 판단했습니다.

세마포어를 사용한다면 한번에 실행되는 비동기 작업의 수를 제한할 수 있는데
저희는 작업의 수를 제한하기보다는 비동기 작업들이 **모두 완료된 시점**을 알고 싶었기에 dispatchGroup을 사용했습니다!

2021-10-20 23:47 UTC, joey-ful commented on WeatherForecast/WeatherForecast/Extension/UILabel+Extension.swift
> +import UIKit
앗 실수로 지우지 않아 Foundation을 제거했습니다!

2021-10-20 23:49 UTC, joey-ful commented on WeatherForecast/WeatherForecast/Extension/UIAlertController+Extension.swift
> +        let alert = UIAlertController(title: "위치변경",
상수들을 저장했고 더 큰 의미를 갖기 위해 Placeholder를 WeatherConstant로 변경했습니다!
NSLocalizedString()으로 지역화해주는 부분도 해당 타입에서 함께 처리해주었습니다 🤩

2021-10-20 23:50 UTC, jgkim1008 commented on WeatherForecast/WeatherForecast/Extension/UIAlertController+Extension.swift
> +        let changeAction = UIAlertAction(title: "변경", style: .default) {_ in
- UIAlertAction의 style은 default ,cancel, destructive 총 3가지 종류가 있습니다.
- default와 cancel은 둘다 파랑색으로 font이지만 cancel은 font가 bold로 구성되었습니다. 
- destructive는 빨간색으로 font가 나옵니다.
![image](https://user-images.githubusercontent.com/52707151/138187450-58bcaf9a-212f-45a7-af55-e03f95fb7717.png)

* default와 cancle은 보통 ok 또는 취소에 주로 사용됩니다.
* destructive는 이버튼을 클릭하면 데이터를 삭제하거나 변경됨을 알려주는것일때만 사용해야합니다.그래서 주로 cancel을  destructive로 사용하는것은 주의해야 하는것으로 알고 있습니다.

2021-10-20 23:52 UTC, jgkim1008 commented on WeatherForecast/WeatherForecast/Extension/UIAlertController+Extension.swift
> +    static func makeValidLocationAlert(
* 중복되는 코드를 extension으로 만들어서 범용성 있게 사용하고 싶었습니다.
* 타입 메서드로 인스턴스화를 하지 않아도 해당 메서드를 통해 alertController를 만들고 싶었습니다.
* 마지막으로 extension을 통해 역할을 분리할수 있는 장점이 있다고 생각했습니다.

2021-10-22 04:02 UTC, lina0322 commented
여러분... 정말 너무 공부를 잘해주셔서 감동입니다ㅠㅠㅠㅠㅠ.. 
최고에여! 이렇게 정리해두면 나중에도 기억이 잘날거고, 기억안나면 와서 또 보면되겠네요!!!
👍👍👍👍👍👍👍👍

2021-10-22 04:02 UTC, merged