Step 1 : 타입 구현 (Joons)
yagom-academy/ios-weather-forecast pull request #7
Opened 2021-01-18 16:48 UTC by elddy0948

@myssun0325  
안녕하세요 메이슨! 😄
리뷰 부탁드립니다!

⭐️AppDelegate, SceneDelegate에서 iOS 버전에 맞게 어노테이션을 추가해 주었습니다.
⭐️JSON에서 화면구현에 필요한 정보에 대해서만 타입으로 정의하였습니다.
⭐️각각의 타입에 데이터가 올바르게 들어가는지에 대한 간단한 Unit Test를 만들어 보았습니다.

⭐️[타입 목록]
 - Coordinate : 좌표를 위한 타입
 - Weather : 날씨 정보를 담기 위한 타입
 - Temperature : 온도(최소, 최대, 체감), 기압, 습도 정보를 위한 타입
 - CurrentWeather : 현재 날씨에 대한 타입
 - Forecast : 5일간의 3시간마다의 날씨 타입
 - ForecastFiveDays : 5일간의 날씨를 나타내기 위한 타입

2021-01-19 18:13 UTC, myssun0325 requested changes
수고하셨습니다. Joons가 모든 테스트를 통과하셨군요! ㅋㅋㅋ
모델도 잘 나누셨고, 테스트 코드를 쓰신게 너무 훌륭합니다. 👏👏👏
(너무 훌륭한 나머지 연산프로퍼티의 활용에 대해서 코멘트를 달아봤습니다.)

저한테 말씀해주셨던 고민1, 고민2를 멋지게 해내신거같습니다.

고민1: 지금 단계에서는 고민1에 대한건 너무 멋지게 해낸거 같습니다. 스텝이 올라가면서 직접 모델을 사용하게 되다보면 또 모델에 대한 관점이 변경될거라 지금 너무 완벽한 모델링에 대한 압박을 받지 않으셔도 됩니다.!!
모델링 관련해서 인상깊게 보았던 부분은 본인이 판단하시기에 필요하다고 생각되는 부분만 최소로 모델링을 하신 부분이었는데, 굉장히 좋은 습관이라고 생각합니다. 불필요하게 내려오는 모든 값을 모델링하기보단 필요하다고 판단되는 값과 실질적으로 사용되는 값 위주로 모델링을 하여 모델이 너무 커져서 많은 책임과 일을 하지 않도록 하는게 중요합니다.

비슷해보이거나 반복이 일어난다고해서 무조건 코드를 줄이기 위해서 묶거나 나누기보단 다양한 요구사항들을 만나면서 주어진 요구사항을 명확히 이해하고 그때마다 Joons만의`기준`을 세워가면서 유연한 설계를 위한 연습을 하시면 될거같습니다.

고민2: 유닛테스트를 너무 훌륭하게 작성하셨습니다. 저도 모델설계가 잘되어있는지 확인하기 위해서 사용하는 방법입니다. 👍
추가적으로 테스트 부분에 대한 고민을 하고 계시다면 테스트 메서드도 메서드라는 접근을 하자면, 테스트 메서드도 단일책임원칙에 의해 작게 나누고, 한가지 테스트에 집중하도록 연습해보는것도 좋습니다 :) 

수고하셔써용 💯 

(커밋메시지를 저보다도 잘쓰시는거 같네요^^)

2021-01-19 18:19 UTC, myssun0325 commented on WeatherForecast/WeatherForecast/Models/CurrentWeather.swift
> +        case cityID = "id"
이미 Codable과 CodingKey를 잘 활용하고 계신데요. 현업에서도 무적권 사용되는 프로토콜이라서 한번 두드리고 넘어갑니다!
Codable과 CodingKey는 각 프로토콜은 무엇이고, 언제사용하는 것일까요? 간단히 설명해주실 수 있을까요?
(+ Codable은 어떤 프로토콜들의 컴포지션일까요? Codable을 사용하신 이유에 대해서도 간략히 말씀해주실 수 있나요?)

2021-01-20 06:49 UTC, elddy0948 commented
@myssun0325 
리뷰 감사합니다! 정말 많은 생각을 해볼 수 있었어요 😄

[이번에는 이런 고민을 해봤어요!]

- 좌표라는 의미의 Coordinate라는 네이밍 보다는 저 좌표를 활용해서 나타내는 것은 결국 사용자의 위치 라는 생각을 다시 한번 해 보았습니다. 메이슨의 힌트로 부터 찾은 결과 Core Location의 CLLocation에서 위도와 경도는 CLLocationDegree라는 타입을 가지고 있었습니다. (Location Degree : 위치의 각도(?)로 해석이 되었습니다.) 그렇기 때문에 이 위도와 경도를 포함하고 있는 타입의 네이밍은 Location Degree가 좀 더 명확하다고 생각하여 LocationDegree로 변경하였습니다. 

- Current Weather 즉, 현재 날씨에 대한 날씨정보는 물론 받아올때는 List의 형식으로 받아오지만 실질적으로 사용하는 날씨는 제일 앞에 있는 날씨만을 사용하게 될 것이라는 메이슨의 말에 동의하였고, 그에 따른 코드를 수정해 보았습니다. 👍 Weather에서  weathers.first 또는 weather[0]을 사용하는 방법 대신 연산 프로퍼티를 사용하여 currentWeather.weather 로 깔끔하게 받아오는 방식을 고민해 보았습니다. 

- Codable과 CodingKey를 활용한 부분에 대해서 다시한번 고민을 해 보았습니다.  (Codable -> Decodable)

2021-01-20 06:49 UTC, elddy0948 commented on WeatherForecast/WeatherForecast/Models/CurrentWeather.swift
> +        case cityID = "id"
- Codable은 Encodable 프로토콜과 Decodable프로토콜이 합쳐진 typealias입니다. Codable을 사용하면 Encodable과 Decodable의 프로토콜을 모두 준수하는 것으로 Encodable이나 Decodable 둘 중 어느 타입에도 맞출 수 있는 타입이 될 수 있습니다. Codable을 사용한 이유는 특별한 이유는 없으며, 그냥 둘을 합쳐놓았다는 것에 의의를 두고 사용하였습니다. 하지만 이 글을 작성하면서 다시한번 생각해 보니 굳이 Encoding을 해 줄 필요가 없는데 사용하지 않는 Encodable 프로토콜까지 준수해줄 필요가 없다고 느껴 이번 수정에서 Decodable로 수정해 주었습니다.
- CodingKey는 Encoding이나 Decoding 키로 사용할 수 있는 타입입니다. 주로 JSON 형식의 데이터를 받아올 때 키의 네이밍이 본인이 사용하려는 네이밍과 다를때, 혹은 snakecase를 사용하여 들어온 키를 camelcase로 받고싶거나 보내고 싶을 때 사용하는 프로토콜 입니다!

2021-01-20 06:51 UTC, elddy0948 commented on WeatherForecast/WeatherForecast/Models/Temperature.swift
> +    let actual: Double
actual을 수정하려고 타입을 보니, temperature.min, temperature.max, temperature.feelsLike 와 같은 것도 actual과 비슷하게 값을 나타낸다고 생각이 들지 않았습니다. 😥
그래서 maxTemp, minTemp, feelsLikeTemp 와 같이 정말 명확하게 '온도!'라고 명시해 주기에는 temperature.feelsLikeTemp 를 사용할 시 temp라는 중복되는 단어가 있어 별로인것같고, value라는 단어를 사용하기에도 조금 좋지 않은 것 같습니다 😥 
이부분에 네이밍에 대한 고민이 조금 있습니다! 어떤 방식으로 생각해보면 좋을까요..? ㅠㅠ

2021-01-20 11:31 UTC, myssun0325 commented on WeatherForecast/WeatherForecast/Models/Temperature.swift
> +    let actual: Double
네이밍의 가이드는 있지만 정답은 없는거 같아요~! 게다가 저희가 원어민도 아니기 때문에 😂 
(저는 temperature.value를 쓰거나 섭씨와 화씨가 존재한다면 연산 프로퍼티로 계산을 해주는것도 방법일거 같네요.)
정해진 정답은 없지만 생각없이 네이밍을 하는것과 고민을 하고 네이밍을 하는 것엔 큰 차이가 있을거 같아요 이미 충분히 고민을 하신거 같고 이해하는데 지장이 없다면 저는 좋은 네이밍인거 같습니다!! (혼란을 주는 네이밍만은 피하는게 좋아요)

2021-01-20 11:31 UTC, myssun0325 commented on WeatherForecast/WeatherForecast/Models/CurrentWeather.swift
> +        case cityID = "id"
Goooood. 👍

2021-01-20 11:40 UTC, myssun0325 commented
수고하셨습니다!

제꺼 스펠링치기 매번 힘드시죠...?? 걍 메이슨이라고 하시면됩니다.. 죄송해요 아이디를 어렵게 지어서...ㅋㅋㅋ
1. Core Location에서는 CLLocationCoordinate라는 이름이 사용되고 있군요, 요기서 프레임워크를 빼서 일반적으로 쓰이는 `LocationCoordinate` 는 어떤가요? -> (요건 선택사항입니당. 일단 다음 스텝으로 진행하면서 고민해보시죵!)
2. 오! first를 쓴거 굉장히 잘하신거 같습니다. 첫번째 요소라든지 마지막 요소는 인덱스로 접근하는 방법보다 first last를 활용하는게 좋습니다. 잘못된 인덱스로 실수할 가능성이 있기 때문이죠.
3. Codable과 CodingKey에 대한 개념을 잘 숙지하신거 같습니다. 👏👏👏

제가 남기는 리뷰만이 정답은 아닙니다.
반대로 Joons가 어떻게 이런 코드를 작성하게됐는지 본인만의 기준과 이유를 설명하면서 저를 설득시키는 것도 때론 필요할지 모릅니다 ;) 
앞으로 상호적으로 재밌게 이 프로젝트를 마쳐봅시다 !!!

2021-01-20 11:41 UTC, merged