날씨 정보(전) [STEP 3] 산체스
yagom-academy/ios-weather-forecast pull request #70
Opened 2021-10-19 10:19 UTC by sanches37

@jungseungyeo 

안녕하세요 린생~!
고민을 하다가 너무 늦어질 것 같아서, 부족하지만 PR을 보냅니다.

### 고민한점
뷰의 레이아웃이 변경되는 것에 대비하기 쉽고,뒷 스탭에서 가로화면 전환 구현이 있어서, TableView 보다 CollectionView 로 구현하면 가로화면에서도 레이아웃 구현하는데 좋다고 생각해서 CollectionView 로 구현하였습니다.

이미지캐시를 적용했는데, 현 상태에서는 이것만으로도 지연로딩에 문제가 되지 않을 거라 생각해서 따로 지연로딩에 관한 코드를 구현하지 않았습니다.

리프레쉬 컨트롤러를 구현했는데, 작동이 원할하지 않아서 고민을 오래하던 중 PR을 보내고 린생께 여쭤보는게 빠르겠다고 생각했습니다.
리프레쉬 컨트롤을 실행했을 때 경도, 위도 값을 아에 못받아오거나 일부만 받아오는 현상이 생겼습니다. 
제대로 못받아왔을 때 다시 리프레쉬 컨트롤을 실행하면 온전히 받아오게 됐는데, 이 부분에서 정확한 문제점을 파악하지 못했습니다.
여러군데서 받아오는 데이터들의 시점이 문제가 될까봐, 디스패치 그룹을 사용해서 모든게 받아온 뒤 화면을 리프레쉬 할 수 있도록 코드를 수정했지만, 문제가 해결 되지 않았습니다. 그러던 중 리프레쉬 컨트롤을 작동했을 때 디스패치 그룹 내부에서 실행하는 코드들이 두번씩 엇갈려 호출되서 문제가 있다는걸 알게됐습니다.

```swift
private func processWeatherImpormation(completion: @escaping () -> Void) {
       
            guard let location = currentLocation else { return }
            let currentWeatherURL =
            WeatherURL.weatherCoordinates(latitude: location.coordinate.latitude,
                                          longitude: location.coordinate.longitude)
            let fiveDaysWeatherURL =
            WeatherURL.forecastCoordinates(latitude: location.coordinate.latitude,
                                           longitude: location.coordinate.longitude)
        
        DispatchQueue.global().async {
            let group = DispatchGroup()
            group.enter()
            self.getWeatherImpormation(request: fiveDaysWeatherURL,
                                  type: FiveDaysWeather.self) { result in
               
                if let result = result {
                    self.collectionViewDataSource.fiveDaysWeather = result
                }
                print("1")
                group.leave()
            }
            
            group.enter()
            self.getWeatherImpormation(request: currentWeatherURL,
                                  type: CurrentWeather.self) { result in
                
                if let result = result {
                    self.collectionViewDataSource.currentWeather = result
                }
                print("2")
                group.leave()
            }
            
            group.enter()
            self.locationManager.getUserAddress(location: location) { address in
                switch address {
                case .success(let data):
                    self.collectionViewDataSource.currentAddress = data
                case .failure(let error):
                    self.handlerError(error)
                }
                print("3")
                group.leave()
            }
            
            group.wait()
            print("4")
            completion()
        }
```
위 코드를 실행했을 때 앱 로딩 후에는 정상적으로 프린트 출력이 되었지만, 이후 리플레쉬 컨트롤 작동 시 엇갈려 호출되는걸 알게됐습니다.
현재 코드상에서 여러번 호출되는 상황이 무엇 때문인지 고민을 하다가 리플레시 컨트롤을 정상적으로 구현하지 못한채 PR을 보내게 됐습니다.

앱 실행시 print 출력

<img width="616" alt="스크린샷 2021-10-19 오후 7 15 42" src="https://user-images.githubusercontent.com/84059338/137890530-af8f3b0b-56c6-4a0a-ac33-33a2d2aeadb3.png">

리플레시 컨트롤 작동시 출력

<img width="654" alt="스크린샷 2021-10-19 오후 7 17 52" src="https://user-images.githubusercontent.com/84059338/137890791-b95f25f1-fa17-4545-8164-f75657d2bb94.png">

이번 리뷰도 잘 부탁드립니다 😊🙏🏼

2021-10-19 12:58 UTC, jungseungyeo requested changes
산체스 step3고생하셨습니다. 

step3를 하면서 많은 고민을 하고 구현을 하였다고 느꼈습니다. :) 동시성으로 api를 3개를 기다리는 것을 구현하는 방식을 사용한 것도 좋았습니다.

고민한점

> 고민한 부분을 실제로 보았는데요. 시뮬레이터에서만 나오고 실제 디바이스 빌드시 발생을 하지 않네요.. 정확한 원인은 모르겠지만 해결을 한 번 해보았으면 좋겠습니다.  

https://webclub.tistory.com/607

Debounce와 Throttle라는 개념이 있습니다. 이것을 직접 구현하여 해결해보면 좋을거 같아요. :) 

또 코멘트에서 이야기 한 거 처럼 이미지 캐시와 imagerequest cancel을 구현을 해주세요. 이번 학습에서 꼭 필요한 부분이라 요청드립니다.  또 코멘트에 답변을 달아주세요.

2021-10-19 12:58 UTC, jungseungyeo commented on WeatherForecast/WeatherForecast/Views/FiveDaysWeatherCell.swift
> +            imageManager.fetchImage(url: ImageURL.weather(icon).path) { image in
```suggestion
            imageManager.fetchImage(url: ImageURL.weather(icon).path) { result in
```
로 하는게 좀 더 명확한 네이밍인거같아요.

2021-10-19 12:58 UTC, jungseungyeo commented on WeatherForecast/WeatherForecast/Managers/ImageManager.swift
> +    func fetchImage(
cancel은 따로 구현하지 않느 건가요?

2021-10-19 12:58 UTC, jungseungyeo commented on WeatherForecast/WeatherForecast/CollectionView/WeatherCollectionViewDataSource.swift
> +        cell.resetContents()
여기서 resetContents()를 호출하는 것보다 cell 내부에서 해주는 것이 좋아요. controller에서 작성하게 되면 controller가 cell의 대해서 좀 더 알아야되어 의존성이 커지게 되는거 같아요.

2021-10-19 12:58 UTC, jungseungyeo commented on WeatherForecast/WeatherForecast/CollectionView/WeatherCollectionViewDataSource.swift
> +class WeatherCollectionViewDataSource: NSObject {
따로 DataSource를 만든 이유가 있을까요?

2021-10-19 12:58 UTC, jungseungyeo commented on WeatherForecast/WeatherForecast/Controllers/WeatherImpomationViewController.swift
> +            processWeatherImpormation {
fetch라는 함수를 만들어서 여기서는 호출만 해주면 좀 더 코드가 깔끔해질거 같아요.

2021-10-19 12:58 UTC, jungseungyeo commented on WeatherForecast/WeatherForecast/Controllers/WeatherImpomationViewController.swift
> +        DispatchQueue.global().async {
DispatchQueue.global().async를 사용하는 이유가 있나요?

2021-10-19 12:58 UTC, jungseungyeo commented on WeatherForecast/WeatherForecast/Controllers/WeatherImpomationViewController.swift
> +            group.wait()
wait()를 사용하지 않고 notifyf를 사용하는 방법은 어떤가요?

2021-10-19 12:58 UTC, jungseungyeo commented on WeatherForecast/WeatherForecast/Extensions/DateFormatter + convertDate.swift
> +        dateFormat = "MM/dd(E) HH시"
이런 형식을 무엇이라고 하나요? 따른 형식은 어떤게 있을까요? 
https://ko.wikipedia.org/wiki/ISO_8601 국제 표준 날짜 표시내용이 있어요 한번 참고해주세요 :)

2021-10-19 12:58 UTC, jungseungyeo commented on WeatherForecast/WeatherForecast/Layout/CompositionalLayout.swift
> +    func create(
파라미터 갯수가 많고 함수의 크기가 너무 큰거 같아요. 한 번 줄여서 사용하는 방법을 사용해주세요

2021-10-19 12:58 UTC, jungseungyeo commented on WeatherForecast/WeatherForecast/Managers/LocationManager.swift
> +    func locationManager(_ manager: CLLocationManager,
여기서 위치 정보가 리플레쉬또는 위치 정보 요청시 여러번 호출이 되고 있어요. 흠.. 실제로는 한번만 호출되어야 하는데.. 이상하네요 ㅎㅎ..

2021-10-19 12:58 UTC, jungseungyeo commented on WeatherForecast/WeatherForecast/Views/CurrentWeatherHeaderView.swift
> +        imageManager.fetchImage(url: ImageURL.weather(icon).path) { image in
cell이 재사용 할 때 마다 ulr을 요청하네요. cancel하고 cache 로직을 추가하면 좋을거같아요.

2021-10-19 12:58 UTC, jungseungyeo commented on WeatherForecast/WeatherForecast/Views/FiveDaysWeatherCell.swift
> +            return "https://openweathermap.org/img/w/\(id).png"
이곳보다는 모델에서 저장 할때 가지고 있는게 좋을거같아요.

2021-10-19 12:58 UTC, jungseungyeo commented on WeatherForecast/WeatherForecast/Layout/CompositionalLayout.swift
> +            UICollectionViewCompositionalLayout { (_, _) -> NSCollectionLayoutSection? in
UICollectionViewCompositionalLayout를 사용한 이유가 있나요?
이번 학습 목표는 아니여서 궁금합니다.

2021-10-19 12:58 UTC, jungseungyeo commented on WeatherForecast/WeatherForecast/Protocols/LocationProtocol.swift
> +    var locationManagerDelegate: LocationManagerDelegate? {
step2에서 이 delegate가 weak가 아니였어요. weak를 붙여주면 좋을거같아요. 또 왜 weak를 붙어주어야할까요?

2021-10-20 04:20 UTC, sanches37 commented on WeatherForecast/WeatherForecast/Views/FiveDaysWeatherCell.swift
> +            imageManager.fetchImage(url: ImageURL.weather(icon).path) { image in
result 가 더 명확한 네이밍인 것 같습니다. 수정했습니다. 😀

2021-10-20 04:34 UTC, sanches37 commented on WeatherForecast/WeatherForecast/Managers/ImageManager.swift
> +    func fetchImage(
requestCachePolicy = .returnCacheDataElseLoad 를 사용하여 캐시를 우선사용하도록 정책을 사용해서 추가 코드 없이 이미지 캐시가 이루어진다고 생각되었는데요.
```swift
let request = URLRequest(url: url, cachePolicy: .returnCacheDataElseLoad)
        
        if let response = cache.cachedResponse(for: request),
           let imageData = UIImage(data: response.data) {
            compleHandler(.success(imageData))
            return nil
        } else {
            let dataTask = session.dataTask(with: request) { data, response, error in
                if let convertResponse = response, let convertData = data {
                    self.cache.storeCachedResponse(
                        CachedURLResponse(
                            response: convertResponse, data: convertData), for: request)
                }
```
위와 같이 이미지가 있으면 캐시의 이미지를 쓰고 아니면 dataTask 로 받아오는 코드로 작성하라는 말씀이실까요?

dataTask를 cancel 하는 코드가 없다는 의미라면, URLSessionDataTask 를 반환값으로 가져서 cell에서 사용시 cancel 하는 코드를 추가할 생각입니다. 🙂

2021-10-20 04:39 UTC, sanches37 commented on WeatherForecast/WeatherForecast/CollectionView/WeatherCollectionViewDataSource.swift
> +        cell.resetContents()
resetContents 대신 prepareForReuse 로 셀이 재사용되기 전에 초기화하도록 수정하였습니다. 괜찮을까요? 🙂

2021-10-20 04:44 UTC, sanches37 commented on WeatherForecast/WeatherForecast/CollectionView/WeatherCollectionViewDataSource.swift
> +class WeatherCollectionViewDataSource: NSObject {
뷰컨트롤러가 많은 일을 처리하게 될 것 같아서 DataSource 나 Delegate 를 분리하여 사용하려는 의도였습니다. 😊

2021-10-20 04:49 UTC, sanches37 commented on WeatherForecast/WeatherForecast/Controllers/WeatherImpomationViewController.swift
> +            processWeatherImpormation {
didset 내부에서 fetchWeatherImpormation 메서드만 호출하도록 변경했습니다. 😃

2021-10-20 06:09 UTC, sanches37 commented on WeatherForecast/WeatherForecast/Controllers/WeatherImpomationViewController.swift
> +        DispatchQueue.global().async {
DispatchQueue.global().async 내부 코드들이 비동기적으로 호출되도록 하기 위해서 사용했습니다. 😀

2021-10-20 06:50 UTC, sanches37 commented on WeatherForecast/WeatherForecast/Controllers/WeatherImpomationViewController.swift
> +            group.wait()
notify 로 그룹 완료 후 비동기적으로 사용하면서 DispatchQueue.global().async 코드를 없앨 수 있었습니다. 😆

2021-10-20 07:44 UTC, sanches37 commented on WeatherForecast/WeatherForecast/Views/FiveDaysWeatherCell.swift
> +            return "https://openweathermap.org/img/w/\(id).png"
View인 cell 에서 가지고 있는게 맞지 않는 것 같습니다. imageManager 폴더 내로 이동하였습니다. 😊

2021-10-20 07:55 UTC, sanches37 commented on WeatherForecast/WeatherForecast/Layout/CompositionalLayout.swift
> +            UICollectionViewCompositionalLayout { (_, _) -> NSCollectionLayoutSection? in
따로 특별한 이유는 없고, 여러 레이아웃에 직관적으로 사용하기 편했고, 컬렉션뷰의 헤드뷰나 섹션이 나눠줬을 때도 쉽게 대응할 수 있어서 컴포지셔널 레이아웃을 선택해서 구현해봤습니다. 다만 IOS 13 이후 사용이라는 점이 좀 걸렸는데, IOS 14 이전 기능은 그냥 사용하자 싶어서 적용해보았습니다. 😃

2021-10-20 08:46 UTC, sanches37 commented on WeatherForecast/WeatherForecast/Views/CurrentWeatherHeaderView.swift
> +        imageManager.fetchImage(url: ImageURL.weather(icon).path) { image in
기존 코드에서도 메모리캐시가 되고 있다고 생각했는데, 코드상 확실히 캐시처리를 하고 있는지 알기 위해 imageManager 의 구조를 수정하고 확인해보니 캐시처리가 되고 있는 걸 확인했습니다. imageConfigure 메서드에서 해당 주소를 넣어주면 fecthImage 내부에서 판별 후 캐시된 이미지를 쓸지 네트워크로 받을지를 판별하는데 이런 구조가 괜찮을까요?
또 지연로딩 처리를 위해 fetchImage 리턴값을 가지게 구조를 바꿨습니다. prepareForReuse에서 이미지가 셀에 적용하기 전에, 셀이 재사용되거나 하는 경우 가지고 온 이미지를 무시하도록 코드를 적용했습니다.😀

2021-10-20 09:00 UTC, sanches37 commented on WeatherForecast/WeatherForecast/Protocols/LocationProtocol.swift
> +    var locationManagerDelegate: LocationManagerDelegate? {
변경했습니다! weak 이 없으면  self.locationManager.locationManagerDelegate = self 코드에서 locationManagerDelegate 와 LocationManager 가 순환 참조되어 메모리 해제가 안될 것 같습니다. 😃

2021-10-20 09:16 UTC, sanches37 commented on WeatherForecast/WeatherForecast/Managers/LocationManager.swift
> +    func locationManager(_ manager: CLLocationManager,
공유해주신 자료로 debounce 를 이해하고, 같은 문제를 가지고 있던 조스트의 코드를 참고하여 debounce 를 구현해서 리플레시 컨트롤이 잘 작동하게 수정하였습니다. 감사합니다. 😆

2021-10-20 11:37 UTC, sanches37 commented on WeatherForecast/WeatherForecast/Layout/CompositionalLayout.swift
> +    func create(
파라미터의 갯수를 줄이기 위해 protocol, enum 을 이용해 전달할 타입을 만들고, 매개변수로 전달하는 구조로 변경하였습니다.
메서드 크기를 줄이기 위해 내부 item, group, header 에 해당하는 부분을 각각 메서드화 해서 create 내에서 호출하도록 하였습니다.
위와같은 방식이 유도하셨던 방법이 맞는지 모르겠습니다. 😅

2021-10-20 12:37 UTC, sanches37 commented on WeatherForecast/WeatherForecast/Extensions/DateFormatter + convertDate.swift
> +        dateFormat = "MM/dd(E) HH시"
공유해주신 내용을 읽어보니 날짜와 시간과 관련된 데이터 교환을 다루는 국제 표준이군요. 감사합니다.
ISO8601DateFormatter.formatOptions = [.withDay, .withMonth, .withYear, .withTime] 로 지정한 요소만 보일 수 있게 하는 방법도 있더군요. ISO8601DateFormatter 도 사용해보려 했지만, 요일이 없는 것 같아서 현재구조를 유지하는 방향으로 정했습니다. 😃

2021-10-22 11:22 UTC, jungseungyeo approved these changes
산체스! 너무 고생하셨어요! 이번에 작성한 코드를 보면서 많은 노력을 보았습니다. protocol을 활요하고 역할을 나누는 부분에서 매우 잘 하셨습니다. 또한 bounce를 구현하여 좀 더 안정성이 있는 코드를 작성한 부분도 좋았습니다. 고생하셨습니다. 

protocol을 사용하는 것은 좋지만 구현해야되는 부분이 많아 지면 코드의 복잡도와 의존성이 높아 진다는 걸 잊지마세요! 수고하셨습니다.

2021-10-22 11:22 UTC, jungseungyeo commented on WeatherForecast/WeatherForecast/Controllers/WeatherImpomationViewController.swift
> +        timer = Timer.scheduledTimer(withTimeInterval: 0.3, repeats: false) { timer in
debounce는 여기가 아니고 delegate에서 호출해주면 좋을거같아요. 또 DispatchQueue와 DispatchWorkItem를 활요하면 좋을거같아요.

2021-10-22 11:22 UTC, jungseungyeo commented on WeatherForecast/WeatherForecast/Controllers/WeatherImpomationViewController.swift
> +        timer = Timer.scheduledTimer(withTimeInterval: 0.3, repeats: false) { timer in
https://stackoverflow.com/questions/27116684/how-can-i-debounce-a-method-call <- 여기를 참고하면 좋을거같아요.

2021-10-22 11:22 UTC, jungseungyeo commented on WeatherForecast/WeatherForecast/Protocols/LocationProtocol.swift
> +    weak var locationManagerDelegate: LocationManagerDelegate? {
너무 좋아요 :)

2021-10-22 11:22 UTC, jungseungyeo commented on WeatherForecast/WeatherForecast/Controllers/WeatherImpomationViewController.swift
> +            group.notify(queue: .global()) {
너무 좋습니다 :)

2021-10-22 11:22 UTC, jungseungyeo commented on WeatherForecast/WeatherForecast/Controllers/WeatherImpomationViewController.swift
> +        collectionView.collectionViewLayout = layout.layout()
layout.layout이라는 네이밍은 이상하네요 ㅠ

2021-10-22 11:22 UTC, jungseungyeo commented on WeatherForecast/WeatherForecast/Protocols/CompositionalLayoutProtocol.swift
> +    func layout() -> UICollectionViewLayout
파라미터가 다 사라졌네요 ㅎㅎ 너무 좋아요. 이야기 한 거 처럼 구현해야되고 알아야되는게 많을 수록 의존성은 높아지고 복잡도가 높아지니 조심해주세요 :)

2021-10-22 11:22 UTC, jungseungyeo commented on WeatherForecast/WeatherForecast/Managers/DebounceManager.swift
> +    func processDebounce(interval: TimeInterval = 0.3, action: @escaping (() -> Void)) {
queue도 받아서 처리하면 더 좋았을거같네요 ㅎㅎ 그래도 너무 좋습니다.

2021-10-22 11:22 UTC, merged