Step1: 타입 구현 (꼬말)
yagom-academy/ios-weather-forecast pull request #8
Opened 2021-01-18 17:02 UTC by hakju

@cmindy 
안녕하세요 민디!!
늦은 시간에 언급해서 죄송합니다ㅠ
STEP1 구현하였습니다. 코드 리뷰 부탁드려요 :)

[구현한 점]

- 프로젝트 초기 설정 iOS13 이상 버전에서 SceneDelegate를 사용하기 위한 어노테이션 추가

- 타입 구현

1. Weather: 날씨 정보를 저장할 타입.
2. Temperature: (최고, 최저, 현재) 기온 정보를 저장할 타입.
3. City: (도시 단위) 위치 정보를 저장할 타입.
4. CurrentWeather: 현재 날씨를 나타내주기 위한 타입.
5. ThenWeather: 특정 시간의 날씨를 나타내주기 위한 타입.
6. FiveDaysWeather: 5일 동안의 날씨를 나타내주기 위한 타입.

2021-01-19 11:44 UTC, cmindy requested changes
고생하셨습니다 꼬말 👏  
모델들의 관계를 파악해서 잘 나눠주셨네요.
다만, 현재 모델로는 json 디코딩에 실패하고 있습니다. 실제 json 값을 넣어서 테스트 해보시면 확인 가능할거예요. (json과 모델의 키값이 일치하지 않는게 몇 개 보이네요 👻)

앗 그리고 언제든 언급하셔도 좋습니다 대환영!!!!!!!! 🎈

2021-01-19 11:44 UTC, cmindy commented on WeatherForecast/WeatherForecast/Weather.swift
> +    }
`CodingKeys` 프로토콜은 언제 사용하는 것일까요? 🤔

2021-01-19 11:44 UTC, cmindy commented on WeatherForecast/WeatherForecast/CurrentWeather.swift
> +        case city = "city"
JSON 키값과 모델명이 동일하면 CodingKey에서 값을 생략할 수 있습니다. ✨ 
값을 계속 입력하는 번거로움도 줄이고, 이 프로퍼티는 키값과 같다라는 의도가 될 수도 있겠네요

2021-01-19 11:44 UTC, cmindy commented on WeatherForecast/WeatherForecast/ThenWeather.swift
> +        case weatherIcon = "weather"
JSON 값과 모델을 잘 매치해주셨네요 🙌

2021-01-19 11:44 UTC, cmindy commented on WeatherForecast/WeatherForecast/CurrentWeather.swift
> +    let city: City
JSON의 기본 타입에는 String, Number, Array, Object 등이 있는데요.
`CurrentWeather`의 json을 보면 `name` 속성은 그냥 String 타입이네요. 
꼬말이 만들어주신 `City`는 어떤 걸 의미하는건가요? 🤓 
json과 모델의 뎁스가 일치하는지 확인이 필요해 보여요!

2021-01-19 11:44 UTC, cmindy commented on WeatherForecast/WeatherForecast/ThenWeather.swift
> +struct ThenWeather: Codable {
`Codable`은 두 프로토콜의 조합으로 만들어진 프로토콜입니다.
어떤 경우에 각 프로토콜들을 사용하는지 생각해 볼까요 ?

2021-01-21 13:17 UTC, hakju commented
@cmindy 
리뷰 감사합니다 민디!!

[리뷰내용]
1. CodingKeys 프로토콜은 언제 사용하는 것일까요?
- CodingKeys 프로토콜은 인코딩, 디코딩을 할 때 사용합니다. JSON에서 정한 key값과 구조체 내의 변수명과 다를 경우, 그것들을 매칭시켜주기 위함으로 알고있습니다. 같을 경우엔 생략가능하니 생략해보았습니다!

2. City의 의미는 무엇일까요?
- 처음에 City는 위치를 나타내기 위해서 생성했습니다. 명세서에 현재날씨에 해당되는 곳에 위치가 표현되었기에 CurrnetWeather에 추가해주었습니다. 그런데 JSON을 살펴보다가 5 days weather JSON을 currentweather JSON으로 착각하고 City구조체에서 name을 받아오게 생성해주었습니다. CurrentWeather에서 위치를 받아오는 변수를 새롭게 추가하였습니다.

3. Codable은 두 프로토콜의 조합으로 만들어진 프로토콜입니다. 어떤 경우에 각 프로토콜들을 사용하는지 생각해 볼까요?
- Codable은 Decodable 과 Encodable 의 조합으로 만들어진 프로토콜입니다. 디코딩, 인코딩을 사용하지 않는 구조체에 잘못 채택하고 있었네요. 수정하였습니다!


- 테스트해주기 위해서 JSON파일을 직접 생성해서 데이터가 담기는 지 확인했습니다. 이 과정에서 Temperature타입에서 오타를 발견하기도 하였고 직접 만들어준 JSON파일에 오타로 인해서 시간이 오래 지체되었습니다,,,,,,,,,,,,

2021-01-22 10:47 UTC, cmindy reviewed
아이구 JSON파일에 오타가 있었군요 ㅜㅜ.. 정말 저도 여러번 겪었는데... 그 때 생각하면 눈물이 앞을 가리네요 껄껄 🤦‍♀️ 
직접 json을 작성할 땐 JSON 문법 검사기를 활용하시면 아주..편합니다 ㅎㅎㅎ 👍  
지금 같은 경우에는 실제 api를 요청해볼수 있으니까 포스트맨 같은 API 툴을 이용해서 그 결과를 사용해도 좋구요!ㅎㅎ.. 꿀팁이 되었기를 바랍니당

추가적으로, 5 day weather 는 디코딩이 안되고 있긴 한데, 꼬말이 바로바로 충분히 고치실 수 있는 부분이라.. 🤩 
이번 스텝에서 해결하고 넘어갈지 아니면 일단 머지하고 다음스텝에서 해결할지 답변주세요!

2021-01-22 10:47 UTC, cmindy commented on WeatherForecast/WeatherForecast/CurrentWeather.swift
> +        case location = "name"
json.. 저도 자주 착각해요 ㅎㅎㅎ.. 정말 다들 비슷하게 생겨서 더 헷갈리지 않나요? 😭 🤯

2021-01-22 10:47 UTC, cmindy commented on WeatherForecast/WeatherForecast/FiveDaysWeather.swift
> +struct FiveDaysWeather {
이 구조체는 디코딩과 코딩키가 필요해 보이는데요 👀

2021-01-22 10:47 UTC, cmindy commented on WeatherForecast/WeatherForecast/Temperature.swift
> +        case maximumTemperature = "temp_max"
👍

2021-01-22 10:47 UTC, cmindy commented on WeatherForecast/WeatherForecast/FiveDaysWeather.swift
> +struct FiveDaysWeather {
> Codable은 Decodable 과 Encodable 의 조합으로 만들어진 프로토콜입니다. 디코딩, 인코딩을 사용하지 않는 구조체에 잘못 채택하고 있었네요. 수정하였습니다!

- 추가적으로 현재 날씨정보 프로젝트에서는 Decode만 일어나고 있는데,  `Encodable`이 필요한 프로토콜인가에 대해 생각해보시면 좋을 것 같아요 😄

2021-01-23 01:54 UTC, hakju commented
@cmindy 
꿀팁 감사합니다ㅠㅠㅠ
다음 스텝에서 진행해보겠습니다! 
머지 해주세요 :)

2021-01-24 12:58 UTC, cmindy approved these changes

2021-01-24 12:58 UTC, merged