Step 1 - Jacob
yagom-academy/ios-weather-forecast pull request #9
Opened 2021-01-18 19:10 UTC by KyungminLeeDev

Step 1 : 타입 구현

- JSON 데이터 중에 프로젝트에 필요한 내용만 구현
- CurrentWeather: Current weather data API의 JSON 데이터 모델
- WeatherForecast: 5 day weather forecast API의 JSON 데이터 모델

안녕하세요 @delmaSong
리뷰 부탁드립니다~

2021-01-19 13:50 UTC, delmaSong requested changes
수고하셨습니다!
CodingKey를 적절하게 사용하셨네요, 모델들을 한 폴더로 관리하는 점도 돋보였습니다 👍🏼
다만 현재 디코딩 작업이 제대로 이루어지지 않는 것 같으니 확인해주시고
리드미에 작성하신대로 10시에는 작업 마치시고 꿀잠 주무시길! 😴

2021-01-19 13:50 UTC, delmaSong commented on WeatherForecast/WeatherForecast/Model/Temperature.swift
> +    let maximumTemperature: Double
`Temperature`의 속성들이니까 반복해서 `-Temperature` 라는 접미사를 안붙여도 될 것 같아요
`currentTemperature`에는 오타가 있네요 🙂

2021-01-19 13:50 UTC, delmaSong commented on WeatherForecast/WeatherForecast/Model/Temperature.swift
> +    let currentTemperatrue: Double
이 온도의 단위는 어떻게 되나요? 단위 변환등의 작업은 어디서 하면 적당할까요?

2021-01-19 13:50 UTC, delmaSong commented on WeatherForecast/WeatherForecast/Model/CurrentWeather.swift
> +    enum CodingKeys: String, CodingKey {
요구사항에 현재 날씨는 날씨와 온도만 보여준다고 나와있나요?
JSON의 여러 필드 중 이 값들만 선정하신 이유가 무엇인지 궁금합니다
그리고 날씨와 온도가 같은 다른 날의 `CurrentWeather`는 어떻게 구분 가능한가요?

2021-01-19 13:50 UTC, delmaSong commented on WeatherForecast/WeatherForecast/Model/WeatherForecast.swift
> +}
넘어오는 값을 디코딩해서  확인해보셨나요? 잘 변환이 되던가요?

2021-01-20 11:09 UTC, KyungminLeeDev commented on WeatherForecast/WeatherForecast/Model/Temperature.swift
> +    let currentTemperatrue: Double
API 설명을 보니 API 요청할 때 온도 단위 선택할 수 있어서 섭씨 단위로 요청하려했습니다.

만약 단위 변환이 필요하다면, 단위 변환 연산이 큰 작업은 아니므로 연산 프로퍼티로 구현하려고 생각했습니다.

2021-01-20 11:11 UTC, KyungminLeeDev commented on WeatherForecast/WeatherForecast/Model/CurrentWeather.swift
> +    enum CodingKeys: String, CodingKey {
기획서의 데모 영상에 나와있는 데이터만 가져오려고 했습니다.
코멘트를 보고 생각해보니 날씨와 온도 말고도 위치, 시간 등의 데이터도 필요할 것 같아서 추가했습니다

2021-01-20 11:13 UTC, KyungminLeeDev commented on WeatherForecast/WeatherForecast/Model/WeatherForecast.swift
> +}
예시 JSON 파일을 만들어서 Unit Test로 테스트 해보니 실패하네요
모델 세부 구현을 꼼꼼히 다시 보고 수정해서 변환되는 것을 확인했습니다😅

2021-01-20 11:15 UTC, KyungminLeeDev commented
@delmaSong 코멘트를 보고 다시 고민해서 수정했습니다

다시 리뷰 부탁드려요😅

2021-01-20 11:56 UTC, delmaSong approved these changes
유닛테스트를 진행하셨군요. 모델이 제대로 설계되었는지, 알맞게 디코딩되는지 확인하기에 좋은 방법이죠!
다만 테스트 코드에서도 사용하지 않는 빈 메서드는 제거해주시고, 한 테스트 메서드에서는 되도록 한가지 테스트나 한 역할만을 담당하도록 작게 나눠주시면 더 좋을 것 같습니다 😀

모델을 설계할 때 필요하다고 생각하는 부분을 위주로 모델링을 하셨는데, 아주 좋은 습관입니다. 작업을 하면서 또 필요에따라 모델이 변경될 수도 있으니 지금 하셨던대로 작게 시작하면서 만드시면 될 것 같습니다! 

더불어 CodingKey와 Codable 프로토콜은 모델 설계시 아주 자주 사용되는 것들이니 이번 프로젝트를 통해서 사용법등에 익숙해지시면 좋겠네요!

이번 단계는 이쯤 하고 넘어가도 좋을 것 같습니다. 수고하셨습니다 😇

2021-01-20 11:56 UTC, merged